In [2]:
import pandas as pd
import numpy as np

In [3]:
#Veri tablosunu okuma
df = pd.read_excel (r'C:\Users\samay\Downloads\Data.xlsx')

In [4]:
#Burada Notebookta görüntüleyeceğimiz tablonun tüm satır sütunlarını daraltma olmadan görebilmemiz için işlem yaptık.
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 150)

In [5]:
#Üzerinde çalışma yapacağımız sütunlardan oluşan ana veri tablomuzu oluşturuyoruz
main_df=df[['MaritalStatus','Gender','EnglishEducation','EnglishOccupation','CommuteDistance','HouseOwnerFlag','Region',\
            'YearlyIncome','TotalChildren','NumberChildrenAtHome','NumberCarsOwned','Age','BikeBuyer']]
main_df.head(5)

,MaritalStatus,Gender,EnglishEducation,EnglishOccupation,CommuteDistance,HouseOwnerFlag,Region,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,BikeBuyer
0,M,M,Bachelors,Professional,1-2 Miles,1,Pacific,90000,2,0,0,48,1
1,S,M,Bachelors,Professional,0-1 Miles,0,Pacific,60000,3,3,1,43,1
2,M,M,Bachelors,Professional,2-5 Miles,1,Pacific,60000,3,3,1,49,1
3,S,F,Bachelors,Professional,5-10 Miles,0,Pacific,70000,0,0,1,46,1
4,S,F,Bachelors,Professional,1-2 Miles,1,Pacific,80000,5,5,4,40,1

In [6]:
#Burada yazı tipi(object) tüm sütunların önden ve arkadan boşlukları varsa o boşlukların hepsini yok ediyoruz
main_df.columns = main_df.columns.str.strip()

In [7]:
#Burada Ev ile işyeri arasındaki uzaklığı modelin kategorik şekilde değil numerik şekilde lineer olarak dikkate almasını sağladım. 
main_df["CommuteDistanceNumeric"] = np.where(main_df["CommuteDistance"]=="0-1 Miles", 1,\
                                            (np.where(main_df["CommuteDistance"]=="1-2 Miles", 2,\
                                             np.where(main_df["CommuteDistance"]=="2-5 Miles", 4,\
                                             np.where(main_df["CommuteDistance"]=="5-10 Miles", 7,11)))))

C:\Users\samay\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [8]:
main_df["HouseOwnerFlagText"] = np.where(main_df["HouseOwnerFlag"]==1, "Yes","No")

C:\Users\samay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [11]:
main_df=main_df[['MaritalStatus','Gender','EnglishEducation','EnglishOccupation','HouseOwnerFlagText','Region',\
            'YearlyIncome','TotalChildren','NumberChildrenAtHome','NumberCarsOwned','Age','CommuteDistanceNumeric','BikeBuyer']]
main_df.head(5)

,MaritalStatus,Gender,EnglishEducation,EnglishOccupation,HouseOwnerFlagText,Region,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer
0,M,M,Bachelors,Professional,Yes,Pacific,90000,2,0,0,48,2,1
1,S,M,Bachelors,Professional,No,Pacific,60000,3,3,1,43,1,1
2,M,M,Bachelors,Professional,Yes,Pacific,60000,3,3,1,49,4,1
3,S,F,Bachelors,Professional,No,Pacific,70000,0,0,1,46,7,1
4,S,F,Bachelors,Professional,Yes,Pacific,80000,5,5,4,40,2,1

### Kategorik verilerin işlenmesi için object formattan integer formatına çevrilmesi gerekli.Bu noktada get_dummies metodu yardımımıza koşar

get_dummies metodunu kullandıktan sonra dummies variable trap'den kurtulmak için bir değerini sileriz.

In [12]:
marital_dummies=pd.get_dummies(main_df.MaritalStatus)
marital_dummies

       M  S
0      1  0
1      0  1
2      1  0
3      0  1
4      0  1
5      0  1
6      0  1
7      1  0
8      0  1
9      0  1
10     0  1
11     1  0
12     1  0
13     1  0
14     0  1
15     0  1
16     1  0
17     0  1
18     0  1
19     0  1
20     0  1
21     0  1
22     1  0
23     1  0
24     1  0
25     1  0
26     0  1
27     1  0
28     1  0
29     1  0
30     1  0
31     1  0
32     1  0
33     1  0
34     1  0
35     1  0
36     1  0
37     0  1
38     1  0
39     1  0
40     1  0
41     1  0
42     1  0
43     1  0
44     1  0
45     0  1
46     1  0
47     1  0
48     1  0
49     0  1
50     1  0
51     0  1
52     0  1
53     1  0
54     1  0
55     1  0
56     1  0
57     1  0
58     1  0
59     0  1
60     1  0
61     1  0
62     1  0
63     0  1
64     1  0
65     1  0
66     1  0
67     0  1
68     0  1
69     0  1
70     1  0
71     0  1
72     0  1
73     0  1
74     0  1
75     0  1
76     0  1
77     0  1
78     0  1
79     0  1
80     1  0
81     1  0
82     0  1
83     1  0
84     0  1
85     0  1
86     1  0
87     1  0
88     1  0
89     0  1
90     0  1
91     1  0
92     1  0
93     1  0
94     0  1
95     0  1
96     1  0
97     1  0
98     0  1
99     1  0
100    0  1
101    0  1
102    0  1
103    0  1
104    1  0
105    0  1
106    0  1
107    1  0
108    0  1
109    0  1
110    1  0
111    1  0
112    1  0
113    1  0
114    0  1
115    1  0
116    1  0
117    1  0
118    0  1
119    0  1
120    0  1
121    1  0
122    1  0
123    1  0
124    0  1
125    0  1
126    1  0
127    1  0
128    1  0
129    0  1
130    1  0
131    1  0
132    0  1
133    0  1
134    0  1
135    0  1
136    0  1
137    1  0
138    1  0
139    0  1
140    0  1
141    1  0
142    0  1
143    1  0
144    0  1
145    0  1
146    0  1
147    1  0
148    1  0
149    1  0
150    0  1
151    0  1
152    0  1
153    1  0
154    0  1
155    0  1
156    0  1
157    1  0
158    0  1
159    0  1
160    0  1
161    0  1
162    0  1
163    1  0
164    0  1
165    1  0
166    0  1
167    0  1
168    0  1
169    1  0
170    1  0
171    0  1
172    1  0
173    0  1
174    1  0
175    0  1
176    1  0
177    1  0
178    1  0
179    1  0
180    1  0
181    1  0
182    0  1
183    0  1
184    0  1
185    0  1
186    0  1
187    1  0
188    1  0
189    0  1
190    1  0
191    0  1
192    1  0
193    1  0
194    1  0
195    1  0
196    1  0
197    1  0
198    0  1
199    1  0
200    1  0
201    1  0
202    1  0
203    1  0
204    1  0
205    1  0
206    1  0
207    0  1
208    1  0
209    1  0
210    1  0
211    1  0
212    1  0
213    0  1
214    0  1
215    1  0
216    0  1
217    0  1
218    0  1
219    1  0
220    1  0
221    1  0
222    1  0
223    0  1
224    0  1
225    1  0
226    1  0
227    0  1
228    1  0
229    0  1
230    1  0
231    1  0
232    1  0
233    1  0
234    0  1
235    1  0
236    0  1
237    0  1
238    0  1
239    1  0
240    1  0
241    0  1
242    1  0
243    1  0
244    0  1
245    1  0
246    1  0
247    0  1
248    1  0
249    1  0
...   .. ..
18234  1  0
18235  0  1
18236  0  1
18237  0  1
18238  0  1
18239  0  1
18240  0  1
18241  0  1
18242  1  0
18243  0  1
18244  0  1
18245  1  0
18246  0  1
18247  0  1
18248  0  1
18249  1  0
18250  0  1
18251  1  0
18252  1  0
18253  0  1
18254  1  0
18255  0  1
18256  1  0
18257  0  1
18258  1  0
18259  0  1
18260  0  1
18261  0  1
18262  0  1
18263  1  0
18264  1  0
18265  0  1
18266  0  1
18267  1  0
18268  1  0
18269  1  0
18270  1  0
18271  0  1
18272  1  0
18273  1  0
18274  0  1
18275  0  1
18276  1  0
18277  0  1
18278  0  1
18279  0  1
18280  0  1
18281  0  1
18282  1  0
18283  1  0
18284  0  1
18285  0  1
18286  0  1
18287  1  0
18288  1  0
18289  0  1
18290  0  1
18291  1  0
18292  0  1
18293  0  1
18294  0  1
18295  0  1
18296  0  1
18297  0  1
18298  0  1
18299  1  0
18300  0  1
18301  1  0
18302  0  1
18303  0  1
18304  1  0
18305  0  1
18306  0  1
18307  0  1
18308  0  1
18309  0  1
18310  0  1
18311  0  1
18312  0  1
18313  1  0
18314  1  0
18315  1  0
18316  0  1
18317  0  1
18318  1  0
18319  0  1
18320  1  0
18321  0  1
18322  0  1
18323  0  1
18324  1  0
18325  1  0
18326  0  1
18327  1  0
18328  1  0
18329  0  1
18330  1  0
18331  1  0
18332  0  1
18333  0  1
18334  0  1
18335  0  1
18336  0  1
18337  0  1
18338  1  0
18339  0  1
18340  0  1
18341  0  1
18342  1  0
18343  1  0
18344  0  1
18345  0  1
18346  0  1
18347  1  0
18348  1  0
18349  0  1
18350  0  1
18351  0  1
18352  0  1
18353  1  0
18354  0  1
18355  1  0
18356  1  0
18357  0  1
18358  1  0
18359  1  0
18360  0  1
18361  0  1
18362  0  1
18363  0  1
18364  1  0
18365  0  1
18366  0  1
18367  0  1
18368  0  1
18369  0  1
18370  0  1
18371  1  0
18372  1  0
18373  1  0
18374  1  0
18375  1  0
18376  0  1
18377  1  0
18378  1  0
18379  1  0
18380  1  0
18381  1  0
18382  1  0
18383  0  1
18384  1  0
18385  0  1
18386  0  1
18387  0  1
18388  1  0
18389  1  0
18390  0  1
18391  0  1
18392  1  0
18393  0  1
18394  0  1
18395  0  1
18396  1  0
18397  1  0
18398  0  1
18399  0  1
18400  1  0
18401  1  0
18402  0  1
18403  1  0
18404  0  1
18405  0  1
18406  1  0
18407  1  0
18408  1  0
18409  0  1
18410  0  1
18411  1  0
18412  1  0
18413  1  0
18414  0  1
18415  0  1
18416  0  1
18417  1  0
18418  0  1
18419  0  1
18420  1  0
18421  0  1
18422  0  1
18423  0  1
18424  1  0
18425  0  1
18426  0  1
18427  0  1
18428  1  0
18429  0  1
18430  0  1
18431  1  0
18432  1  0
18433  1  0
18434  1  0
18435  1  0
18436  0  1
18437  0  1
18438  1  0
18439  1  0
18440  0  1
18441  1  0
18442  0  1
18443  0  1
18444  1  0
18445  0  1
18446  0  1
18447  0  1
18448  0  1
18449  0  1
18450  0  1
18451  0  1
18452  0  1
18453  1  0
18454  1  0
18455  1  0
18456  0  1
18457  0  1
18458  0  1
18459  0  1
18460  1  0
18461  1  0
18462  0  1
18463  0  1
18464  0  1
18465  0  1
18466  1  0
18467  1  0
18468  1  0
18469  1  0
18470  0  1
18471  0  1
18472  1  0
18473  0  1
18474  1  0
18475  0  1
18476  1  0
18477  1  0
18478  0  1
18479  1  0
18480  0  1
18481  0  1
18482  1  0
18483  1  0

[18484 rows x 2 columns]

In [13]:
merged1=pd.concat([main_df,marital_dummies],axis='columns')
merged1

,MaritalStatus,Gender,EnglishEducation,EnglishOccupation,HouseOwnerFlagText,Region,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer,M,S
0,M,M,Bachelors,Professional,Yes,Pacific,90000,2,0,0,48,2,1,1,0
1,S,M,Bachelors,Professional,No,Pacific,60000,3,3,1,43,1,1,0,1
2,M,M,Bachelors,Professional,Yes,Pacific,60000,3,3,1,49,4,1,1,0
3,S,F,Bachelors,Professional,No,Pacific,70000,0,0,1,46,7,1,0,1
4,S,F,Bachelors,Professional,Yes,Pacific,80000,5,5,4,40,2,1,0,1
5,S,M,Bachelors,Professional,Yes,Pacific,70000,0,0,1,43,7,1,0,1
6,S,F,Bachelors,Professional,Yes,Pacific,70000,0,0,1,43,7,1,0,1
7,M,M,Bachelors,Professional,Yes,Pacific,60000,3,3,2,50,1,1,1,0
8,S,F,Bachelors,Professional,Yes,Pacific,60000,4,4,3,44,11,1,0,1
9,S,M,Bachelors,Professional,No,Pacific,70000,0,0,1,50,7,1,0,1
10,S,F,Bachelors,Professional,No,Pacific,70000,0,0,1,50,7,1,0,1
11,M,M,Bachelors,Professional,Yes,Pacific,60000,4,4,4,50,11,1,1,0
12,M,F,Bachelors,Management,Yes,North America,100000,2,0,2,41,2,0,1,0
13,M,M,Bachelors,Management,Yes,North America,100000,2,0,3,40,1,0,1,0
14,S,F,Bachelors,Management,No,North America,100000,3,0,3,46,2,0,0,1
15,S,F,Partial College,Skilled Manual,No,North America,30000,0,0,1,35,7,1,0,1
16,M,M,Partial College,Skilled Manual,Yes,North America,30000,0,0,1,35,7,1,1,0
17,S,F,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,70,7,1,0,1
18,S,M,Partial College,Clerical,Yes,Pacific,30000,2,0,2,64,7,1,0,1
19,S,M,High School,Skilled Manual,No,North America,40000,0,0,2,36,7,0,0,1
20,S,M,High School,Skilled Manual,No,North America,40000,0,0,2,35,2,1,0,1
21,S,F,Partial College,Skilled Manual,No,North America,40000,0,0,1,35,2,1,0,1
22,M,M,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,35,7,1,1,0
23,M,M,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,35,2,0,1,0
24,M,M,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,35,7,0,1,0
25,M,M,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,68,2,1,1,0
26,S,M,Partial College,Clerical,No,Pacific,30000,2,0,2,68,2,1,0,1
27,M,M,Partial College,Clerical,Yes,Pacific,30000,2,0,2,67,7,1,1,0
28,M,F,Partial College,Clerical,Yes,Pacific,30000,2,0,2,68,2,1,1,0
29,M,M,Partial College,Clerical,Yes,Pacific,30000,2,0,2,67,2,1,1,0
30,M,F,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,62,2,1,1,0
31,M,F,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,2,1,1,0
32,M,F,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,2,1,1,0
33,M,M,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,61,7,1,1,0
34,M,F,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,7,1,1,0
35,M,F,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,66,2,1,1,0
36,M,F,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,35,2,1,1,0
37,S,F,Partial High School,Clerical,No,North America,40000,0,0,2,36,7,1,0,1
38,M,F,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,66,7,1,1,0
39,M,M,Partial College,Clerical,Yes,Pacific,30000,3,0,2,65,7,1,1,0
40,M,M,Partial College,Skilled Manual,Yes,North America,30000,0,0,2,37,2,1,1,0
41,M,F,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,36,2,1,1,0
42,M,F,Partial College,Skilled Manual,Yes,North America,70000,0,0,2,37,1,1,1,0
43,M,M,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,38,7,0,1,0
44,M,M,Partial High School,Clerical,Yes,Pacific,20000,2,1,2,65,2,1,1,0
45,S,M,High School,Skilled Manual,No,Pacific,30000,3,0,2,64,2,0,0,1
46,M,F,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,64,7,1,1,0
47,M,F,High School,Skilled Manual,No,Pacific,30000,3,0,2,64,2,1,1,0
48,M,M,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,63,7,1,1,0
49,S,F,Partial High School,Clerical,Yes,North America,40000,0,0,2,34,7,0,0,1
50,M,M,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,62,7,1,1,0
51,S,M,High School,Skilled Manual,No,Pacific,30000,3,0,2,63,2,0,0,1
52,S,F,Partial College,Clerical,No,Pacific,40000,2,0,2,63,7,1,0,1
53,M,F,Partial College,Skilled Manual,No,North America,60000,0,0,2,34,2,1,1,0
54,M,F,Partial College,Skilled Manual,Yes,Pacific,40000,2,0,2,62,7,1,1,0
55,M,M,Partial College,Skilled Manual,Yes,Pacific,40000,2,0,2,62,7,1,1,0
56,M,F,Partial College,Skilled Manual,Yes,Pacific,40000,3,0,2,61,7,1,1,0
57,M,M,Graduate Degree,Management,Yes,Pacific,70000,2,0,2,49,2,1,1,0
58,M,M,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,54,2,1,1,0
59,S,F,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,60,7,0,0,1
60,M,M,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,60,7,1,1,0
61,M,M,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,44,7,1,1,0
62,M,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,1,1,0
63,S,F,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,1,0,1
64,M,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,1,0
65,M,F,Partial College,Skilled Manual,No,North America,60000,0,0,2,40,2,0,1,0
66,M,F,Partial College,Professional,Yes,North America,70000,0,0,2,40,7,0,1,0
67,S,M,Partial College,Professional,Yes,North America,60000,0,0,2,37,7,0,0,1
68,S,F,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,53,7,0,0,1
69,S,F,High School,Skilled Manual,No,Pacific,80000,2,0,2,53,2,1,0,1
70,M,M,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,59,7,1,1,0
71,S,F,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,59,7,0,0,1
72,S,F,High School,Skilled Manual,No,Pacific,80000,2,0,2,59,2,1,0,1
73,S,F,High School,Skilled Manual,Yes,Pacific,70000,2,0,2,58,7,0,0,1
74,S,M,High School,Skilled Manual,Yes,Pacific,70000,2,0,2,58,7,0,0,1
75,S,F,High School,Professional,Yes,Pacific,80000,2,0,2,56,7,1,0,1
76,S,M,High School,Professional,Yes,Pacific,80000,2,0,2,57,7,1,0,1
77,S,F,High School,Professional,No,Pacific,80000,2,0,2,56,2,1,0,1
78,S,F,High School,Professional,No,North America,40000,0,0,2,35,2,0,0,1
79,S,M,Graduate Degree,Management,Yes,Pacific,160000,0,0,2,49,1,0,0,1
80,M,M,Graduate Degree,Management,Yes,Pacific,170000,0,0,2,55,1,1,1,0
81,M,F,Bachelors,Management,Yes,North America,120000,2,2,3,48,4,0,1,0
82,S,F,Graduate Degree,Management,No,North America,130000,0,1,3,48,2,1,0,1
83,M,F,Graduate Degree,Management,Yes,North America,130000,0,1,3,42,2,1,1,0
84,S,M,Partial High School,Skilled Manual,No,North America,80000,2,0,2,56,2,1,0,1
85,S,F,High School,Professional,No,North America,60000,2,0,2,57,7,0,0,1
86,M,M,Partial College,Professional,Yes,North America,70000,2,1,0,56,1,0,1,0
87,M,F,Partial College,Professional,No,North America,70000,3,2,0,56,1,0,1,0
88,M,M,Bachelors,Management,Yes,North America,80000,2,1,0,56,4,1,1,0
89,S,F,Bachelors,Management,Yes,North America,80000,2,1,1,57,4,1,0,1
90,S,M,Partial College,Professional,Yes,North America,90000,2,0,1,51,4,1,0,1
91,M,M,Partial College,Professional,Yes,North America,90000,2,0,1,57,7,0,1,0
92,M,F,Bachelors,Professional,Yes,Pacific,90000,2,2,0,47,2,1,1,0
93,M,F,Graduate Degree,Management,Yes,Pacific,100000,0,0,0,41,1,1,1,0
94,S,M,Partial College,Skilled Manual,No,Pacific,70000,1,0,1,52,1,0,0,1
95,S,M,Partial College,Skilled Manual,Yes,Pacific,70000,1,0,1,52,7,1,0,1
96,M,M,Bachelors,Professional,Yes,Pacific,60000,1,0,1,52,7,1,1,0
97,M,M,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,47,7,1,1,0
98,S,F,Partial College,Skilled Manual,No,Pacific,60000,1,0,1,53,1,0,0,1
99,M,M,Bachelors,Professional,Yes,Pacific,60000,1,0,1,53,1,1,1,0
100,S,F,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,53,7,1,0,1
101,S,F,Bachelors,Professional,No,Pacific,70000,0,0,1,49,1,1,0,1
102,S,F,Bachelors,Professional,Yes,Pacific,80000,5,5,4,49,2,0,0,1
103,S,F,Bachelors,Professional,Yes,Pacific,70000,0,0,1,38,7,1,0,1
104,M,M,Bachelors,Professional,No,Pacific,70000,0,0,1,44,1,1,1,0
105,S,F,Bachelors,Professional,No,Pacific,70000,0,0,1,49,7,1,0,1
106,S,M,Bachelors,Professional,No,Pacific,70000,0,0,1,49,7,1,0,1
107,M,F,Bachelors,Professional,Yes,Pacific,90000,1,0,1,43,7,1,1,0
108,S,F,Bachelors,Professional,No,Pacific,70000,0,0,2,51,1,1,0,1
109,S,M,Bachelors,Professional,No,Pacific,70000,0,0,2,39,1,1,0,1
110,M,M,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,52,7,1,1,0
111,M,F,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,52,1,1,1,0
112,M,F,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,51,1,1,1,0
113,M,M,Bachelors,Professional,Yes,Pacific,70000,5,4,2,47,7,0,1,0
114,S,F,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,52,7,0,0,1
115,M,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,52,1,0,1,0
116,M,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,40,7,0,1,0
117,M,F,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,53,11,1,1,0
118,S,M,Partial College,Skilled Manual,No,Pacific,80000,1,0,1,57,1,0,0,1
119,S,M,Partial College,Clerical,No,Pacific,30000,2,0,2,79,1,0,0,1
120,S,F,Bachelors,Management,Yes,Pacific,40000,2,0,1,78,7,1,0,1
121,M,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,53,11,0,1,0
122,M,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,54,7,0,1,0
123,M,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,54,11,0,1,0
124,S,M,Partial College,Skilled Manual,Yes,Pacific,80000,1,0,1,51,7,1,0,1
125,S,F,Partial College,Skilled Manual,Yes,Pacific,70000,1,0,1,58,7,0,0,1
126,M,M,High School,Skilled Manual,No,Pacific,10000,2,1,2,65,1,1,1,0
127,M,F,High School,Skilled Manual,Yes,North America,40000,0,0,1,38,7,0,1,0
128,M,F,High School,Skilled Manual,Yes,North America,40000,0,0,1,38,7,0,1,0
129,S,F,High School,Skilled Manual,Yes,North America,40000,0,0,1,39,7,1,0,1
130,M,F,High School,Skilled Manual,Yes,North America,30000,0,0,2,34,7,0,1,0
131,M,F,High School,Skilled Manual,No,North America,30000,0,0,2,34,1,0,1,0
132,S,F,High School,Skilled Manual,No,North America,30000,0,0,2,33,7,1,0,1
133,S,F,Partial High School,Clerical,No,North America,30000,0,0,2,33,1,0,0,1
134,S,M,High School,Skilled Manual,Yes,Pacific,10000,5,0,2,63,7,1,0,1
135,S,M,Partial High School,Clerical,No,North America,30000,0,0,2,34,7,1,0,1
136,S,F,High School,Skilled Manual,No,North America,40000,0,0,2,35,1,1,0,1
137,M,F,High School,Skilled Manual,Yes,North America,40000,0,0,2,36,7,0,1,0
138,M,F,High School,Skilled Manual,No,North America,40000,0,0,2,35,1,0,1,0
139,S,F,Partial College,Clerical,No,Pacific,30000,2,0,2,70,7,0,0,1
140,S,M,Partial High School,Clerical,No,North America,30000,0,0,2,37,7,0,0,1
141,M,F,High School,Skilled Manual,No,North America,40000,0,0,2,37,1,0,1,0
142,S,M,High School,Skilled Manual,No,North America,40000,0,0,2,37,1,0,0,1
143,M,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,37,7,0,1,0
144,S,M,High School,Skilled Manual,No,North America,40000,0,0,2,34,1,1,0,1
145,S,F,High School,Skilled Manual,No,North America,40000,0,0,2,34,1,1,0,1
146,S,F,Bachelors,Management,Yes,Pacific,40000,2,0,2,75,7,0,0,1
147,M,M,Graduate Degree,Management,Yes,Pacific,60000,2,0,1,75,1,1,1,0
148,M,M,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,7,0,1,0
149,M,M,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,1,0,1,0
150,S,M,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,7,0,0,1
151,S,F,Graduate Degree,Management,No,Pacific,60000,2,0,1,72,1,1,0,1
152,S,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,0,1
153,M,F,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,0,1,0
154,S,F,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,38,7,1,0,1
155,S,M,Partial College,Skilled Manual,No,North America,40000,0,0,1,38,2,1,0,1
156,S,F,Partial College,Skilled Manual,No,North America,40000,0,0,1,38,2,1,0,1
157,M,F,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,0,1,0
158,S,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,0,1
159,S,F,High School,Skilled Manual,No,North America,40000,0,0,2,38,2,0,0,1
160,S,M,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,7,1,0,1
161,S,F,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,2,0,0,1
162,S,M,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,40,7,1,0,1
163,M,M,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,39,7,0,1,0
164,S,M,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,2,0,0,1
165,M,F,Partial College,Skilled Manual,No,North America,60000,0,0,1,41,2,0,1,0
166,S,F,Partial College,Skilled Manual,No,North America,70000,0,0,2,42,1,0,0,1
167,S,F,Bachelors,Management,No,North America,80000,0,0,1,42,1,1,0,1
168,S,M,Bachelors,Management,No,North America,80000,0,0,1,46,1,1,0,1
169,M,M,Bachelors,Management,Yes,North America,90000,4,4,1,46,1,0,1,0
170,M,F,Bachelors,Management,Yes,North America,90000,4,4,1,46,1,0,1,0
171,S,M,Bachelors,Management,Yes,North America,100000,1,0,2,41,2,1,0,1
172,M,F,Bachelors,Management,Yes,North America,100000,1,0,2,46,2,0,1,0
173,S,F,Graduate Degree,Management,No,North America,110000,0,0,4,47,1,0,0,1
174,M,M,Graduate Degree,Management,Yes,North America,110000,0,1,0,47,4,0,1,0
175,S,M,Partial College,Skilled Manual,Yes,North America,70000,0,0,2,51,7,1,0,1
176,M,M,Bachelors,Management,Yes,North America,90000,4,4,1,41,2,0,1,0
177,M,M,Graduate Degree,Management,Yes,North America,110000,2,4,2,72,7,0,1,0
178,M,M,Graduate Degree,Management,Yes,North America,100000,2,3,3,65,2,0,1,0
179,M,F,Graduate Degree,Management,Yes,North America,120000,2,4,3,60,7,0,1,0
180,M,F,Bachelors,Management,Yes,North America,160000,1,3,4,71,1,0,1,0
181,M,M,Graduate Degree,Management,Yes,North America,170000,2,3,2,60,1,0,1,0
182,S,F,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0,1
183,S,F,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0,1
184,S,F,Bachelors,Management,Yes,North America,70000,4,0,2,64,11,0,0,1
185,S,F,Bachelors,Management,Yes,North America,70000,4,0,2,69,11,0,0,1
186,S,F,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0,1
187,M,F,Graduate Degree,Management,Yes,North America,60000,4,0,2,70,11,0,1,0
188,M,F,Graduate Degree,Management,No,North America,60000,4,0,2,69,2,0,1,0
189,S,M,Graduate Degree,Management,Yes,North America,60000,4,0,2,70,11,1,0,1
190,M,M,Bachelors,Management,Yes,North America,70000,5,0,2,70,11,0,1,0
191,S,F,Bachelors,Management,Yes,North America,70000,5,0,3,68,11,1,0,1
192,M,M,Bachelors,Management,Yes,North America,60000,4,0,2,68,4,0,1,0
193,M,M,Bachelors,Management,Yes,North America,60000,4,0,2,69,4,0,1,0
194,M,F,Bachelors,Management,Yes,North America,60000,4,0,2,69,4,0,1,0
195,M,F,Bachelors,Management,Yes,North America,60000,5,0,3,68,11,0,1,0
196,M,M,Bachelors,Management,Yes,North America,60000,5,0,3,68,11,0,1,0
197,M,F,Bachelors,Management,No,North America,70000,3,1,1,68,2,0,1,0
198,S,F,Bachelors,Management,Yes,North America,70000,4,1,1,67,11,0,0,1
199,M,F,Bachelors,Management,Yes,North America,70000,4,1,1,62,11,0,1,0
200,M,M,Bachelors,Management,Yes,North America,70000,4,1,1,66,2,0,1,0
201,M,F,Bachelors,Management,Yes,North America,70000,4,1,1,67,11,0,1,0
202,M,F,Bachelors,Management,No,North America,80000,5,0,2,61,2,0,1,0
203,M,M,High School,Professional,Yes,North America,40000,2,1,2,60,11,0,1,0
204,M,F,High School,Professional,Yes,North America,40000,2,1,2,66,4,0,1,0
205,M,F,High School,Professional,Yes,North America,40000,2,1,2,66,11,0,1,0
206,M,M,Partial College,Professional,Yes,North America,60000,2,1,1,65,11,0,1,0
207,S,F,Partial College,Professional,Yes,North America,60000,2,1,1,66,11,0,0,1
208,M,F,Bachelors,Management,Yes,North America,60000,2,1,0,66,11,0,1,0
209,M,F,Bachelors,Management,Yes,North America,60000,2,1,0,66,11,0,1,0
210,M,M,Partial College,Professional,Yes,North America,70000,4,1,2,66,11,0,1,0
211,M,F,High School,Professional,Yes,North America,40000,2,1,2,59,4,0,1,0
212,M,F,High School,Professional,Yes,North America,40000,2,1,2,64,4,0,1,0
213,S,F,Partial College,Professional,Yes,North America,60000,2,1,2,65,11,0,0,1
214,S,M,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,0,0,1
215,M,F,Partial High School,Skilled Manual,Yes,North America,40000,2,1,2,58,11,0,1,0
216,S,F,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,1,0,1
217,S,F,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,1,0,1
218,S,F,Partial College,Professional,No,North America,60000,2,1,2,58,4,0,0,1
219,M,M,High School,Professional,Yes,North America,60000,2,1,2,63,11,0,1,0
220,M,F,Partial College,Professional,Yes,North America,60000,2,1,1,59,11,0,1,0
221,M,M,Partial College,Professional,Yes,North America,70000,4,2,1,64,2,0,1,0
222,M,F,Bachelors,Management,Yes,North America,80000,3,1,1,64,2,0,1,0
223,S,F,High School,Professional,Yes,North America,70000,2,1,2,62,4,0,0,1
224,S,F,High School,Professional,Yes,North America,70000,2,1,2,62,11,1,0,1
225,M,F,Partial College,Professional,Yes,North America,60000,2,1,1,58,11,0,1,0
226,M,F,Partial College,Professional,Yes,North America,60000,2,1,1,57,4,0,1,0
227,S,M,Partial College,Professional,Yes,North America,60000,2,1,2,57,11,1,0,1
228,M,F,Partial College,Professional,Yes,North America,60000,2,1,2,63,11,0,1,0
229,S,M,Partial College,Professional,Yes,North America,70000,4,2,1,62,11,0,0,1
230,M,F,Partial College,Professional,No,North America,70000,4,2,2,63,4,0,1,0
231,M,M,High School,Professional,Yes,North America,60000,2,1,2,56,11,0,1,0
232,M,F,High School,Professional,No,North America,60000,3,1,2,61,4,0,1,0
233,M,M,Partial College,Professional,Yes,North America,70000,4,2,2,56,11,0,1,0
234,S,F,Partial College,Professional,Yes,North America,70000,4,2,2,61,11,0,0,1
235,M,M,Partial College,Professional,Yes,North America,70000,4,2,2,62,11,0,1,0
236,S,M,Partial College,Professional,Yes,North America,70000,5,2,2,62,11,0,0,1
237,S,M,Bachelors,Management,No,Europe,130000,2,3,4,55,1,1,0,1
238,S,F,Bachelors,Management,No,Europe,130000,2,3,4,56,1,1,0,1
239,M,F,Partial College,Professional,No,Europe,130000,2,4,2,50,7,1,1,0
240,M,F,Partial College,Professional,Yes,Europe,160000,2,3,4,55,7,1,1,0
241,S,F,Partial College,Professional,Yes,Europe,100000,2,3,4,45,7,1,0,1
242,M,M,Partial College,Professional,Yes,Europe,110000,2,4,3,56,7,1,1,0
243,M,F,Partial College,Professional,Yes,Europe,150000,2,3,3,56,1,1,1,0
244,S,F,Bachelors,Management,No,Europe,170000,2,3,3,51,1,1,0,1
245,M,M,High School,Professional,No,Europe,120000,3,4,4,57,7,1,1,0
246,M,F,High School,Professional,No,Europe,120000,3,4,4,57,7,1,1,0
247,S,F,Partial College,Professional,No,Europe,130000,3,4,3,58,1,1,0,1
248,M,M,Partial College,Professional,Yes,Europe,110000,3,4,4,53,11,0,1,0
249,M,F,Partial College,Professional,Yes,Europe,130000,3,4,3,53,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,M,M,Bachelors,Management,Yes,North America,110000,5,3,1,50,7,0,1,0
18235,S,M,Partial College,Professional,No,North America,120000,4,3,2,50,2,0,0,1
18236,S,M,Partial College,Professional,Yes,North America,120000,4,3,3,51,7,1,0,1
18237,S,F,Partial College,Professional,Yes,North America,120000,4,3,3,51,7,1,0,1
18238,S,M,Partial College,Professional,No,North America,150000,4,1,3,51,2,1,0,1
18239,S,F,Partial College,Professional,No,North America,150000,4,1,4,51,2,1,0,1
18240,S,F,Partial College,Professional,No,North America,80000,5,4,3,52,1,0,0,1
18241,S,F,Partial College,Professional,No,North America,90000,5,4,4,46,2,0,0,1
18242,M,M,Partial College,Professional,Yes,North America,100000,3,2,4,51,7,1,1,0
18243,S,M,Bachelors,Management,Yes,North America,110000,1,3,1,51,7,0,0,1
18244,S,M,Bachelors,Management,Yes,North America,110000,1,3,2,52,7,0,0,1
18245,M,M,Bachelors,Management,Yes,North America,130000,1,2,4,51,1,0,1,0
18246,S,M,Bachelors,Management,No,North America,130000,1,2,4,52,4,0,0,1
18247,S,F,Partial College,Professional,Yes,North America,70000,5,4,3,42,7,1,0,1
18248,S,M,High School,Professional,Yes,North America,90000,4,3,2,53,7,0,0,1
18249,M,M,High School,Professional,Yes,North America,90000,4,3,2,53,7,0,1,0
18250,S,M,Partial College,Professional,No,North America,100000,3,2,4,47,2,0,0,1
18251,M,F,Bachelors,Management,Yes,North America,110000,1,3,3,53,7,0,1,0
18252,M,M,Bachelors,Management,Yes,North America,130000,1,3,3,52,1,1,1,0
18253,S,F,Bachelors,Management,No,North America,130000,3,3,3,53,4,0,0,1
18254,M,F,High School,Professional,Yes,North America,60000,2,0,2,58,7,1,1,0

In [14]:
merged1final=merged1.drop(['MaritalStatus','S'],axis='columns')
merged1final

,Gender,EnglishEducation,EnglishOccupation,HouseOwnerFlagText,Region,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer,M
0,M,Bachelors,Professional,Yes,Pacific,90000,2,0,0,48,2,1,1
1,M,Bachelors,Professional,No,Pacific,60000,3,3,1,43,1,1,0
2,M,Bachelors,Professional,Yes,Pacific,60000,3,3,1,49,4,1,1
3,F,Bachelors,Professional,No,Pacific,70000,0,0,1,46,7,1,0
4,F,Bachelors,Professional,Yes,Pacific,80000,5,5,4,40,2,1,0
5,M,Bachelors,Professional,Yes,Pacific,70000,0,0,1,43,7,1,0
6,F,Bachelors,Professional,Yes,Pacific,70000,0,0,1,43,7,1,0
7,M,Bachelors,Professional,Yes,Pacific,60000,3,3,2,50,1,1,1
8,F,Bachelors,Professional,Yes,Pacific,60000,4,4,3,44,11,1,0
9,M,Bachelors,Professional,No,Pacific,70000,0,0,1,50,7,1,0
10,F,Bachelors,Professional,No,Pacific,70000,0,0,1,50,7,1,0
11,M,Bachelors,Professional,Yes,Pacific,60000,4,4,4,50,11,1,1
12,F,Bachelors,Management,Yes,North America,100000,2,0,2,41,2,0,1
13,M,Bachelors,Management,Yes,North America,100000,2,0,3,40,1,0,1
14,F,Bachelors,Management,No,North America,100000,3,0,3,46,2,0,0
15,F,Partial College,Skilled Manual,No,North America,30000,0,0,1,35,7,1,0
16,M,Partial College,Skilled Manual,Yes,North America,30000,0,0,1,35,7,1,1
17,F,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,70,7,1,0
18,M,Partial College,Clerical,Yes,Pacific,30000,2,0,2,64,7,1,0
19,M,High School,Skilled Manual,No,North America,40000,0,0,2,36,7,0,0
20,M,High School,Skilled Manual,No,North America,40000,0,0,2,35,2,1,0
21,F,Partial College,Skilled Manual,No,North America,40000,0,0,1,35,2,1,0
22,M,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,35,7,1,1
23,M,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,35,2,0,1
24,M,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,35,7,0,1
25,M,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,68,2,1,1
26,M,Partial College,Clerical,No,Pacific,30000,2,0,2,68,2,1,0
27,M,Partial College,Clerical,Yes,Pacific,30000,2,0,2,67,7,1,1
28,F,Partial College,Clerical,Yes,Pacific,30000,2,0,2,68,2,1,1
29,M,Partial College,Clerical,Yes,Pacific,30000,2,0,2,67,2,1,1
30,F,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,62,2,1,1
31,F,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,2,1,1
32,F,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,2,1,1
33,M,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,61,7,1,1
34,F,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,7,1,1
35,F,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,66,2,1,1
36,F,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,35,2,1,1
37,F,Partial High School,Clerical,No,North America,40000,0,0,2,36,7,1,0
38,F,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,66,7,1,1
39,M,Partial College,Clerical,Yes,Pacific,30000,3,0,2,65,7,1,1
40,M,Partial College,Skilled Manual,Yes,North America,30000,0,0,2,37,2,1,1
41,F,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,36,2,1,1
42,F,Partial College,Skilled Manual,Yes,North America,70000,0,0,2,37,1,1,1
43,M,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,38,7,0,1
44,M,Partial High School,Clerical,Yes,Pacific,20000,2,1,2,65,2,1,1
45,M,High School,Skilled Manual,No,Pacific,30000,3,0,2,64,2,0,0
46,F,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,64,7,1,1
47,F,High School,Skilled Manual,No,Pacific,30000,3,0,2,64,2,1,1
48,M,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,63,7,1,1
49,F,Partial High School,Clerical,Yes,North America,40000,0,0,2,34,7,0,0
50,M,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,62,7,1,1
51,M,High School,Skilled Manual,No,Pacific,30000,3,0,2,63,2,0,0
52,F,Partial College,Clerical,No,Pacific,40000,2,0,2,63,7,1,0
53,F,Partial College,Skilled Manual,No,North America,60000,0,0,2,34,2,1,1
54,F,Partial College,Skilled Manual,Yes,Pacific,40000,2,0,2,62,7,1,1
55,M,Partial College,Skilled Manual,Yes,Pacific,40000,2,0,2,62,7,1,1
56,F,Partial College,Skilled Manual,Yes,Pacific,40000,3,0,2,61,7,1,1
57,M,Graduate Degree,Management,Yes,Pacific,70000,2,0,2,49,2,1,1
58,M,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,54,2,1,1
59,F,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,60,7,0,0
60,M,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,60,7,1,1
61,M,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,44,7,1,1
62,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,1,1
63,F,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,1,0
64,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,1
65,F,Partial College,Skilled Manual,No,North America,60000,0,0,2,40,2,0,1
66,F,Partial College,Professional,Yes,North America,70000,0,0,2,40,7,0,1
67,M,Partial College,Professional,Yes,North America,60000,0,0,2,37,7,0,0
68,F,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,53,7,0,0
69,F,High School,Skilled Manual,No,Pacific,80000,2,0,2,53,2,1,0
70,M,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,59,7,1,1
71,F,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,59,7,0,0
72,F,High School,Skilled Manual,No,Pacific,80000,2,0,2,59,2,1,0
73,F,High School,Skilled Manual,Yes,Pacific,70000,2,0,2,58,7,0,0
74,M,High School,Skilled Manual,Yes,Pacific,70000,2,0,2,58,7,0,0
75,F,High School,Professional,Yes,Pacific,80000,2,0,2,56,7,1,0
76,M,High School,Professional,Yes,Pacific,80000,2,0,2,57,7,1,0
77,F,High School,Professional,No,Pacific,80000,2,0,2,56,2,1,0
78,F,High School,Professional,No,North America,40000,0,0,2,35,2,0,0
79,M,Graduate Degree,Management,Yes,Pacific,160000,0,0,2,49,1,0,0
80,M,Graduate Degree,Management,Yes,Pacific,170000,0,0,2,55,1,1,1
81,F,Bachelors,Management,Yes,North America,120000,2,2,3,48,4,0,1
82,F,Graduate Degree,Management,No,North America,130000,0,1,3,48,2,1,0
83,F,Graduate Degree,Management,Yes,North America,130000,0,1,3,42,2,1,1
84,M,Partial High School,Skilled Manual,No,North America,80000,2,0,2,56,2,1,0
85,F,High School,Professional,No,North America,60000,2,0,2,57,7,0,0
86,M,Partial College,Professional,Yes,North America,70000,2,1,0,56,1,0,1
87,F,Partial College,Professional,No,North America,70000,3,2,0,56,1,0,1
88,M,Bachelors,Management,Yes,North America,80000,2,1,0,56,4,1,1
89,F,Bachelors,Management,Yes,North America,80000,2,1,1,57,4,1,0
90,M,Partial College,Professional,Yes,North America,90000,2,0,1,51,4,1,0
91,M,Partial College,Professional,Yes,North America,90000,2,0,1,57,7,0,1
92,F,Bachelors,Professional,Yes,Pacific,90000,2,2,0,47,2,1,1
93,F,Graduate Degree,Management,Yes,Pacific,100000,0,0,0,41,1,1,1
94,M,Partial College,Skilled Manual,No,Pacific,70000,1,0,1,52,1,0,0
95,M,Partial College,Skilled Manual,Yes,Pacific,70000,1,0,1,52,7,1,0
96,M,Bachelors,Professional,Yes,Pacific,60000,1,0,1,52,7,1,1
97,M,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,47,7,1,1
98,F,Partial College,Skilled Manual,No,Pacific,60000,1,0,1,53,1,0,0
99,M,Bachelors,Professional,Yes,Pacific,60000,1,0,1,53,1,1,1
100,F,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,53,7,1,0
101,F,Bachelors,Professional,No,Pacific,70000,0,0,1,49,1,1,0
102,F,Bachelors,Professional,Yes,Pacific,80000,5,5,4,49,2,0,0
103,F,Bachelors,Professional,Yes,Pacific,70000,0,0,1,38,7,1,0
104,M,Bachelors,Professional,No,Pacific,70000,0,0,1,44,1,1,1
105,F,Bachelors,Professional,No,Pacific,70000,0,0,1,49,7,1,0
106,M,Bachelors,Professional,No,Pacific,70000,0,0,1,49,7,1,0
107,F,Bachelors,Professional,Yes,Pacific,90000,1,0,1,43,7,1,1
108,F,Bachelors,Professional,No,Pacific,70000,0,0,2,51,1,1,0
109,M,Bachelors,Professional,No,Pacific,70000,0,0,2,39,1,1,0
110,M,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,52,7,1,1
111,F,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,52,1,1,1
112,F,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,51,1,1,1
113,M,Bachelors,Professional,Yes,Pacific,70000,5,4,2,47,7,0,1
114,F,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,52,7,0,0
115,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,52,1,0,1
116,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,40,7,0,1
117,F,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,53,11,1,1
118,M,Partial College,Skilled Manual,No,Pacific,80000,1,0,1,57,1,0,0
119,M,Partial College,Clerical,No,Pacific,30000,2,0,2,79,1,0,0
120,F,Bachelors,Management,Yes,Pacific,40000,2,0,1,78,7,1,0
121,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,53,11,0,1
122,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,54,7,0,1
123,M,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,54,11,0,1
124,M,Partial College,Skilled Manual,Yes,Pacific,80000,1,0,1,51,7,1,0
125,F,Partial College,Skilled Manual,Yes,Pacific,70000,1,0,1,58,7,0,0
126,M,High School,Skilled Manual,No,Pacific,10000,2,1,2,65,1,1,1
127,F,High School,Skilled Manual,Yes,North America,40000,0,0,1,38,7,0,1
128,F,High School,Skilled Manual,Yes,North America,40000,0,0,1,38,7,0,1
129,F,High School,Skilled Manual,Yes,North America,40000,0,0,1,39,7,1,0
130,F,High School,Skilled Manual,Yes,North America,30000,0,0,2,34,7,0,1
131,F,High School,Skilled Manual,No,North America,30000,0,0,2,34,1,0,1
132,F,High School,Skilled Manual,No,North America,30000,0,0,2,33,7,1,0
133,F,Partial High School,Clerical,No,North America,30000,0,0,2,33,1,0,0
134,M,High School,Skilled Manual,Yes,Pacific,10000,5,0,2,63,7,1,0
135,M,Partial High School,Clerical,No,North America,30000,0,0,2,34,7,1,0
136,F,High School,Skilled Manual,No,North America,40000,0,0,2,35,1,1,0
137,F,High School,Skilled Manual,Yes,North America,40000,0,0,2,36,7,0,1
138,F,High School,Skilled Manual,No,North America,40000,0,0,2,35,1,0,1
139,F,Partial College,Clerical,No,Pacific,30000,2,0,2,70,7,0,0
140,M,Partial High School,Clerical,No,North America,30000,0,0,2,37,7,0,0
141,F,High School,Skilled Manual,No,North America,40000,0,0,2,37,1,0,1
142,M,High School,Skilled Manual,No,North America,40000,0,0,2,37,1,0,0
143,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,37,7,0,1
144,M,High School,Skilled Manual,No,North America,40000,0,0,2,34,1,1,0
145,F,High School,Skilled Manual,No,North America,40000,0,0,2,34,1,1,0
146,F,Bachelors,Management,Yes,Pacific,40000,2,0,2,75,7,0,0
147,M,Graduate Degree,Management,Yes,Pacific,60000,2,0,1,75,1,1,1
148,M,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,7,0,1
149,M,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,1,0,1
150,M,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,7,0,0
151,F,Graduate Degree,Management,No,Pacific,60000,2,0,1,72,1,1,0
152,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,0
153,F,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,0,1
154,F,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,38,7,1,0
155,M,Partial College,Skilled Manual,No,North America,40000,0,0,1,38,2,1,0
156,F,Partial College,Skilled Manual,No,North America,40000,0,0,1,38,2,1,0
157,F,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,0,1
158,M,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,0
159,F,High School,Skilled Manual,No,North America,40000,0,0,2,38,2,0,0
160,M,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,7,1,0
161,F,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,2,0,0
162,M,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,40,7,1,0
163,M,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,39,7,0,1
164,M,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,2,0,0
165,F,Partial College,Skilled Manual,No,North America,60000,0,0,1,41,2,0,1
166,F,Partial College,Skilled Manual,No,North America,70000,0,0,2,42,1,0,0
167,F,Bachelors,Management,No,North America,80000,0,0,1,42,1,1,0
168,M,Bachelors,Management,No,North America,80000,0,0,1,46,1,1,0
169,M,Bachelors,Management,Yes,North America,90000,4,4,1,46,1,0,1
170,F,Bachelors,Management,Yes,North America,90000,4,4,1,46,1,0,1
171,M,Bachelors,Management,Yes,North America,100000,1,0,2,41,2,1,0
172,F,Bachelors,Management,Yes,North America,100000,1,0,2,46,2,0,1
173,F,Graduate Degree,Management,No,North America,110000,0,0,4,47,1,0,0
174,M,Graduate Degree,Management,Yes,North America,110000,0,1,0,47,4,0,1
175,M,Partial College,Skilled Manual,Yes,North America,70000,0,0,2,51,7,1,0
176,M,Bachelors,Management,Yes,North America,90000,4,4,1,41,2,0,1
177,M,Graduate Degree,Management,Yes,North America,110000,2,4,2,72,7,0,1
178,M,Graduate Degree,Management,Yes,North America,100000,2,3,3,65,2,0,1
179,F,Graduate Degree,Management,Yes,North America,120000,2,4,3,60,7,0,1
180,F,Bachelors,Management,Yes,North America,160000,1,3,4,71,1,0,1
181,M,Graduate Degree,Management,Yes,North America,170000,2,3,2,60,1,0,1
182,F,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0
183,F,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0
184,F,Bachelors,Management,Yes,North America,70000,4,0,2,64,11,0,0
185,F,Bachelors,Management,Yes,North America,70000,4,0,2,69,11,0,0
186,F,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0
187,F,Graduate Degree,Management,Yes,North America,60000,4,0,2,70,11,0,1
188,F,Graduate Degree,Management,No,North America,60000,4,0,2,69,2,0,1
189,M,Graduate Degree,Management,Yes,North America,60000,4,0,2,70,11,1,0
190,M,Bachelors,Management,Yes,North America,70000,5,0,2,70,11,0,1
191,F,Bachelors,Management,Yes,North America,70000,5,0,3,68,11,1,0
192,M,Bachelors,Management,Yes,North America,60000,4,0,2,68,4,0,1
193,M,Bachelors,Management,Yes,North America,60000,4,0,2,69,4,0,1
194,F,Bachelors,Management,Yes,North America,60000,4,0,2,69,4,0,1
195,F,Bachelors,Management,Yes,North America,60000,5,0,3,68,11,0,1
196,M,Bachelors,Management,Yes,North America,60000,5,0,3,68,11,0,1
197,F,Bachelors,Management,No,North America,70000,3,1,1,68,2,0,1
198,F,Bachelors,Management,Yes,North America,70000,4,1,1,67,11,0,0
199,F,Bachelors,Management,Yes,North America,70000,4,1,1,62,11,0,1
200,M,Bachelors,Management,Yes,North America,70000,4,1,1,66,2,0,1
201,F,Bachelors,Management,Yes,North America,70000,4,1,1,67,11,0,1
202,F,Bachelors,Management,No,North America,80000,5,0,2,61,2,0,1
203,M,High School,Professional,Yes,North America,40000,2,1,2,60,11,0,1
204,F,High School,Professional,Yes,North America,40000,2,1,2,66,4,0,1
205,F,High School,Professional,Yes,North America,40000,2,1,2,66,11,0,1
206,M,Partial College,Professional,Yes,North America,60000,2,1,1,65,11,0,1
207,F,Partial College,Professional,Yes,North America,60000,2,1,1,66,11,0,0
208,F,Bachelors,Management,Yes,North America,60000,2,1,0,66,11,0,1
209,F,Bachelors,Management,Yes,North America,60000,2,1,0,66,11,0,1
210,M,Partial College,Professional,Yes,North America,70000,4,1,2,66,11,0,1
211,F,High School,Professional,Yes,North America,40000,2,1,2,59,4,0,1
212,F,High School,Professional,Yes,North America,40000,2,1,2,64,4,0,1
213,F,Partial College,Professional,Yes,North America,60000,2,1,2,65,11,0,0
214,M,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,0,0
215,F,Partial High School,Skilled Manual,Yes,North America,40000,2,1,2,58,11,0,1
216,F,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,1,0
217,F,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,1,0
218,F,Partial College,Professional,No,North America,60000,2,1,2,58,4,0,0
219,M,High School,Professional,Yes,North America,60000,2,1,2,63,11,0,1
220,F,Partial College,Professional,Yes,North America,60000,2,1,1,59,11,0,1
221,M,Partial College,Professional,Yes,North America,70000,4,2,1,64,2,0,1
222,F,Bachelors,Management,Yes,North America,80000,3,1,1,64,2,0,1
223,F,High School,Professional,Yes,North America,70000,2,1,2,62,4,0,0
224,F,High School,Professional,Yes,North America,70000,2,1,2,62,11,1,0
225,F,Partial College,Professional,Yes,North America,60000,2,1,1,58,11,0,1
226,F,Partial College,Professional,Yes,North America,60000,2,1,1,57,4,0,1
227,M,Partial College,Professional,Yes,North America,60000,2,1,2,57,11,1,0
228,F,Partial College,Professional,Yes,North America,60000,2,1,2,63,11,0,1
229,M,Partial College,Professional,Yes,North America,70000,4,2,1,62,11,0,0
230,F,Partial College,Professional,No,North America,70000,4,2,2,63,4,0,1
231,M,High School,Professional,Yes,North America,60000,2,1,2,56,11,0,1
232,F,High School,Professional,No,North America,60000,3,1,2,61,4,0,1
233,M,Partial College,Professional,Yes,North America,70000,4,2,2,56,11,0,1
234,F,Partial College,Professional,Yes,North America,70000,4,2,2,61,11,0,0
235,M,Partial College,Professional,Yes,North America,70000,4,2,2,62,11,0,1
236,M,Partial College,Professional,Yes,North America,70000,5,2,2,62,11,0,0
237,M,Bachelors,Management,No,Europe,130000,2,3,4,55,1,1,0
238,F,Bachelors,Management,No,Europe,130000,2,3,4,56,1,1,0
239,F,Partial College,Professional,No,Europe,130000,2,4,2,50,7,1,1
240,F,Partial College,Professional,Yes,Europe,160000,2,3,4,55,7,1,1
241,F,Partial College,Professional,Yes,Europe,100000,2,3,4,45,7,1,0
242,M,Partial College,Professional,Yes,Europe,110000,2,4,3,56,7,1,1
243,F,Partial College,Professional,Yes,Europe,150000,2,3,3,56,1,1,1
244,F,Bachelors,Management,No,Europe,170000,2,3,3,51,1,1,0
245,M,High School,Professional,No,Europe,120000,3,4,4,57,7,1,1
246,F,High School,Professional,No,Europe,120000,3,4,4,57,7,1,1
247,F,Partial College,Professional,No,Europe,130000,3,4,3,58,1,1,0
248,M,Partial College,Professional,Yes,Europe,110000,3,4,4,53,11,0,1
249,F,Partial College,Professional,Yes,Europe,130000,3,4,3,53,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,M,Bachelors,Management,Yes,North America,110000,5,3,1,50,7,0,1
18235,M,Partial College,Professional,No,North America,120000,4,3,2,50,2,0,0
18236,M,Partial College,Professional,Yes,North America,120000,4,3,3,51,7,1,0
18237,F,Partial College,Professional,Yes,North America,120000,4,3,3,51,7,1,0
18238,M,Partial College,Professional,No,North America,150000,4,1,3,51,2,1,0
18239,F,Partial College,Professional,No,North America,150000,4,1,4,51,2,1,0
18240,F,Partial College,Professional,No,North America,80000,5,4,3,52,1,0,0
18241,F,Partial College,Professional,No,North America,90000,5,4,4,46,2,0,0
18242,M,Partial College,Professional,Yes,North America,100000,3,2,4,51,7,1,1
18243,M,Bachelors,Management,Yes,North America,110000,1,3,1,51,7,0,0
18244,M,Bachelors,Management,Yes,North America,110000,1,3,2,52,7,0,0
18245,M,Bachelors,Management,Yes,North America,130000,1,2,4,51,1,0,1
18246,M,Bachelors,Management,No,North America,130000,1,2,4,52,4,0,0
18247,F,Partial College,Professional,Yes,North America,70000,5,4,3,42,7,1,0
18248,M,High School,Professional,Yes,North America,90000,4,3,2,53,7,0,0
18249,M,High School,Professional,Yes,North America,90000,4,3,2,53,7,0,1
18250,M,Partial College,Professional,No,North America,100000,3,2,4,47,2,0,0
18251,F,Bachelors,Management,Yes,North America,110000,1,3,3,53,7,0,1
18252,M,Bachelors,Management,Yes,North America,130000,1,3,3,52,1,1,1
18253,F,Bachelors,Management,No,North America,130000,3,3,3,53,4,0,0
18254,F,High School,Professional,Yes,North America,60000,2,0,2,58,7,1,1
18255,M,Partial College,Professional,No,North America,80000,3,2,1,59,2,1,0
18256,M,High School,Professional,No,North America,90000,2,1,1,58,11,1,1
18257,M,High School,Professional,Yes,North America,90000,2,1,1,58,11,0,0
18258,F,High School,Professional,Yes,North America,90000,2,1,1,58,11,1,1
18259,M,Partial High School,Skilled Manual,Yes,North America,70000,2,0,2,59,7,0,0
18260,M,Graduate Degree,Management,No,North America,70000,4,0,2,79,2,0,0
18261,M,Graduate Degree,Management,No,North America,130000,2,3,3,79,1,1,0
18262,F,Graduate Degree,Management,No,North America,50000,2,0,2,78,2,0,0
18263,M,Graduate Degree,Management,No,North America,70000,4,0,2,78,2,0,1
18264,F,Bachelors,Management,No,North America,90000,4,0,2,78,2,1,1
18265,F,Bachelors,Management,No,North America,90000,4,0,2,77,2,1,0
18266,M,Partial College,Professional,No,North America,80000,5,4,3,54,2,0,0
18267,F,Partial College,Professional,Yes,North America,80000,5,4,3,48,7,0,1
18268,M,High School,Professional,Yes,North America,90000,4,3,3,54,7,0,1
18269,F,High School,Professional,Yes,North America,90000,4,3,3,54,7,0,1

In [16]:
gender_dummies=pd.get_dummies(main_df.Gender)
merged2=pd.concat([merged1final,gender_dummies],axis='columns')
mergedfinal2=merged2.drop(['Gender','F'],axis='columns')
mergedfinal2

,EnglishEducation,EnglishOccupation,HouseOwnerFlagText,Region,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer,M,M
0,Bachelors,Professional,Yes,Pacific,90000,2,0,0,48,2,1,1,1
1,Bachelors,Professional,No,Pacific,60000,3,3,1,43,1,1,0,1
2,Bachelors,Professional,Yes,Pacific,60000,3,3,1,49,4,1,1,1
3,Bachelors,Professional,No,Pacific,70000,0,0,1,46,7,1,0,0
4,Bachelors,Professional,Yes,Pacific,80000,5,5,4,40,2,1,0,0
5,Bachelors,Professional,Yes,Pacific,70000,0,0,1,43,7,1,0,1
6,Bachelors,Professional,Yes,Pacific,70000,0,0,1,43,7,1,0,0
7,Bachelors,Professional,Yes,Pacific,60000,3,3,2,50,1,1,1,1
8,Bachelors,Professional,Yes,Pacific,60000,4,4,3,44,11,1,0,0
9,Bachelors,Professional,No,Pacific,70000,0,0,1,50,7,1,0,1
10,Bachelors,Professional,No,Pacific,70000,0,0,1,50,7,1,0,0
11,Bachelors,Professional,Yes,Pacific,60000,4,4,4,50,11,1,1,1
12,Bachelors,Management,Yes,North America,100000,2,0,2,41,2,0,1,0
13,Bachelors,Management,Yes,North America,100000,2,0,3,40,1,0,1,1
14,Bachelors,Management,No,North America,100000,3,0,3,46,2,0,0,0
15,Partial College,Skilled Manual,No,North America,30000,0,0,1,35,7,1,0,0
16,Partial College,Skilled Manual,Yes,North America,30000,0,0,1,35,7,1,1,1
17,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,70,7,1,0,0
18,Partial College,Clerical,Yes,Pacific,30000,2,0,2,64,7,1,0,1
19,High School,Skilled Manual,No,North America,40000,0,0,2,36,7,0,0,1
20,High School,Skilled Manual,No,North America,40000,0,0,2,35,2,1,0,1
21,Partial College,Skilled Manual,No,North America,40000,0,0,1,35,2,1,0,0
22,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,35,7,1,1,1
23,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,35,2,0,1,1
24,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,35,7,0,1,1
25,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,68,2,1,1,1
26,Partial College,Clerical,No,Pacific,30000,2,0,2,68,2,1,0,1
27,Partial College,Clerical,Yes,Pacific,30000,2,0,2,67,7,1,1,1
28,Partial College,Clerical,Yes,Pacific,30000,2,0,2,68,2,1,1,0
29,Partial College,Clerical,Yes,Pacific,30000,2,0,2,67,2,1,1,1
30,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,62,2,1,1,0
31,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,2,1,1,0
32,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,2,1,1,0
33,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,61,7,1,1,1
34,High School,Skilled Manual,Yes,Pacific,20000,4,0,2,67,7,1,1,0
35,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,66,2,1,1,0
36,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,35,2,1,1,0
37,Partial High School,Clerical,No,North America,40000,0,0,2,36,7,1,0,0
38,Partial High School,Clerical,Yes,Pacific,10000,2,1,2,66,7,1,1,0
39,Partial College,Clerical,Yes,Pacific,30000,3,0,2,65,7,1,1,1
40,Partial College,Skilled Manual,Yes,North America,30000,0,0,2,37,2,1,1,1
41,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,36,2,1,1,0
42,Partial College,Skilled Manual,Yes,North America,70000,0,0,2,37,1,1,1,0
43,Partial College,Skilled Manual,Yes,North America,60000,0,0,2,38,7,0,1,1
44,Partial High School,Clerical,Yes,Pacific,20000,2,1,2,65,2,1,1,1
45,High School,Skilled Manual,No,Pacific,30000,3,0,2,64,2,0,0,1
46,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,64,7,1,1,0
47,High School,Skilled Manual,No,Pacific,30000,3,0,2,64,2,1,1,0
48,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,63,7,1,1,1
49,Partial High School,Clerical,Yes,North America,40000,0,0,2,34,7,0,0,0
50,High School,Skilled Manual,Yes,Pacific,30000,3,0,2,62,7,1,1,1
51,High School,Skilled Manual,No,Pacific,30000,3,0,2,63,2,0,0,1
52,Partial College,Clerical,No,Pacific,40000,2,0,2,63,7,1,0,0
53,Partial College,Skilled Manual,No,North America,60000,0,0,2,34,2,1,1,0
54,Partial College,Skilled Manual,Yes,Pacific,40000,2,0,2,62,7,1,1,0
55,Partial College,Skilled Manual,Yes,Pacific,40000,2,0,2,62,7,1,1,1
56,Partial College,Skilled Manual,Yes,Pacific,40000,3,0,2,61,7,1,1,0
57,Graduate Degree,Management,Yes,Pacific,70000,2,0,2,49,2,1,1,1
58,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,54,2,1,1,1
59,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,60,7,0,0,0
60,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,60,7,1,1,1
61,Partial College,Skilled Manual,Yes,Pacific,80000,2,0,2,44,7,1,1,1
62,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,1,1,1
63,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,1,0,0
64,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,1,1
65,Partial College,Skilled Manual,No,North America,60000,0,0,2,40,2,0,1,0
66,Partial College,Professional,Yes,North America,70000,0,0,2,40,7,0,1,0
67,Partial College,Professional,Yes,North America,60000,0,0,2,37,7,0,0,1
68,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,53,7,0,0,0
69,High School,Skilled Manual,No,Pacific,80000,2,0,2,53,2,1,0,0
70,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,59,7,1,1,1
71,High School,Skilled Manual,Yes,Pacific,80000,2,0,2,59,7,0,0,0
72,High School,Skilled Manual,No,Pacific,80000,2,0,2,59,2,1,0,0
73,High School,Skilled Manual,Yes,Pacific,70000,2,0,2,58,7,0,0,0
74,High School,Skilled Manual,Yes,Pacific,70000,2,0,2,58,7,0,0,1
75,High School,Professional,Yes,Pacific,80000,2,0,2,56,7,1,0,0
76,High School,Professional,Yes,Pacific,80000,2,0,2,57,7,1,0,1
77,High School,Professional,No,Pacific,80000,2,0,2,56,2,1,0,0
78,High School,Professional,No,North America,40000,0,0,2,35,2,0,0,0
79,Graduate Degree,Management,Yes,Pacific,160000,0,0,2,49,1,0,0,1
80,Graduate Degree,Management,Yes,Pacific,170000,0,0,2,55,1,1,1,1
81,Bachelors,Management,Yes,North America,120000,2,2,3,48,4,0,1,0
82,Graduate Degree,Management,No,North America,130000,0,1,3,48,2,1,0,0
83,Graduate Degree,Management,Yes,North America,130000,0,1,3,42,2,1,1,0
84,Partial High School,Skilled Manual,No,North America,80000,2,0,2,56,2,1,0,1
85,High School,Professional,No,North America,60000,2,0,2,57,7,0,0,0
86,Partial College,Professional,Yes,North America,70000,2,1,0,56,1,0,1,1
87,Partial College,Professional,No,North America,70000,3,2,0,56,1,0,1,0
88,Bachelors,Management,Yes,North America,80000,2,1,0,56,4,1,1,1
89,Bachelors,Management,Yes,North America,80000,2,1,1,57,4,1,0,0
90,Partial College,Professional,Yes,North America,90000,2,0,1,51,4,1,0,1
91,Partial College,Professional,Yes,North America,90000,2,0,1,57,7,0,1,1
92,Bachelors,Professional,Yes,Pacific,90000,2,2,0,47,2,1,1,0
93,Graduate Degree,Management,Yes,Pacific,100000,0,0,0,41,1,1,1,0
94,Partial College,Skilled Manual,No,Pacific,70000,1,0,1,52,1,0,0,1
95,Partial College,Skilled Manual,Yes,Pacific,70000,1,0,1,52,7,1,0,1
96,Bachelors,Professional,Yes,Pacific,60000,1,0,1,52,7,1,1,1
97,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,47,7,1,1,1
98,Partial College,Skilled Manual,No,Pacific,60000,1,0,1,53,1,0,0,0
99,Bachelors,Professional,Yes,Pacific,60000,1,0,1,53,1,1,1,1
100,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,53,7,1,0,0
101,Bachelors,Professional,No,Pacific,70000,0,0,1,49,1,1,0,0
102,Bachelors,Professional,Yes,Pacific,80000,5,5,4,49,2,0,0,0
103,Bachelors,Professional,Yes,Pacific,70000,0,0,1,38,7,1,0,0
104,Bachelors,Professional,No,Pacific,70000,0,0,1,44,1,1,1,1
105,Bachelors,Professional,No,Pacific,70000,0,0,1,49,7,1,0,0
106,Bachelors,Professional,No,Pacific,70000,0,0,1,49,7,1,0,1
107,Bachelors,Professional,Yes,Pacific,90000,1,0,1,43,7,1,1,0
108,Bachelors,Professional,No,Pacific,70000,0,0,2,51,1,1,0,0
109,Bachelors,Professional,No,Pacific,70000,0,0,2,39,1,1,0,1
110,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,52,7,1,1,1
111,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,52,1,1,1,0
112,Partial College,Skilled Manual,Yes,Pacific,60000,1,0,1,51,1,1,1,0
113,Bachelors,Professional,Yes,Pacific,70000,5,4,2,47,7,0,1,1
114,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,52,7,0,0,0
115,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,52,1,0,1,1
116,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,2,40,7,0,1,1
117,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,53,11,1,1,0
118,Partial College,Skilled Manual,No,Pacific,80000,1,0,1,57,1,0,0,1
119,Partial College,Clerical,No,Pacific,30000,2,0,2,79,1,0,0,1
120,Bachelors,Management,Yes,Pacific,40000,2,0,1,78,7,1,0,0
121,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,53,11,0,1,1
122,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,54,7,0,1,1
123,Partial College,Skilled Manual,Yes,Pacific,70000,5,4,3,54,11,0,1,1
124,Partial College,Skilled Manual,Yes,Pacific,80000,1,0,1,51,7,1,0,1
125,Partial College,Skilled Manual,Yes,Pacific,70000,1,0,1,58,7,0,0,0
126,High School,Skilled Manual,No,Pacific,10000,2,1,2,65,1,1,1,1
127,High School,Skilled Manual,Yes,North America,40000,0,0,1,38,7,0,1,0
128,High School,Skilled Manual,Yes,North America,40000,0,0,1,38,7,0,1,0
129,High School,Skilled Manual,Yes,North America,40000,0,0,1,39,7,1,0,0
130,High School,Skilled Manual,Yes,North America,30000,0,0,2,34,7,0,1,0
131,High School,Skilled Manual,No,North America,30000,0,0,2,34,1,0,1,0
132,High School,Skilled Manual,No,North America,30000,0,0,2,33,7,1,0,0
133,Partial High School,Clerical,No,North America,30000,0,0,2,33,1,0,0,0
134,High School,Skilled Manual,Yes,Pacific,10000,5,0,2,63,7,1,0,1
135,Partial High School,Clerical,No,North America,30000,0,0,2,34,7,1,0,1
136,High School,Skilled Manual,No,North America,40000,0,0,2,35,1,1,0,0
137,High School,Skilled Manual,Yes,North America,40000,0,0,2,36,7,0,1,0
138,High School,Skilled Manual,No,North America,40000,0,0,2,35,1,0,1,0
139,Partial College,Clerical,No,Pacific,30000,2,0,2,70,7,0,0,0
140,Partial High School,Clerical,No,North America,30000,0,0,2,37,7,0,0,1
141,High School,Skilled Manual,No,North America,40000,0,0,2,37,1,0,1,0
142,High School,Skilled Manual,No,North America,40000,0,0,2,37,1,0,0,1
143,High School,Skilled Manual,Yes,North America,40000,0,0,2,37,7,0,1,1
144,High School,Skilled Manual,No,North America,40000,0,0,2,34,1,1,0,1
145,High School,Skilled Manual,No,North America,40000,0,0,2,34,1,1,0,0
146,Bachelors,Management,Yes,Pacific,40000,2,0,2,75,7,0,0,0
147,Graduate Degree,Management,Yes,Pacific,60000,2,0,1,75,1,1,1,1
148,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,7,0,1,1
149,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,1,0,1,1
150,Bachelors,Management,Yes,Pacific,40000,2,0,2,73,7,0,0,1
151,Graduate Degree,Management,No,Pacific,60000,2,0,1,72,1,1,0,0
152,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,0,1
153,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,0,1,0
154,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,38,7,1,0,0
155,Partial College,Skilled Manual,No,North America,40000,0,0,1,38,2,1,0,1
156,Partial College,Skilled Manual,No,North America,40000,0,0,1,38,2,1,0,0
157,High School,Skilled Manual,Yes,North America,40000,0,0,2,39,7,0,1,0
158,High School,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,0,1
159,High School,Skilled Manual,No,North America,40000,0,0,2,38,2,0,0,0
160,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,7,1,0,1
161,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,2,0,0,0
162,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,40,7,1,0,1
163,Partial College,Skilled Manual,Yes,North America,40000,0,0,1,39,7,0,1,1
164,Partial College,Skilled Manual,No,North America,40000,0,0,1,40,2,0,0,1
165,Partial College,Skilled Manual,No,North America,60000,0,0,1,41,2,0,1,0
166,Partial College,Skilled Manual,No,North America,70000,0,0,2,42,1,0,0,0
167,Bachelors,Management,No,North America,80000,0,0,1,42,1,1,0,0
168,Bachelors,Management,No,North America,80000,0,0,1,46,1,1,0,1
169,Bachelors,Management,Yes,North America,90000,4,4,1,46,1,0,1,1
170,Bachelors,Management,Yes,North America,90000,4,4,1,46,1,0,1,0
171,Bachelors,Management,Yes,North America,100000,1,0,2,41,2,1,0,1
172,Bachelors,Management,Yes,North America,100000,1,0,2,46,2,0,1,0
173,Graduate Degree,Management,No,North America,110000,0,0,4,47,1,0,0,0
174,Graduate Degree,Management,Yes,North America,110000,0,1,0,47,4,0,1,1
175,Partial College,Skilled Manual,Yes,North America,70000,0,0,2,51,7,1,0,1
176,Bachelors,Management,Yes,North America,90000,4,4,1,41,2,0,1,1
177,Graduate Degree,Management,Yes,North America,110000,2,4,2,72,7,0,1,1
178,Graduate Degree,Management,Yes,North America,100000,2,3,3,65,2,0,1,1
179,Graduate Degree,Management,Yes,North America,120000,2,4,3,60,7,0,1,0
180,Bachelors,Management,Yes,North America,160000,1,3,4,71,1,0,1,0
181,Graduate Degree,Management,Yes,North America,170000,2,3,2,60,1,0,1,1
182,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0,0
183,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0,0
184,Bachelors,Management,Yes,North America,70000,4,0,2,64,11,0,0,0
185,Bachelors,Management,Yes,North America,70000,4,0,2,69,11,0,0,0
186,Bachelors,Management,Yes,North America,70000,4,0,2,70,11,0,0,0
187,Graduate Degree,Management,Yes,North America,60000,4,0,2,70,11,0,1,0
188,Graduate Degree,Management,No,North America,60000,4,0,2,69,2,0,1,0
189,Graduate Degree,Management,Yes,North America,60000,4,0,2,70,11,1,0,1
190,Bachelors,Management,Yes,North America,70000,5,0,2,70,11,0,1,1
191,Bachelors,Management,Yes,North America,70000,5,0,3,68,11,1,0,0
192,Bachelors,Management,Yes,North America,60000,4,0,2,68,4,0,1,1
193,Bachelors,Management,Yes,North America,60000,4,0,2,69,4,0,1,1
194,Bachelors,Management,Yes,North America,60000,4,0,2,69,4,0,1,0
195,Bachelors,Management,Yes,North America,60000,5,0,3,68,11,0,1,0
196,Bachelors,Management,Yes,North America,60000,5,0,3,68,11,0,1,1
197,Bachelors,Management,No,North America,70000,3,1,1,68,2,0,1,0
198,Bachelors,Management,Yes,North America,70000,4,1,1,67,11,0,0,0
199,Bachelors,Management,Yes,North America,70000,4,1,1,62,11,0,1,0
200,Bachelors,Management,Yes,North America,70000,4,1,1,66,2,0,1,1
201,Bachelors,Management,Yes,North America,70000,4,1,1,67,11,0,1,0
202,Bachelors,Management,No,North America,80000,5,0,2,61,2,0,1,0
203,High School,Professional,Yes,North America,40000,2,1,2,60,11,0,1,1
204,High School,Professional,Yes,North America,40000,2,1,2,66,4,0,1,0
205,High School,Professional,Yes,North America,40000,2,1,2,66,11,0,1,0
206,Partial College,Professional,Yes,North America,60000,2,1,1,65,11,0,1,1
207,Partial College,Professional,Yes,North America,60000,2,1,1,66,11,0,0,0
208,Bachelors,Management,Yes,North America,60000,2,1,0,66,11,0,1,0
209,Bachelors,Management,Yes,North America,60000,2,1,0,66,11,0,1,0
210,Partial College,Professional,Yes,North America,70000,4,1,2,66,11,0,1,1
211,High School,Professional,Yes,North America,40000,2,1,2,59,4,0,1,0
212,High School,Professional,Yes,North America,40000,2,1,2,64,4,0,1,0
213,Partial College,Professional,Yes,North America,60000,2,1,2,65,11,0,0,0
214,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,0,0,1
215,Partial High School,Skilled Manual,Yes,North America,40000,2,1,2,58,11,0,1,0
216,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,1,0,0
217,Partial College,Professional,Yes,North America,60000,2,1,2,64,11,1,0,0
218,Partial College,Professional,No,North America,60000,2,1,2,58,4,0,0,0
219,High School,Professional,Yes,North America,60000,2,1,2,63,11,0,1,1
220,Partial College,Professional,Yes,North America,60000,2,1,1,59,11,0,1,0
221,Partial College,Professional,Yes,North America,70000,4,2,1,64,2,0,1,1
222,Bachelors,Management,Yes,North America,80000,3,1,1,64,2,0,1,0
223,High School,Professional,Yes,North America,70000,2,1,2,62,4,0,0,0
224,High School,Professional,Yes,North America,70000,2,1,2,62,11,1,0,0
225,Partial College,Professional,Yes,North America,60000,2,1,1,58,11,0,1,0
226,Partial College,Professional,Yes,North America,60000,2,1,1,57,4,0,1,0
227,Partial College,Professional,Yes,North America,60000,2,1,2,57,11,1,0,1
228,Partial College,Professional,Yes,North America,60000,2,1,2,63,11,0,1,0
229,Partial College,Professional,Yes,North America,70000,4,2,1,62,11,0,0,1
230,Partial College,Professional,No,North America,70000,4,2,2,63,4,0,1,0
231,High School,Professional,Yes,North America,60000,2,1,2,56,11,0,1,1
232,High School,Professional,No,North America,60000,3,1,2,61,4,0,1,0
233,Partial College,Professional,Yes,North America,70000,4,2,2,56,11,0,1,1
234,Partial College,Professional,Yes,North America,70000,4,2,2,61,11,0,0,0
235,Partial College,Professional,Yes,North America,70000,4,2,2,62,11,0,1,1
236,Partial College,Professional,Yes,North America,70000,5,2,2,62,11,0,0,1
237,Bachelors,Management,No,Europe,130000,2,3,4,55,1,1,0,1
238,Bachelors,Management,No,Europe,130000,2,3,4,56,1,1,0,0
239,Partial College,Professional,No,Europe,130000,2,4,2,50,7,1,1,0
240,Partial College,Professional,Yes,Europe,160000,2,3,4,55,7,1,1,0
241,Partial College,Professional,Yes,Europe,100000,2,3,4,45,7,1,0,0
242,Partial College,Professional,Yes,Europe,110000,2,4,3,56,7,1,1,1
243,Partial College,Professional,Yes,Europe,150000,2,3,3,56,1,1,1,0
244,Bachelors,Management,No,Europe,170000,2,3,3,51,1,1,0,0
245,High School,Professional,No,Europe,120000,3,4,4,57,7,1,1,1
246,High School,Professional,No,Europe,120000,3,4,4,57,7,1,1,0
247,Partial College,Professional,No,Europe,130000,3,4,3,58,1,1,0,0
248,Partial College,Professional,Yes,Europe,110000,3,4,4,53,11,0,1,1
249,Partial College,Professional,Yes,Europe,130000,3,4,3,53,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,Bachelors,Management,Yes,North America,110000,5,3,1,50,7,0,1,1
18235,Partial College,Professional,No,North America,120000,4,3,2,50,2,0,0,1
18236,Partial College,Professional,Yes,North America,120000,4,3,3,51,7,1,0,1
18237,Partial College,Professional,Yes,North America,120000,4,3,3,51,7,1,0,0
18238,Partial College,Professional,No,North America,150000,4,1,3,51,2,1,0,1
18239,Partial College,Professional,No,North America,150000,4,1,4,51,2,1,0,0
18240,Partial College,Professional,No,North America,80000,5,4,3,52,1,0,0,0
18241,Partial College,Professional,No,North America,90000,5,4,4,46,2,0,0,0
18242,Partial College,Professional,Yes,North America,100000,3,2,4,51,7,1,1,1
18243,Bachelors,Management,Yes,North America,110000,1,3,1,51,7,0,0,1
18244,Bachelors,Management,Yes,North America,110000,1,3,2,52,7,0,0,1
18245,Bachelors,Management,Yes,North America,130000,1,2,4,51,1,0,1,1
18246,Bachelors,Management,No,North America,130000,1,2,4,52,4,0,0,1
18247,Partial College,Professional,Yes,North America,70000,5,4,3,42,7,1,0,0
18248,High School,Professional,Yes,North America,90000,4,3,2,53,7,0,0,1
18249,High School,Professional,Yes,North America,90000,4,3,2,53,7,0,1,1
18250,Partial College,Professional,No,North America,100000,3,2,4,47,2,0,0,1
18251,Bachelors,Management,Yes,North America,110000,1,3,3,53,7,0,1,0
18252,Bachelors,Management,Yes,North America,130000,1,3,3,52,1,1,1,1
18253,Bachelors,Management,No,North America,130000,3,3,3,53,4,0,0,0
18254,High School,Professional,Yes,North America,60000,2,0,2,58,7,1,1,0
18255,Partial College,Professional,No,North America,80000,3,2,1,59,2,1,0,1
18256,High School,Professional,No,North America,90000,2,1,1,58,11,1,1,1
18257,High School,Professional,Yes,North America,90000,2,1,1,58,11,0,0,1
18258,High School,Professional,Yes,North America,90000,2,1,1,58,11,1,1,0
18259,Partial High School,Skilled Manual,Yes,North America,70000,2,0,2,59,7,0,0,1
18260,Graduate Degree,Management,No,North America,70000,4,0,2,79,2,0,0,1
18261,Graduate Degree,Management,No,North America,130000,2,3,3,79,1,1,0,1
18262,Graduate Degree,Management,No,North America,50000,2,0,2,78,2,0,0,0
18263,Graduate Degree,Management,No,North America,70000,4,0,2,78,2,0,1,1
18264,Bachelors,Management,No,North America,90000,4,0,2,78,2,1,1,0
18265,Bachelors,Management,No,North America,90000,4,0,2,77,2,1,0,0
18266,Partial College,Professional,No,North America,80000,5,4,3,54,2,0,0,1
18267,Partial College,Professional,Yes,North America,80000,5,4,3,48,7,0,1,0
18268,High School,Professional,Yes,North America,90000,4,3,3,54,7,0,1,1
18269,High School,Professional,Yes,North America,90000,4,3,3,54,7,0,1,0

In [17]:
englisheducation_dummies=pd.get_dummies(main_df.EnglishEducation)
merged3=pd.concat([mergedfinal2,englisheducation_dummies],axis='columns')
mergedfinal3=merged3.drop(['EnglishEducation','Bachelors'],axis='columns')
mergedfinal3

,EnglishOccupation,HouseOwnerFlagText,Region,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer,M,M,Graduate Degree,High School,Partial College,Partial High School
0,Professional,Yes,Pacific,90000,2,0,0,48,2,1,1,1,0,0,0,0
1,Professional,No,Pacific,60000,3,3,1,43,1,1,0,1,0,0,0,0
2,Professional,Yes,Pacific,60000,3,3,1,49,4,1,1,1,0,0,0,0
3,Professional,No,Pacific,70000,0,0,1,46,7,1,0,0,0,0,0,0
4,Professional,Yes,Pacific,80000,5,5,4,40,2,1,0,0,0,0,0,0
5,Professional,Yes,Pacific,70000,0,0,1,43,7,1,0,1,0,0,0,0
6,Professional,Yes,Pacific,70000,0,0,1,43,7,1,0,0,0,0,0,0
7,Professional,Yes,Pacific,60000,3,3,2,50,1,1,1,1,0,0,0,0
8,Professional,Yes,Pacific,60000,4,4,3,44,11,1,0,0,0,0,0,0
9,Professional,No,Pacific,70000,0,0,1,50,7,1,0,1,0,0,0,0
10,Professional,No,Pacific,70000,0,0,1,50,7,1,0,0,0,0,0,0
11,Professional,Yes,Pacific,60000,4,4,4,50,11,1,1,1,0,0,0,0
12,Management,Yes,North America,100000,2,0,2,41,2,0,1,0,0,0,0,0
13,Management,Yes,North America,100000,2,0,3,40,1,0,1,1,0,0,0,0
14,Management,No,North America,100000,3,0,3,46,2,0,0,0,0,0,0,0
15,Skilled Manual,No,North America,30000,0,0,1,35,7,1,0,0,0,0,1,0
16,Skilled Manual,Yes,North America,30000,0,0,1,35,7,1,1,1,0,0,1,0
17,Skilled Manual,Yes,Pacific,20000,4,0,2,70,7,1,0,0,0,1,0,0
18,Clerical,Yes,Pacific,30000,2,0,2,64,7,1,0,1,0,0,1,0
19,Skilled Manual,No,North America,40000,0,0,2,36,7,0,0,1,0,1,0,0
20,Skilled Manual,No,North America,40000,0,0,2,35,2,1,0,1,0,1,0,0
21,Skilled Manual,No,North America,40000,0,0,1,35,2,1,0,0,0,0,1,0
22,Skilled Manual,Yes,North America,40000,0,0,1,35,7,1,1,1,0,0,1,0
23,Skilled Manual,Yes,North America,40000,0,0,1,35,2,0,1,1,0,0,1,0
24,Skilled Manual,Yes,North America,60000,0,0,2,35,7,0,1,1,0,0,1,0
25,Clerical,Yes,Pacific,10000,2,1,2,68,2,1,1,1,0,0,0,1
26,Clerical,No,Pacific,30000,2,0,2,68,2,1,0,1,0,0,1,0
27,Clerical,Yes,Pacific,30000,2,0,2,67,7,1,1,1,0,0,1,0
28,Clerical,Yes,Pacific,30000,2,0,2,68,2,1,1,0,0,0,1,0
29,Clerical,Yes,Pacific,30000,2,0,2,67,2,1,1,1,0,0,1,0
30,Clerical,Yes,Pacific,10000,2,1,2,62,2,1,1,0,0,0,0,1
31,Skilled Manual,Yes,Pacific,20000,4,0,2,67,2,1,1,0,0,1,0,0
32,Skilled Manual,Yes,Pacific,20000,4,0,2,67,2,1,1,0,0,1,0,0
33,Skilled Manual,Yes,Pacific,20000,4,0,2,61,7,1,1,1,0,1,0,0
34,Skilled Manual,Yes,Pacific,20000,4,0,2,67,7,1,1,0,0,1,0,0
35,Clerical,Yes,Pacific,10000,2,1,2,66,2,1,1,0,0,0,0,1
36,Skilled Manual,Yes,North America,60000,0,0,2,35,2,1,1,0,0,0,1,0
37,Clerical,No,North America,40000,0,0,2,36,7,1,0,0,0,0,0,1
38,Clerical,Yes,Pacific,10000,2,1,2,66,7,1,1,0,0,0,0,1
39,Clerical,Yes,Pacific,30000,3,0,2,65,7,1,1,1,0,0,1,0
40,Skilled Manual,Yes,North America,30000,0,0,2,37,2,1,1,1,0,0,1,0
41,Skilled Manual,Yes,North America,60000,0,0,2,36,2,1,1,0,0,0,1,0
42,Skilled Manual,Yes,North America,70000,0,0,2,37,1,1,1,0,0,0,1,0
43,Skilled Manual,Yes,North America,60000,0,0,2,38,7,0,1,1,0,0,1,0
44,Clerical,Yes,Pacific,20000,2,1,2,65,2,1,1,1,0,0,0,1
45,Skilled Manual,No,Pacific,30000,3,0,2,64,2,0,0,1,0,1,0,0
46,Skilled Manual,Yes,Pacific,30000,3,0,2,64,7,1,1,0,0,1,0,0
47,Skilled Manual,No,Pacific,30000,3,0,2,64,2,1,1,0,0,1,0,0
48,Skilled Manual,Yes,Pacific,30000,3,0,2,63,7,1,1,1,0,1,0,0
49,Clerical,Yes,North America,40000,0,0,2,34,7,0,0,0,0,0,0,1
50,Skilled Manual,Yes,Pacific,30000,3,0,2,62,7,1,1,1,0,1,0,0
51,Skilled Manual,No,Pacific,30000,3,0,2,63,2,0,0,1,0,1,0,0
52,Clerical,No,Pacific,40000,2,0,2,63,7,1,0,0,0,0,1,0
53,Skilled Manual,No,North America,60000,0,0,2,34,2,1,1,0,0,0,1,0
54,Skilled Manual,Yes,Pacific,40000,2,0,2,62,7,1,1,0,0,0,1,0
55,Skilled Manual,Yes,Pacific,40000,2,0,2,62,7,1,1,1,0,0,1,0
56,Skilled Manual,Yes,Pacific,40000,3,0,2,61,7,1,1,0,0,0,1,0
57,Management,Yes,Pacific,70000,2,0,2,49,2,1,1,1,1,0,0,0
58,Skilled Manual,Yes,Pacific,80000,2,0,2,54,2,1,1,1,0,0,1,0
59,Skilled Manual,Yes,Pacific,80000,2,0,2,60,7,0,0,0,0,0,1,0
60,Skilled Manual,Yes,Pacific,80000,2,0,2,60,7,1,1,1,0,0,1,0
61,Skilled Manual,Yes,Pacific,80000,2,0,2,44,7,1,1,1,0,0,1,0
62,Skilled Manual,Yes,North America,40000,0,0,2,39,7,1,1,1,0,1,0,0
63,Skilled Manual,Yes,North America,40000,0,0,2,39,7,1,0,0,0,1,0,0
64,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,1,1,0,1,0,0
65,Skilled Manual,No,North America,60000,0,0,2,40,2,0,1,0,0,0,1,0
66,Professional,Yes,North America,70000,0,0,2,40,7,0,1,0,0,0,1,0
67,Professional,Yes,North America,60000,0,0,2,37,7,0,0,1,0,0,1,0
68,Skilled Manual,Yes,Pacific,80000,2,0,2,53,7,0,0,0,0,1,0,0
69,Skilled Manual,No,Pacific,80000,2,0,2,53,2,1,0,0,0,1,0,0
70,Skilled Manual,Yes,Pacific,80000,2,0,2,59,7,1,1,1,0,1,0,0
71,Skilled Manual,Yes,Pacific,80000,2,0,2,59,7,0,0,0,0,1,0,0
72,Skilled Manual,No,Pacific,80000,2,0,2,59,2,1,0,0,0,1,0,0
73,Skilled Manual,Yes,Pacific,70000,2,0,2,58,7,0,0,0,0,1,0,0
74,Skilled Manual,Yes,Pacific,70000,2,0,2,58,7,0,0,1,0,1,0,0
75,Professional,Yes,Pacific,80000,2,0,2,56,7,1,0,0,0,1,0,0
76,Professional,Yes,Pacific,80000,2,0,2,57,7,1,0,1,0,1,0,0
77,Professional,No,Pacific,80000,2,0,2,56,2,1,0,0,0,1,0,0
78,Professional,No,North America,40000,0,0,2,35,2,0,0,0,0,1,0,0
79,Management,Yes,Pacific,160000,0,0,2,49,1,0,0,1,1,0,0,0
80,Management,Yes,Pacific,170000,0,0,2,55,1,1,1,1,1,0,0,0
81,Management,Yes,North America,120000,2,2,3,48,4,0,1,0,0,0,0,0
82,Management,No,North America,130000,0,1,3,48,2,1,0,0,1,0,0,0
83,Management,Yes,North America,130000,0,1,3,42,2,1,1,0,1,0,0,0
84,Skilled Manual,No,North America,80000,2,0,2,56,2,1,0,1,0,0,0,1
85,Professional,No,North America,60000,2,0,2,57,7,0,0,0,0,1,0,0
86,Professional,Yes,North America,70000,2,1,0,56,1,0,1,1,0,0,1,0
87,Professional,No,North America,70000,3,2,0,56,1,0,1,0,0,0,1,0
88,Management,Yes,North America,80000,2,1,0,56,4,1,1,1,0,0,0,0
89,Management,Yes,North America,80000,2,1,1,57,4,1,0,0,0,0,0,0
90,Professional,Yes,North America,90000,2,0,1,51,4,1,0,1,0,0,1,0
91,Professional,Yes,North America,90000,2,0,1,57,7,0,1,1,0,0,1,0
92,Professional,Yes,Pacific,90000,2,2,0,47,2,1,1,0,0,0,0,0
93,Management,Yes,Pacific,100000,0,0,0,41,1,1,1,0,1,0,0,0
94,Skilled Manual,No,Pacific,70000,1,0,1,52,1,0,0,1,0,0,1,0
95,Skilled Manual,Yes,Pacific,70000,1,0,1,52,7,1,0,1,0,0,1,0
96,Professional,Yes,Pacific,60000,1,0,1,52,7,1,1,1,0,0,0,0
97,Skilled Manual,Yes,Pacific,60000,1,0,1,47,7,1,1,1,0,0,1,0
98,Skilled Manual,No,Pacific,60000,1,0,1,53,1,0,0,0,0,0,1,0
99,Professional,Yes,Pacific,60000,1,0,1,53,1,1,1,1,0,0,0,0
100,Skilled Manual,Yes,Pacific,60000,1,0,1,53,7,1,0,0,0,0,1,0
101,Professional,No,Pacific,70000,0,0,1,49,1,1,0,0,0,0,0,0
102,Professional,Yes,Pacific,80000,5,5,4,49,2,0,0,0,0,0,0,0
103,Professional,Yes,Pacific,70000,0,0,1,38,7,1,0,0,0,0,0,0
104,Professional,No,Pacific,70000,0,0,1,44,1,1,1,1,0,0,0,0
105,Professional,No,Pacific,70000,0,0,1,49,7,1,0,0,0,0,0,0
106,Professional,No,Pacific,70000,0,0,1,49,7,1,0,1,0,0,0,0
107,Professional,Yes,Pacific,90000,1,0,1,43,7,1,1,0,0,0,0,0
108,Professional,No,Pacific,70000,0,0,2,51,1,1,0,0,0,0,0,0
109,Professional,No,Pacific,70000,0,0,2,39,1,1,0,1,0,0,0,0
110,Skilled Manual,Yes,Pacific,60000,1,0,1,52,7,1,1,1,0,0,1,0
111,Skilled Manual,Yes,Pacific,60000,1,0,1,52,1,1,1,0,0,0,1,0
112,Skilled Manual,Yes,Pacific,60000,1,0,1,51,1,1,1,0,0,0,1,0
113,Professional,Yes,Pacific,70000,5,4,2,47,7,0,1,1,0,0,0,0
114,Skilled Manual,Yes,Pacific,70000,5,4,2,52,7,0,0,0,0,0,1,0
115,Skilled Manual,Yes,Pacific,70000,5,4,2,52,1,0,1,1,0,0,1,0
116,Skilled Manual,Yes,Pacific,70000,5,4,2,40,7,0,1,1,0,0,1,0
117,Skilled Manual,Yes,Pacific,70000,5,4,3,53,11,1,1,0,0,0,1,0
118,Skilled Manual,No,Pacific,80000,1,0,1,57,1,0,0,1,0,0,1,0
119,Clerical,No,Pacific,30000,2,0,2,79,1,0,0,1,0,0,1,0
120,Management,Yes,Pacific,40000,2,0,1,78,7,1,0,0,0,0,0,0
121,Skilled Manual,Yes,Pacific,70000,5,4,3,53,11,0,1,1,0,0,1,0
122,Skilled Manual,Yes,Pacific,70000,5,4,3,54,7,0,1,1,0,0,1,0
123,Skilled Manual,Yes,Pacific,70000,5,4,3,54,11,0,1,1,0,0,1,0
124,Skilled Manual,Yes,Pacific,80000,1,0,1,51,7,1,0,1,0,0,1,0
125,Skilled Manual,Yes,Pacific,70000,1,0,1,58,7,0,0,0,0,0,1,0
126,Skilled Manual,No,Pacific,10000,2,1,2,65,1,1,1,1,0,1,0,0
127,Skilled Manual,Yes,North America,40000,0,0,1,38,7,0,1,0,0,1,0,0
128,Skilled Manual,Yes,North America,40000,0,0,1,38,7,0,1,0,0,1,0,0
129,Skilled Manual,Yes,North America,40000,0,0,1,39,7,1,0,0,0,1,0,0
130,Skilled Manual,Yes,North America,30000,0,0,2,34,7,0,1,0,0,1,0,0
131,Skilled Manual,No,North America,30000,0,0,2,34,1,0,1,0,0,1,0,0
132,Skilled Manual,No,North America,30000,0,0,2,33,7,1,0,0,0,1,0,0
133,Clerical,No,North America,30000,0,0,2,33,1,0,0,0,0,0,0,1
134,Skilled Manual,Yes,Pacific,10000,5,0,2,63,7,1,0,1,0,1,0,0
135,Clerical,No,North America,30000,0,0,2,34,7,1,0,1,0,0,0,1
136,Skilled Manual,No,North America,40000,0,0,2,35,1,1,0,0,0,1,0,0
137,Skilled Manual,Yes,North America,40000,0,0,2,36,7,0,1,0,0,1,0,0
138,Skilled Manual,No,North America,40000,0,0,2,35,1,0,1,0,0,1,0,0
139,Clerical,No,Pacific,30000,2,0,2,70,7,0,0,0,0,0,1,0
140,Clerical,No,North America,30000,0,0,2,37,7,0,0,1,0,0,0,1
141,Skilled Manual,No,North America,40000,0,0,2,37,1,0,1,0,0,1,0,0
142,Skilled Manual,No,North America,40000,0,0,2,37,1,0,0,1,0,1,0,0
143,Skilled Manual,Yes,North America,40000,0,0,2,37,7,0,1,1,0,1,0,0
144,Skilled Manual,No,North America,40000,0,0,2,34,1,1,0,1,0,1,0,0
145,Skilled Manual,No,North America,40000,0,0,2,34,1,1,0,0,0,1,0,0
146,Management,Yes,Pacific,40000,2,0,2,75,7,0,0,0,0,0,0,0
147,Management,Yes,Pacific,60000,2,0,1,75,1,1,1,1,1,0,0,0
148,Management,Yes,Pacific,40000,2,0,2,73,7,0,1,1,0,0,0,0
149,Management,Yes,Pacific,40000,2,0,2,73,1,0,1,1,0,0,0,0
150,Management,Yes,Pacific,40000,2,0,2,73,7,0,0,1,0,0,0,0
151,Management,No,Pacific,60000,2,0,1,72,1,1,0,0,1,0,0,0
152,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,0,1,0,1,0,0
153,Skilled Manual,Yes,North America,40000,0,0,2,38,7,0,1,0,0,1,0,0
154,Skilled Manual,Yes,North America,40000,0,0,1,38,7,1,0,0,0,0,1,0
155,Skilled Manual,No,North America,40000,0,0,1,38,2,1,0,1,0,0,1,0
156,Skilled Manual,No,North America,40000,0,0,1,38,2,1,0,0,0,0,1,0
157,Skilled Manual,Yes,North America,40000,0,0,2,39,7,0,1,0,0,1,0,0
158,Skilled Manual,Yes,North America,40000,0,0,2,38,7,1,0,1,0,1,0,0
159,Skilled Manual,No,North America,40000,0,0,2,38,2,0,0,0,0,1,0,0
160,Skilled Manual,No,North America,40000,0,0,1,40,7,1,0,1,0,0,1,0
161,Skilled Manual,No,North America,40000,0,0,1,40,2,0,0,0,0,0,1,0
162,Skilled Manual,Yes,North America,40000,0,0,1,40,7,1,0,1,0,0,1,0
163,Skilled Manual,Yes,North America,40000,0,0,1,39,7,0,1,1,0,0,1,0
164,Skilled Manual,No,North America,40000,0,0,1,40,2,0,0,1,0,0,1,0
165,Skilled Manual,No,North America,60000,0,0,1,41,2,0,1,0,0,0,1,0
166,Skilled Manual,No,North America,70000,0,0,2,42,1,0,0,0,0,0,1,0
167,Management,No,North America,80000,0,0,1,42,1,1,0,0,0,0,0,0
168,Management,No,North America,80000,0,0,1,46,1,1,0,1,0,0,0,0
169,Management,Yes,North America,90000,4,4,1,46,1,0,1,1,0,0,0,0
170,Management,Yes,North America,90000,4,4,1,46,1,0,1,0,0,0,0,0
171,Management,Yes,North America,100000,1,0,2,41,2,1,0,1,0,0,0,0
172,Management,Yes,North America,100000,1,0,2,46,2,0,1,0,0,0,0,0
173,Management,No,North America,110000,0,0,4,47,1,0,0,0,1,0,0,0
174,Management,Yes,North America,110000,0,1,0,47,4,0,1,1,1,0,0,0
175,Skilled Manual,Yes,North America,70000,0,0,2,51,7,1,0,1,0,0,1,0
176,Management,Yes,North America,90000,4,4,1,41,2,0,1,1,0,0,0,0
177,Management,Yes,North America,110000,2,4,2,72,7,0,1,1,1,0,0,0
178,Management,Yes,North America,100000,2,3,3,65,2,0,1,1,1,0,0,0
179,Management,Yes,North America,120000,2,4,3,60,7,0,1,0,1,0,0,0
180,Management,Yes,North America,160000,1,3,4,71,1,0,1,0,0,0,0,0
181,Management,Yes,North America,170000,2,3,2,60,1,0,1,1,1,0,0,0
182,Management,Yes,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0
183,Management,Yes,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0
184,Management,Yes,North America,70000,4,0,2,64,11,0,0,0,0,0,0,0
185,Management,Yes,North America,70000,4,0,2,69,11,0,0,0,0,0,0,0
186,Management,Yes,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0
187,Management,Yes,North America,60000,4,0,2,70,11,0,1,0,1,0,0,0
188,Management,No,North America,60000,4,0,2,69,2,0,1,0,1,0,0,0
189,Management,Yes,North America,60000,4,0,2,70,11,1,0,1,1,0,0,0
190,Management,Yes,North America,70000,5,0,2,70,11,0,1,1,0,0,0,0
191,Management,Yes,North America,70000,5,0,3,68,11,1,0,0,0,0,0,0
192,Management,Yes,North America,60000,4,0,2,68,4,0,1,1,0,0,0,0
193,Management,Yes,North America,60000,4,0,2,69,4,0,1,1,0,0,0,0
194,Management,Yes,North America,60000,4,0,2,69,4,0,1,0,0,0,0,0
195,Management,Yes,North America,60000,5,0,3,68,11,0,1,0,0,0,0,0
196,Management,Yes,North America,60000,5,0,3,68,11,0,1,1,0,0,0,0
197,Management,No,North America,70000,3,1,1,68,2,0,1,0,0,0,0,0
198,Management,Yes,North America,70000,4,1,1,67,11,0,0,0,0,0,0,0
199,Management,Yes,North America,70000,4,1,1,62,11,0,1,0,0,0,0,0
200,Management,Yes,North America,70000,4,1,1,66,2,0,1,1,0,0,0,0
201,Management,Yes,North America,70000,4,1,1,67,11,0,1,0,0,0,0,0
202,Management,No,North America,80000,5,0,2,61,2,0,1,0,0,0,0,0
203,Professional,Yes,North America,40000,2,1,2,60,11,0,1,1,0,1,0,0
204,Professional,Yes,North America,40000,2,1,2,66,4,0,1,0,0,1,0,0
205,Professional,Yes,North America,40000,2,1,2,66,11,0,1,0,0,1,0,0
206,Professional,Yes,North America,60000,2,1,1,65,11,0,1,1,0,0,1,0
207,Professional,Yes,North America,60000,2,1,1,66,11,0,0,0,0,0,1,0
208,Management,Yes,North America,60000,2,1,0,66,11,0,1,0,0,0,0,0
209,Management,Yes,North America,60000,2,1,0,66,11,0,1,0,0,0,0,0
210,Professional,Yes,North America,70000,4,1,2,66,11,0,1,1,0,0,1,0
211,Professional,Yes,North America,40000,2,1,2,59,4,0,1,0,0,1,0,0
212,Professional,Yes,North America,40000,2,1,2,64,4,0,1,0,0,1,0,0
213,Professional,Yes,North America,60000,2,1,2,65,11,0,0,0,0,0,1,0
214,Professional,Yes,North America,60000,2,1,2,64,11,0,0,1,0,0,1,0
215,Skilled Manual,Yes,North America,40000,2,1,2,58,11,0,1,0,0,0,0,1
216,Professional,Yes,North America,60000,2,1,2,64,11,1,0,0,0,0,1,0
217,Professional,Yes,North America,60000,2,1,2,64,11,1,0,0,0,0,1,0
218,Professional,No,North America,60000,2,1,2,58,4,0,0,0,0,0,1,0
219,Professional,Yes,North America,60000,2,1,2,63,11,0,1,1,0,1,0,0
220,Professional,Yes,North America,60000,2,1,1,59,11,0,1,0,0,0,1,0
221,Professional,Yes,North America,70000,4,2,1,64,2,0,1,1,0,0,1,0
222,Management,Yes,North America,80000,3,1,1,64,2,0,1,0,0,0,0,0
223,Professional,Yes,North America,70000,2,1,2,62,4,0,0,0,0,1,0,0
224,Professional,Yes,North America,70000,2,1,2,62,11,1,0,0,0,1,0,0
225,Professional,Yes,North America,60000,2,1,1,58,11,0,1,0,0,0,1,0
226,Professional,Yes,North America,60000,2,1,1,57,4,0,1,0,0,0,1,0
227,Professional,Yes,North America,60000,2,1,2,57,11,1,0,1,0,0,1,0
228,Professional,Yes,North America,60000,2,1,2,63,11,0,1,0,0,0,1,0
229,Professional,Yes,North America,70000,4,2,1,62,11,0,0,1,0,0,1,0
230,Professional,No,North America,70000,4,2,2,63,4,0,1,0,0,0,1,0
231,Professional,Yes,North America,60000,2,1,2,56,11,0,1,1,0,1,0,0
232,Professional,No,North America,60000,3,1,2,61,4,0,1,0,0,1,0,0
233,Professional,Yes,North America,70000,4,2,2,56,11,0,1,1,0,0,1,0
234,Professional,Yes,North America,70000,4,2,2,61,11,0,0,0,0,0,1,0
235,Professional,Yes,North America,70000,4,2,2,62,11,0,1,1,0,0,1,0
236,Professional,Yes,North America,70000,5,2,2,62,11,0,0,1,0,0,1,0
237,Management,No,Europe,130000,2,3,4,55,1,1,0,1,0,0,0,0
238,Management,No,Europe,130000,2,3,4,56,1,1,0,0,0,0,0,0
239,Professional,No,Europe,130000,2,4,2,50,7,1,1,0,0,0,1,0
240,Professional,Yes,Europe,160000,2,3,4,55,7,1,1,0,0,0,1,0
241,Professional,Yes,Europe,100000,2,3,4,45,7,1,0,0,0,0,1,0
242,Professional,Yes,Europe,110000,2,4,3,56,7,1,1,1,0,0,1,0
243,Professional,Yes,Europe,150000,2,3,3,56,1,1,1,0,0,0,1,0
244,Management,No,Europe,170000,2,3,3,51,1,1,0,0,0,0,0,0
245,Professional,No,Europe,120000,3,4,4,57,7,1,1,1,0,1,0,0
246,Professional,No,Europe,120000,3,4,4,57,7,1,1,0,0,1,0,0
247,Professional,No,Europe,130000,3,4,3,58,1,1,0,0,0,0,1,0
248,Professional,Yes,Europe,110000,3,4,4,53,11,0,1,1,0,0,1,0
249,Professional,Yes,Europe,130000,3,4,3,53,1,1,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,Management,Yes,North America,110000,5,3,1,50,7,0,1,1,0,0,0,0
18235,Professional,No,North America,120000,4,3,2,50,2,0,0,1,0,0,1,0
18236,Professional,Yes,North America,120000,4,3,3,51,7,1,0,1,0,0,1,0
18237,Professional,Yes,North America,120000,4,3,3,51,7,1,0,0,0,0,1,0
18238,Professional,No,North America,150000,4,1,3,51,2,1,0,1,0,0,1,0
18239,Professional,No,North America,150000,4,1,4,51,2,1,0,0,0,0,1,0
18240,Professional,No,North America,80000,5,4,3,52,1,0,0,0,0,0,1,0
18241,Professional,No,North America,90000,5,4,4,46,2,0,0,0,0,0,1,0
18242,Professional,Yes,North America,100000,3,2,4,51,7,1,1,1,0,0,1,0
18243,Management,Yes,North America,110000,1,3,1,51,7,0,0,1,0,0,0,0
18244,Management,Yes,North America,110000,1,3,2,52,7,0,0,1,0,0,0,0
18245,Management,Yes,North America,130000,1,2,4,51,1,0,1,1,0,0,0,0
18246,Management,No,North America,130000,1,2,4,52,4,0,0,1,0,0,0,0
18247,Professional,Yes,North America,70000,5,4,3,42,7,1,0,0,0,0,1,0
18248,Professional,Yes,North America,90000,4,3,2,53,7,0,0,1,0,1,0,0
18249,Professional,Yes,North America,90000,4,3,2,53,7,0,1,1,0,1,0,0
18250,Professional,No,North America,100000,3,2,4,47,2,0,0,1,0,0,1,0
18251,Management,Yes,North America,110000,1,3,3,53,7,0,1,0,0,0,0,0
18252,Management,Yes,North America,130000,1,3,3,52,1,1,1,1,0,0,0,0
18253,Management,No,North America,130000,3,3,3,53,4,0,0,0,0,0,0,0
18254,Professional,Yes,North America,60000,2,0,2,58,7,1,1,0,0,1,0,0
18255,Professional,No,North America,80000,3,2,1,59,2,1,0,1,0,0,1,0
18256,Professional,No,North America,90000,2,1,1,58,11,1,1,1,0,1,0,0
18257,Professional,Yes,North America,90000,2,1,1,58,11,0,0,1,0,1,0,0
18258,Professional,Yes,North America,90000,2,1,1,58,11,1,1,0,0,1,0,0
18259,Skilled Manual,Yes,North America,70000,2,0,2,59,7,0,0,1,0,0,0,1
18260,Management,No,North America,70000,4,0,2,79,2,0,0,1,1,0,0,0
18261,Management,No,North America,130000,2,3,3,79,1,1,0,1,1,0,0,0
18262,Management,No,North America,50000,2,0,2,78,2,0,0,0,1,0,0,0
18263,Management,No,North America,70000,4,0,2,78,2,0,1,1,1,0,0,0
18264,Management,No,North America,90000,4,0,2,78,2,1,1,0,0,0,0,0
18265,Management,No,North America,90000,4,0,2,77,2,1,0,0,0,0,0,0
18266,Professional,No,North America,80000,5,4,3,54,2,0,0,1,0,0,1,0
18267,Professional,Yes,North America,80000,5,4,3,48,7,0,1,0,0,0,1,0
18268,Professional,Yes,North America,90000,4,3,3,54,7,0,1,1,0,1,0,0
18269,Professional,Yes,North America,90000,4,3,3,54,7,0,1,0,0,1,0,0
18270,Professional,Yes,North America,100000,0,3,1,54,7,0,1,1,0,0,1,0
18271,Professional,No,North America,100000,0,3,1,48,2,0,0,1,0,0,1,0
18272,Professional,Yes,North America,100000,0,3,2,54,7,0,1,1,0,0,1,0
18273,Professional,Yes,North America,100000,0,3,2,49,7,0,1,1,0,0,1,0
18274,Professional,Yes,North America,120000,5,4,3,54,7,1,0,1,0,1,0,0
18275,Management,No,North America,70000,3,0,2,61,2,1,0,0,1,0,0,0
18276,Management,Yes,North America,70000,3,0,2,61,7,1,1,0,1,0,0,0
18277,Management,No,North America,70000,3,0,2,61,2,1,0,0,1,0,0,0
18278,Management,Yes,North America,70000,3,0,2,55,7,1,0,0,1,0,0,0
18279,Management,Yes,North America,70000,3,0,2,61,7,1,0,0,1,0,0,0
18280,Professional,No,North America,40000,3,0,2,52,2,1,0,0,0,0,1,0
18281,Professional,No,North America,40000,4,0,2,59,2,1,0,1,0,0,1,0
18282,Professional,Yes,North America,30000,4,0,2,64,7,0,1,0,0,1,0,0
18283,Professional,No,North America,30000,4,0,2,65,2,0,1,1,0,1,0,0
18284,Professional,No,North America,30000,4,0,2,64,2,0,0,0,0,1,0,0
18285,Professional,No,North America,40000,4,0,2,65,2,1,0,1,0,1,0,0
18286,Professional,No,Pacific,60000,3,3,2,44,1,0,0,1,0,0,0,0
18287,Professional,Yes,Pacific,60000,4,4,1,50,7,0,1,0,0,0,0,0
18288,Professional,No,Pacific,60000,4,4,2,38,1,0,1,1,0,0,0,0
18289,Professional,Yes,Pacific,70000,0,0,1,44,7,1,0,1,0,0,0,0
18290,Professional,No,Pacific,60000,5,5,2,50,1,0,0,1,0,0,0,0
18291,Professional,No,Pacific,60000,3,2,2,50,1,1,1,0,0,0,0,0
18292,Professional,No,Pacific,90000,2,2,0,42,1,1,0,0,0,0,0,0
18293,Professional,Yes,Pacific,90000,3,3,0,47,2,1,0,1,0,0,0,0

In [18]:
englishoccupation_dummies=pd.get_dummies(main_df.EnglishOccupation)
merged4=pd.concat([mergedfinal3,englishoccupation_dummies],axis='columns')
mergedfinal4=merged4.drop(['EnglishOccupation','Professional'],axis='columns')
mergedfinal4

,HouseOwnerFlagText,Region,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer,M,M,Graduate Degree,High School,Partial College,Partial High School,Clerical,Management,Manual,Skilled Manual
0,Yes,Pacific,90000,2,0,0,48,2,1,1,1,0,0,0,0,0,0,0,0
1,No,Pacific,60000,3,3,1,43,1,1,0,1,0,0,0,0,0,0,0,0
2,Yes,Pacific,60000,3,3,1,49,4,1,1,1,0,0,0,0,0,0,0,0
3,No,Pacific,70000,0,0,1,46,7,1,0,0,0,0,0,0,0,0,0,0
4,Yes,Pacific,80000,5,5,4,40,2,1,0,0,0,0,0,0,0,0,0,0
5,Yes,Pacific,70000,0,0,1,43,7,1,0,1,0,0,0,0,0,0,0,0
6,Yes,Pacific,70000,0,0,1,43,7,1,0,0,0,0,0,0,0,0,0,0
7,Yes,Pacific,60000,3,3,2,50,1,1,1,1,0,0,0,0,0,0,0,0
8,Yes,Pacific,60000,4,4,3,44,11,1,0,0,0,0,0,0,0,0,0,0
9,No,Pacific,70000,0,0,1,50,7,1,0,1,0,0,0,0,0,0,0,0
10,No,Pacific,70000,0,0,1,50,7,1,0,0,0,0,0,0,0,0,0,0
11,Yes,Pacific,60000,4,4,4,50,11,1,1,1,0,0,0,0,0,0,0,0
12,Yes,North America,100000,2,0,2,41,2,0,1,0,0,0,0,0,0,1,0,0
13,Yes,North America,100000,2,0,3,40,1,0,1,1,0,0,0,0,0,1,0,0
14,No,North America,100000,3,0,3,46,2,0,0,0,0,0,0,0,0,1,0,0
15,No,North America,30000,0,0,1,35,7,1,0,0,0,0,1,0,0,0,0,1
16,Yes,North America,30000,0,0,1,35,7,1,1,1,0,0,1,0,0,0,0,1
17,Yes,Pacific,20000,4,0,2,70,7,1,0,0,0,1,0,0,0,0,0,1
18,Yes,Pacific,30000,2,0,2,64,7,1,0,1,0,0,1,0,1,0,0,0
19,No,North America,40000,0,0,2,36,7,0,0,1,0,1,0,0,0,0,0,1
20,No,North America,40000,0,0,2,35,2,1,0,1,0,1,0,0,0,0,0,1
21,No,North America,40000,0,0,1,35,2,1,0,0,0,0,1,0,0,0,0,1
22,Yes,North America,40000,0,0,1,35,7,1,1,1,0,0,1,0,0,0,0,1
23,Yes,North America,40000,0,0,1,35,2,0,1,1,0,0,1,0,0,0,0,1
24,Yes,North America,60000,0,0,2,35,7,0,1,1,0,0,1,0,0,0,0,1
25,Yes,Pacific,10000,2,1,2,68,2,1,1,1,0,0,0,1,1,0,0,0
26,No,Pacific,30000,2,0,2,68,2,1,0,1,0,0,1,0,1,0,0,0
27,Yes,Pacific,30000,2,0,2,67,7,1,1,1,0,0,1,0,1,0,0,0
28,Yes,Pacific,30000,2,0,2,68,2,1,1,0,0,0,1,0,1,0,0,0
29,Yes,Pacific,30000,2,0,2,67,2,1,1,1,0,0,1,0,1,0,0,0
30,Yes,Pacific,10000,2,1,2,62,2,1,1,0,0,0,0,1,1,0,0,0
31,Yes,Pacific,20000,4,0,2,67,2,1,1,0,0,1,0,0,0,0,0,1
32,Yes,Pacific,20000,4,0,2,67,2,1,1,0,0,1,0,0,0,0,0,1
33,Yes,Pacific,20000,4,0,2,61,7,1,1,1,0,1,0,0,0,0,0,1
34,Yes,Pacific,20000,4,0,2,67,7,1,1,0,0,1,0,0,0,0,0,1
35,Yes,Pacific,10000,2,1,2,66,2,1,1,0,0,0,0,1,1,0,0,0
36,Yes,North America,60000,0,0,2,35,2,1,1,0,0,0,1,0,0,0,0,1
37,No,North America,40000,0,0,2,36,7,1,0,0,0,0,0,1,1,0,0,0
38,Yes,Pacific,10000,2,1,2,66,7,1,1,0,0,0,0,1,1,0,0,0
39,Yes,Pacific,30000,3,0,2,65,7,1,1,1,0,0,1,0,1,0,0,0
40,Yes,North America,30000,0,0,2,37,2,1,1,1,0,0,1,0,0,0,0,1
41,Yes,North America,60000,0,0,2,36,2,1,1,0,0,0,1,0,0,0,0,1
42,Yes,North America,70000,0,0,2,37,1,1,1,0,0,0,1,0,0,0,0,1
43,Yes,North America,60000,0,0,2,38,7,0,1,1,0,0,1,0,0,0,0,1
44,Yes,Pacific,20000,2,1,2,65,2,1,1,1,0,0,0,1,1,0,0,0
45,No,Pacific,30000,3,0,2,64,2,0,0,1,0,1,0,0,0,0,0,1
46,Yes,Pacific,30000,3,0,2,64,7,1,1,0,0,1,0,0,0,0,0,1
47,No,Pacific,30000,3,0,2,64,2,1,1,0,0,1,0,0,0,0,0,1
48,Yes,Pacific,30000,3,0,2,63,7,1,1,1,0,1,0,0,0,0,0,1
49,Yes,North America,40000,0,0,2,34,7,0,0,0,0,0,0,1,1,0,0,0
50,Yes,Pacific,30000,3,0,2,62,7,1,1,1,0,1,0,0,0,0,0,1
51,No,Pacific,30000,3,0,2,63,2,0,0,1,0,1,0,0,0,0,0,1
52,No,Pacific,40000,2,0,2,63,7,1,0,0,0,0,1,0,1,0,0,0
53,No,North America,60000,0,0,2,34,2,1,1,0,0,0,1,0,0,0,0,1
54,Yes,Pacific,40000,2,0,2,62,7,1,1,0,0,0,1,0,0,0,0,1
55,Yes,Pacific,40000,2,0,2,62,7,1,1,1,0,0,1,0,0,0,0,1
56,Yes,Pacific,40000,3,0,2,61,7,1,1,0,0,0,1,0,0,0,0,1
57,Yes,Pacific,70000,2,0,2,49,2,1,1,1,1,0,0,0,0,1,0,0
58,Yes,Pacific,80000,2,0,2,54,2,1,1,1,0,0,1,0,0,0,0,1
59,Yes,Pacific,80000,2,0,2,60,7,0,0,0,0,0,1,0,0,0,0,1
60,Yes,Pacific,80000,2,0,2,60,7,1,1,1,0,0,1,0,0,0,0,1
61,Yes,Pacific,80000,2,0,2,44,7,1,1,1,0,0,1,0,0,0,0,1
62,Yes,North America,40000,0,0,2,39,7,1,1,1,0,1,0,0,0,0,0,1
63,Yes,North America,40000,0,0,2,39,7,1,0,0,0,1,0,0,0,0,0,1
64,Yes,North America,40000,0,0,2,38,7,1,1,1,0,1,0,0,0,0,0,1
65,No,North America,60000,0,0,2,40,2,0,1,0,0,0,1,0,0,0,0,1
66,Yes,North America,70000,0,0,2,40,7,0,1,0,0,0,1,0,0,0,0,0
67,Yes,North America,60000,0,0,2,37,7,0,0,1,0,0,1,0,0,0,0,0
68,Yes,Pacific,80000,2,0,2,53,7,0,0,0,0,1,0,0,0,0,0,1
69,No,Pacific,80000,2,0,2,53,2,1,0,0,0,1,0,0,0,0,0,1
70,Yes,Pacific,80000,2,0,2,59,7,1,1,1,0,1,0,0,0,0,0,1
71,Yes,Pacific,80000,2,0,2,59,7,0,0,0,0,1,0,0,0,0,0,1
72,No,Pacific,80000,2,0,2,59,2,1,0,0,0,1,0,0,0,0,0,1
73,Yes,Pacific,70000,2,0,2,58,7,0,0,0,0,1,0,0,0,0,0,1
74,Yes,Pacific,70000,2,0,2,58,7,0,0,1,0,1,0,0,0,0,0,1
75,Yes,Pacific,80000,2,0,2,56,7,1,0,0,0,1,0,0,0,0,0,0
76,Yes,Pacific,80000,2,0,2,57,7,1,0,1,0,1,0,0,0,0,0,0
77,No,Pacific,80000,2,0,2,56,2,1,0,0,0,1,0,0,0,0,0,0
78,No,North America,40000,0,0,2,35,2,0,0,0,0,1,0,0,0,0,0,0
79,Yes,Pacific,160000,0,0,2,49,1,0,0,1,1,0,0,0,0,1,0,0
80,Yes,Pacific,170000,0,0,2,55,1,1,1,1,1,0,0,0,0,1,0,0
81,Yes,North America,120000,2,2,3,48,4,0,1,0,0,0,0,0,0,1,0,0
82,No,North America,130000,0,1,3,48,2,1,0,0,1,0,0,0,0,1,0,0
83,Yes,North America,130000,0,1,3,42,2,1,1,0,1,0,0,0,0,1,0,0
84,No,North America,80000,2,0,2,56,2,1,0,1,0,0,0,1,0,0,0,1
85,No,North America,60000,2,0,2,57,7,0,0,0,0,1,0,0,0,0,0,0
86,Yes,North America,70000,2,1,0,56,1,0,1,1,0,0,1,0,0,0,0,0
87,No,North America,70000,3,2,0,56,1,0,1,0,0,0,1,0,0,0,0,0
88,Yes,North America,80000,2,1,0,56,4,1,1,1,0,0,0,0,0,1,0,0
89,Yes,North America,80000,2,1,1,57,4,1,0,0,0,0,0,0,0,1,0,0
90,Yes,North America,90000,2,0,1,51,4,1,0,1,0,0,1,0,0,0,0,0
91,Yes,North America,90000,2,0,1,57,7,0,1,1,0,0,1,0,0,0,0,0
92,Yes,Pacific,90000,2,2,0,47,2,1,1,0,0,0,0,0,0,0,0,0
93,Yes,Pacific,100000,0,0,0,41,1,1,1,0,1,0,0,0,0,1,0,0
94,No,Pacific,70000,1,0,1,52,1,0,0,1,0,0,1,0,0,0,0,1
95,Yes,Pacific,70000,1,0,1,52,7,1,0,1,0,0,1,0,0,0,0,1
96,Yes,Pacific,60000,1,0,1,52,7,1,1,1,0,0,0,0,0,0,0,0
97,Yes,Pacific,60000,1,0,1,47,7,1,1,1,0,0,1,0,0,0,0,1
98,No,Pacific,60000,1,0,1,53,1,0,0,0,0,0,1,0,0,0,0,1
99,Yes,Pacific,60000,1,0,1,53,1,1,1,1,0,0,0,0,0,0,0,0
100,Yes,Pacific,60000,1,0,1,53,7,1,0,0,0,0,1,0,0,0,0,1
101,No,Pacific,70000,0,0,1,49,1,1,0,0,0,0,0,0,0,0,0,0
102,Yes,Pacific,80000,5,5,4,49,2,0,0,0,0,0,0,0,0,0,0,0
103,Yes,Pacific,70000,0,0,1,38,7,1,0,0,0,0,0,0,0,0,0,0
104,No,Pacific,70000,0,0,1,44,1,1,1,1,0,0,0,0,0,0,0,0
105,No,Pacific,70000,0,0,1,49,7,1,0,0,0,0,0,0,0,0,0,0
106,No,Pacific,70000,0,0,1,49,7,1,0,1,0,0,0,0,0,0,0,0
107,Yes,Pacific,90000,1,0,1,43,7,1,1,0,0,0,0,0,0,0,0,0
108,No,Pacific,70000,0,0,2,51,1,1,0,0,0,0,0,0,0,0,0,0
109,No,Pacific,70000,0,0,2,39,1,1,0,1,0,0,0,0,0,0,0,0
110,Yes,Pacific,60000,1,0,1,52,7,1,1,1,0,0,1,0,0,0,0,1
111,Yes,Pacific,60000,1,0,1,52,1,1,1,0,0,0,1,0,0,0,0,1
112,Yes,Pacific,60000,1,0,1,51,1,1,1,0,0,0,1,0,0,0,0,1
113,Yes,Pacific,70000,5,4,2,47,7,0,1,1,0,0,0,0,0,0,0,0
114,Yes,Pacific,70000,5,4,2,52,7,0,0,0,0,0,1,0,0,0,0,1
115,Yes,Pacific,70000,5,4,2,52,1,0,1,1,0,0,1,0,0,0,0,1
116,Yes,Pacific,70000,5,4,2,40,7,0,1,1,0,0,1,0,0,0,0,1
117,Yes,Pacific,70000,5,4,3,53,11,1,1,0,0,0,1,0,0,0,0,1
118,No,Pacific,80000,1,0,1,57,1,0,0,1,0,0,1,0,0,0,0,1
119,No,Pacific,30000,2,0,2,79,1,0,0,1,0,0,1,0,1,0,0,0
120,Yes,Pacific,40000,2,0,1,78,7,1,0,0,0,0,0,0,0,1,0,0
121,Yes,Pacific,70000,5,4,3,53,11,0,1,1,0,0,1,0,0,0,0,1
122,Yes,Pacific,70000,5,4,3,54,7,0,1,1,0,0,1,0,0,0,0,1
123,Yes,Pacific,70000,5,4,3,54,11,0,1,1,0,0,1,0,0,0,0,1
124,Yes,Pacific,80000,1,0,1,51,7,1,0,1,0,0,1,0,0,0,0,1
125,Yes,Pacific,70000,1,0,1,58,7,0,0,0,0,0,1,0,0,0,0,1
126,No,Pacific,10000,2,1,2,65,1,1,1,1,0,1,0,0,0,0,0,1
127,Yes,North America,40000,0,0,1,38,7,0,1,0,0,1,0,0,0,0,0,1
128,Yes,North America,40000,0,0,1,38,7,0,1,0,0,1,0,0,0,0,0,1
129,Yes,North America,40000,0,0,1,39,7,1,0,0,0,1,0,0,0,0,0,1
130,Yes,North America,30000,0,0,2,34,7,0,1,0,0,1,0,0,0,0,0,1
131,No,North America,30000,0,0,2,34,1,0,1,0,0,1,0,0,0,0,0,1
132,No,North America,30000,0,0,2,33,7,1,0,0,0,1,0,0,0,0,0,1
133,No,North America,30000,0,0,2,33,1,0,0,0,0,0,0,1,1,0,0,0
134,Yes,Pacific,10000,5,0,2,63,7,1,0,1,0,1,0,0,0,0,0,1
135,No,North America,30000,0,0,2,34,7,1,0,1,0,0,0,1,1,0,0,0
136,No,North America,40000,0,0,2,35,1,1,0,0,0,1,0,0,0,0,0,1
137,Yes,North America,40000,0,0,2,36,7,0,1,0,0,1,0,0,0,0,0,1
138,No,North America,40000,0,0,2,35,1,0,1,0,0,1,0,0,0,0,0,1
139,No,Pacific,30000,2,0,2,70,7,0,0,0,0,0,1,0,1,0,0,0
140,No,North America,30000,0,0,2,37,7,0,0,1,0,0,0,1,1,0,0,0
141,No,North America,40000,0,0,2,37,1,0,1,0,0,1,0,0,0,0,0,1
142,No,North America,40000,0,0,2,37,1,0,0,1,0,1,0,0,0,0,0,1
143,Yes,North America,40000,0,0,2,37,7,0,1,1,0,1,0,0,0,0,0,1
144,No,North America,40000,0,0,2,34,1,1,0,1,0,1,0,0,0,0,0,1
145,No,North America,40000,0,0,2,34,1,1,0,0,0,1,0,0,0,0,0,1
146,Yes,Pacific,40000,2,0,2,75,7,0,0,0,0,0,0,0,0,1,0,0
147,Yes,Pacific,60000,2,0,1,75,1,1,1,1,1,0,0,0,0,1,0,0
148,Yes,Pacific,40000,2,0,2,73,7,0,1,1,0,0,0,0,0,1,0,0
149,Yes,Pacific,40000,2,0,2,73,1,0,1,1,0,0,0,0,0,1,0,0
150,Yes,Pacific,40000,2,0,2,73,7,0,0,1,0,0,0,0,0,1,0,0
151,No,Pacific,60000,2,0,1,72,1,1,0,0,1,0,0,0,0,1,0,0
152,Yes,North America,40000,0,0,2,38,7,1,0,1,0,1,0,0,0,0,0,1
153,Yes,North America,40000,0,0,2,38,7,0,1,0,0,1,0,0,0,0,0,1
154,Yes,North America,40000,0,0,1,38,7,1,0,0,0,0,1,0,0,0,0,1
155,No,North America,40000,0,0,1,38,2,1,0,1,0,0,1,0,0,0,0,1
156,No,North America,40000,0,0,1,38,2,1,0,0,0,0,1,0,0,0,0,1
157,Yes,North America,40000,0,0,2,39,7,0,1,0,0,1,0,0,0,0,0,1
158,Yes,North America,40000,0,0,2,38,7,1,0,1,0,1,0,0,0,0,0,1
159,No,North America,40000,0,0,2,38,2,0,0,0,0,1,0,0,0,0,0,1
160,No,North America,40000,0,0,1,40,7,1,0,1,0,0,1,0,0,0,0,1
161,No,North America,40000,0,0,1,40,2,0,0,0,0,0,1,0,0,0,0,1
162,Yes,North America,40000,0,0,1,40,7,1,0,1,0,0,1,0,0,0,0,1
163,Yes,North America,40000,0,0,1,39,7,0,1,1,0,0,1,0,0,0,0,1
164,No,North America,40000,0,0,1,40,2,0,0,1,0,0,1,0,0,0,0,1
165,No,North America,60000,0,0,1,41,2,0,1,0,0,0,1,0,0,0,0,1
166,No,North America,70000,0,0,2,42,1,0,0,0,0,0,1,0,0,0,0,1
167,No,North America,80000,0,0,1,42,1,1,0,0,0,0,0,0,0,1,0,0
168,No,North America,80000,0,0,1,46,1,1,0,1,0,0,0,0,0,1,0,0
169,Yes,North America,90000,4,4,1,46,1,0,1,1,0,0,0,0,0,1,0,0
170,Yes,North America,90000,4,4,1,46,1,0,1,0,0,0,0,0,0,1,0,0
171,Yes,North America,100000,1,0,2,41,2,1,0,1,0,0,0,0,0,1,0,0
172,Yes,North America,100000,1,0,2,46,2,0,1,0,0,0,0,0,0,1,0,0
173,No,North America,110000,0,0,4,47,1,0,0,0,1,0,0,0,0,1,0,0
174,Yes,North America,110000,0,1,0,47,4,0,1,1,1,0,0,0,0,1,0,0
175,Yes,North America,70000,0,0,2,51,7,1,0,1,0,0,1,0,0,0,0,1
176,Yes,North America,90000,4,4,1,41,2,0,1,1,0,0,0,0,0,1,0,0
177,Yes,North America,110000,2,4,2,72,7,0,1,1,1,0,0,0,0,1,0,0
178,Yes,North America,100000,2,3,3,65,2,0,1,1,1,0,0,0,0,1,0,0
179,Yes,North America,120000,2,4,3,60,7,0,1,0,1,0,0,0,0,1,0,0
180,Yes,North America,160000,1,3,4,71,1,0,1,0,0,0,0,0,0,1,0,0
181,Yes,North America,170000,2,3,2,60,1,0,1,1,1,0,0,0,0,1,0,0
182,Yes,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0
183,Yes,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0
184,Yes,North America,70000,4,0,2,64,11,0,0,0,0,0,0,0,0,1,0,0
185,Yes,North America,70000,4,0,2,69,11,0,0,0,0,0,0,0,0,1,0,0
186,Yes,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0
187,Yes,North America,60000,4,0,2,70,11,0,1,0,1,0,0,0,0,1,0,0
188,No,North America,60000,4,0,2,69,2,0,1,0,1,0,0,0,0,1,0,0
189,Yes,North America,60000,4,0,2,70,11,1,0,1,1,0,0,0,0,1,0,0
190,Yes,North America,70000,5,0,2,70,11,0,1,1,0,0,0,0,0,1,0,0
191,Yes,North America,70000,5,0,3,68,11,1,0,0,0,0,0,0,0,1,0,0
192,Yes,North America,60000,4,0,2,68,4,0,1,1,0,0,0,0,0,1,0,0
193,Yes,North America,60000,4,0,2,69,4,0,1,1,0,0,0,0,0,1,0,0
194,Yes,North America,60000,4,0,2,69,4,0,1,0,0,0,0,0,0,1,0,0
195,Yes,North America,60000,5,0,3,68,11,0,1,0,0,0,0,0,0,1,0,0
196,Yes,North America,60000,5,0,3,68,11,0,1,1,0,0,0,0,0,1,0,0
197,No,North America,70000,3,1,1,68,2,0,1,0,0,0,0,0,0,1,0,0
198,Yes,North America,70000,4,1,1,67,11,0,0,0,0,0,0,0,0,1,0,0
199,Yes,North America,70000,4,1,1,62,11,0,1,0,0,0,0,0,0,1,0,0
200,Yes,North America,70000,4,1,1,66,2,0,1,1,0,0,0,0,0,1,0,0
201,Yes,North America,70000,4,1,1,67,11,0,1,0,0,0,0,0,0,1,0,0
202,No,North America,80000,5,0,2,61,2,0,1,0,0,0,0,0,0,1,0,0
203,Yes,North America,40000,2,1,2,60,11,0,1,1,0,1,0,0,0,0,0,0
204,Yes,North America,40000,2,1,2,66,4,0,1,0,0,1,0,0,0,0,0,0
205,Yes,North America,40000,2,1,2,66,11,0,1,0,0,1,0,0,0,0,0,0
206,Yes,North America,60000,2,1,1,65,11,0,1,1,0,0,1,0,0,0,0,0
207,Yes,North America,60000,2,1,1,66,11,0,0,0,0,0,1,0,0,0,0,0
208,Yes,North America,60000,2,1,0,66,11,0,1,0,0,0,0,0,0,1,0,0
209,Yes,North America,60000,2,1,0,66,11,0,1,0,0,0,0,0,0,1,0,0
210,Yes,North America,70000,4,1,2,66,11,0,1,1,0,0,1,0,0,0,0,0
211,Yes,North America,40000,2,1,2,59,4,0,1,0,0,1,0,0,0,0,0,0
212,Yes,North America,40000,2,1,2,64,4,0,1,0,0,1,0,0,0,0,0,0
213,Yes,North America,60000,2,1,2,65,11,0,0,0,0,0,1,0,0,0,0,0
214,Yes,North America,60000,2,1,2,64,11,0,0,1,0,0,1,0,0,0,0,0
215,Yes,North America,40000,2,1,2,58,11,0,1,0,0,0,0,1,0,0,0,1
216,Yes,North America,60000,2,1,2,64,11,1,0,0,0,0,1,0,0,0,0,0
217,Yes,North America,60000,2,1,2,64,11,1,0,0,0,0,1,0,0,0,0,0
218,No,North America,60000,2,1,2,58,4,0,0,0,0,0,1,0,0,0,0,0
219,Yes,North America,60000,2,1,2,63,11,0,1,1,0,1,0,0,0,0,0,0
220,Yes,North America,60000,2,1,1,59,11,0,1,0,0,0,1,0,0,0,0,0
221,Yes,North America,70000,4,2,1,64,2,0,1,1,0,0,1,0,0,0,0,0
222,Yes,North America,80000,3,1,1,64,2,0,1,0,0,0,0,0,0,1,0,0
223,Yes,North America,70000,2,1,2,62,4,0,0,0,0,1,0,0,0,0,0,0
224,Yes,North America,70000,2,1,2,62,11,1,0,0,0,1,0,0,0,0,0,0
225,Yes,North America,60000,2,1,1,58,11,0,1,0,0,0,1,0,0,0,0,0
226,Yes,North America,60000,2,1,1,57,4,0,1,0,0,0,1,0,0,0,0,0
227,Yes,North America,60000,2,1,2,57,11,1,0,1,0,0,1,0,0,0,0,0
228,Yes,North America,60000,2,1,2,63,11,0,1,0,0,0,1,0,0,0,0,0
229,Yes,North America,70000,4,2,1,62,11,0,0,1,0,0,1,0,0,0,0,0
230,No,North America,70000,4,2,2,63,4,0,1,0,0,0,1,0,0,0,0,0
231,Yes,North America,60000,2,1,2,56,11,0,1,1,0,1,0,0,0,0,0,0
232,No,North America,60000,3,1,2,61,4,0,1,0,0,1,0,0,0,0,0,0
233,Yes,North America,70000,4,2,2,56,11,0,1,1,0,0,1,0,0,0,0,0
234,Yes,North America,70000,4,2,2,61,11,0,0,0,0,0,1,0,0,0,0,0
235,Yes,North America,70000,4,2,2,62,11,0,1,1,0,0,1,0,0,0,0,0
236,Yes,North America,70000,5,2,2,62,11,0,0,1,0,0,1,0,0,0,0,0
237,No,Europe,130000,2,3,4,55,1,1,0,1,0,0,0,0,0,1,0,0
238,No,Europe,130000,2,3,4,56,1,1,0,0,0,0,0,0,0,1,0,0
239,No,Europe,130000,2,4,2,50,7,1,1,0,0,0,1,0,0,0,0,0
240,Yes,Europe,160000,2,3,4,55,7,1,1,0,0,0,1,0,0,0,0,0
241,Yes,Europe,100000,2,3,4,45,7,1,0,0,0,0,1,0,0,0,0,0
242,Yes,Europe,110000,2,4,3,56,7,1,1,1,0,0,1,0,0,0,0,0
243,Yes,Europe,150000,2,3,3,56,1,1,1,0,0,0,1,0,0,0,0,0
244,No,Europe,170000,2,3,3,51,1,1,0,0,0,0,0,0,0,1,0,0
245,No,Europe,120000,3,4,4,57,7,1,1,1,0,1,0,0,0,0,0,0
246,No,Europe,120000,3,4,4,57,7,1,1,0,0,1,0,0,0,0,0,0
247,No,Europe,130000,3,4,3,58,1,1,0,0,0,0,1,0,0,0,0,0
248,Yes,Europe,110000,3,4,4,53,11,0,1,1,0,0,1,0,0,0,0,0
249,Yes,Europe,130000,3,4,3,53,1,1,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,Yes,North America,110000,5,3,1,50,7,0,1,1,0,0,0,0,0,1,0,0
18235,No,North America,120000,4,3,2,50,2,0,0,1,0,0,1,0,0,0,0,0
18236,Yes,North America,120000,4,3,3,51,7,1,0,1,0,0,1,0,0,0,0,0
18237,Yes,North America,120000,4,3,3,51,7,1,0,0,0,0,1,0,0,0,0,0
18238,No,North America,150000,4,1,3,51,2,1,0,1,0,0,1,0,0,0,0,0
18239,No,North America,150000,4,1,4,51,2,1,0,0,0,0,1,0,0,0,0,0
18240,No,North America,80000,5,4,3,52,1,0,0,0,0,0,1,0,0,0,0,0
18241,No,North America,90000,5,4,4,46,2,0,0,0,0,0,1,0,0,0,0,0
18242,Yes,North America,100000,3,2,4,51,7,1,1,1,0,0,1,0,0,0,0,0
18243,Yes,North America,110000,1,3,1,51,7,0,0,1,0,0,0,0,0,1,0,0
18244,Yes,North America,110000,1,3,2,52,7,0,0,1,0,0,0,0,0,1,0,0
18245,Yes,North America,130000,1,2,4,51,1,0,1,1,0,0,0,0,0,1,0,0
18246,No,North America,130000,1,2,4,52,4,0,0,1,0,0,0,0,0,1,0,0
18247,Yes,North America,70000,5,4,3,42,7,1,0,0,0,0,1,0,0,0,0,0
18248,Yes,North America,90000,4,3,2,53,7,0,0,1,0,1,0,0,0,0,0,0
18249,Yes,North America,90000,4,3,2,53,7,0,1,1,0,1,0,0,0,0,0,0
18250,No,North America,100000,3,2,4,47,2,0,0,1,0,0,1,0,0,0,0,0
18251,Yes,North America,110000,1,3,3,53,7,0,1,0,0,0,0,0,0,1,0,0
18252,Yes,North America,130000,1,3,3,52,1,1,1,1,0,0,0,0,0,1,0,0
18253,No,North America,130000,3,3,3,53,4,0,0,0,0,0,0,0,0,1,0,0
18254,Yes,North America,60000,2,0,2,58,7,1,1,0,0,1,0,0,0,0,0,0
18255,No,North America,80000,3,2,1,59,2,1,0,1,0,0,1,0,0,0,0,0
18256,No,North America,90000,2,1,1,58,11,1,1,1,0,1,0,0,0,0,0,0
18257,Yes,North America,90000,2,1,1,58,11,0,0,1,0,1,0,0,0,0,0,0
18258,Yes,North America,90000,2,1,1,58,11,1,1,0,0,1,0,0,0,0,0,0
18259,Yes,North America,70000,2,0,2,59,7,0,0,1,0,0,0,1,0,0,0,1
18260,No,North America,70000,4,0,2,79,2,0,0,1,1,0,0,0,0,1,0,0
18261,No,North America,130000,2,3,3,79,1,1,0,1,1,0,0,0,0,1,0,0
18262,No,North America,50000,2,0,2,78,2,0,0,0,1,0,0,0,0,1,0,0
18263,No,North America,70000,4,0,2,78,2,0,1,1,1,0,0,0,0,1,0,0
18264,No,North America,90000,4,0,2,78,2,1,1,0,0,0,0,0,0,1,0,0
18265,No,North America,90000,4,0,2,77,2,1,0,0,0,0,0,0,0,1,0,0
18266,No,North America,80000,5,4,3,54,2,0,0,1,0,0,1,0,0,0,0,0
18267,Yes,North America,80000,5,4,3,48,7,0,1,0,0,0,1,0,0,0,0,0
18268,Yes,North America,90000,4,3,3,54,7,0,1,1,0,1,0,0,0,0,0,0
18269,Yes,North America,90000,4,3,3,54,7,0,1,0,0,1,0,0,0,0,0,0
18270,Yes,North America,100000,0,3,1,54,7,0,1,1,0,0,1,0,0,0,0,0
18271,No,North America,100000,0,3,1,48,2,0,0,1,0,0,1,0,0,0,0,0
18272,Yes,North America,100000,0,3,2,54,7,0,1,1,0,0,1,0,0,0,0,0
18273,Yes,North America,100000,0,3,2,49,7,0,1,1,0,0,1,0,0,0,0,0
18274,Yes,North America,120000,5,4,3,54,7,1,0,1,0,1,0,0,0,0,0,0
18275,No,North America,70000,3,0,2,61,2,1,0,0,1,0,0,0,0,1,0,0
18276,Yes,North America,70000,3,0,2,61,7,1,1,0,1,0,0,0,0,1,0,0
18277,No,North America,70000,3,0,2,61,2,1,0,0,1,0,0,0,0,1,0,0
18278,Yes,North America,70000,3,0,2,55,7,1,0,0,1,0,0,0,0,1,0,0
18279,Yes,North America,70000,3,0,2,61,7,1,0,0,1,0,0,0,0,1,0,0
18280,No,North America,40000,3,0,2,52,2,1,0,0,0,0,1,0,0,0,0,0
18281,No,North America,40000,4,0,2,59,2,1,0,1,0,0,1,0,0,0,0,0
18282,Yes,North America,30000,4,0,2,64,7,0,1,0,0,1,0,0,0,0,0,0
18283,No,North America,30000,4,0,2,65,2,0,1,1,0,1,0,0,0,0,0,0
18284,No,North America,30000,4,0,2,64,2,0,0,0,0,1,0,0,0,0,0,0
18285,No,North America,40000,4,0,2,65,2,1,0,1,0,1,0,0,0,0,0,0
18286,No,Pacific,60000,3,3,2,44,1,0,0,1,0,0,0,0,0,0,0,0
18287,Yes,Pacific,60000,4,4,1,50,7,0,1,0,0,0,0,0,0,0,0,0
18288,No,Pacific,60000,4,4,2,38,1,0,1,1,0,0,0,0,0,0,0,0
18289,Yes,Pacific,70000,0,0,1,44,7,1,0,1,0,0,0,0,0,0,0,0
18290,No,Pacific,60000,5,5,2,50,1,0,0,1,0,0,0,0,0,0,0,0
18291,No,Pacific,60000,3,2,2,50,1,1,1,0,0,0,0,0,0,0,0,0
18292,No,Pacific,90000,2,2,0,42,1,1,0,0,0,0,0,0,0,0,0,0
18293,Yes,Pacific,90000,3,3,0,47,2,1,0,1,0,0,0,0,0,0,0,0
18294,No,Pacific,60000,1,0,1,53,1,1,0,0,0,0,1,0,0,0,0,1
18295,Yes,Pacific,110000,0,0,2,48,2,1,0,1,1,0,0,0,0,1,0,0
18296,No,Pacific,110000,0,0,3,47,2,0,0,0,1,0,0,0,0,1,0,0
18297,No,Pacific,60000,1,0,1,48,1,1,0,0,0,0,1,0,0,0,0,1
18298,Yes,Pacific,60000,1,0,1,54,7,1,0,0,0,0,1,0,0,0,0,1
18299,Yes,Pacific,60000,1,0,1,53,7,1,1,0,0,0,1,0,0,0,0,1
18300,No,Pacific,70000,0,0,1,48,7,1,0,1,0,0,0,0,0,0,0,0
18301,Yes,Pacific,80000,5,5,4,43,2,0,1,1,0,0,0,0,0,0,0,0
18302,No,Pacific,70000,0,0,1,50,7,0,0,0,0,0,0,0,0,0,0,0
18303,Yes,Pacific,70000,0,0,1,50,7,1,0,1,0,0,0,0,0,0,0,0
18304,Yes,Pacific,100000,5,0,1,55,11,0,1,1,0,0,0,0,0,0,0,0
18305,No,Pacific,100000,5,0,1,55,11,0,0,0,0,0,0,0,0,0,0,0
18306,No,Pacific,70000,0,0,1,45,1,1,0,1,0,0,0,0,0,0,0,0
18307,No,Pacific,70000,0,0,1,51,7,0,0,1,0,0,0,0,0,0,0,0
18308,No,Pacific,70000,0,0,2,40,1,1,0,1,0,0,0,0,0,0,0,0
18309,Yes,Pacific,70000,0,0,2,51,7,1,0,1,0,0,0,0,0,0,0,0
18310,No,Pacific,70000,0,0,2,50,7,1,0,1,0,0,0,0,0,0,0,0
18311,Yes,Pacific,60000,1,0,1,52,7,1,0,0,0,0,1,0,0,0,0,1
18312,Yes,Pacific,70000,5,4,2,46,7,0,0,0,0,0,1,0,0,0,0,1
18313,Yes,Pacific,60000,1,0,1,52,7,1,1,1,0,0,1,0,0,0,0,1
18314,Yes,Pacific,60000,1,0,1,47,7,1,1,0,0,0,1,0,0,0,0,1
18315,Yes,Pacific,90000,2,0,1,44,7,0,1,0,0,0,0,0,0,0,0,0
18316,No,Pacific,90000,2,0,1,55,4,1,0,1,0,0,0,0,0,0,0,0
18317,No,Pacific,90000,2,0,1,56,4,1,0,1,0,0,0,0,0,0,0,0
18318,Yes,Pacific,100000,4,0,2,55,2,1,1,1,0,0,0,0,0,1,0,0
18319,No,Pacific,70000,1,0,1,57,1,1,0,1,0,0,1,0,0,0,0,1

In [19]:
houseownerflagtext_dummies=pd.get_dummies(main_df.HouseOwnerFlagText)
merged5=pd.concat([mergedfinal4,houseownerflagtext_dummies],axis='columns')
mergedfinal5=merged5.drop(['HouseOwnerFlagText','No'],axis='columns')
mergedfinal5

,Region,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer,M,M,Graduate Degree,High School,Partial College,Partial High School,Clerical,Management,Manual,Skilled Manual,Yes
0,Pacific,90000,2,0,0,48,2,1,1,1,0,0,0,0,0,0,0,0,1
1,Pacific,60000,3,3,1,43,1,1,0,1,0,0,0,0,0,0,0,0,0
2,Pacific,60000,3,3,1,49,4,1,1,1,0,0,0,0,0,0,0,0,1
3,Pacific,70000,0,0,1,46,7,1,0,0,0,0,0,0,0,0,0,0,0
4,Pacific,80000,5,5,4,40,2,1,0,0,0,0,0,0,0,0,0,0,1
5,Pacific,70000,0,0,1,43,7,1,0,1,0,0,0,0,0,0,0,0,1
6,Pacific,70000,0,0,1,43,7,1,0,0,0,0,0,0,0,0,0,0,1
7,Pacific,60000,3,3,2,50,1,1,1,1,0,0,0,0,0,0,0,0,1
8,Pacific,60000,4,4,3,44,11,1,0,0,0,0,0,0,0,0,0,0,1
9,Pacific,70000,0,0,1,50,7,1,0,1,0,0,0,0,0,0,0,0,0
10,Pacific,70000,0,0,1,50,7,1,0,0,0,0,0,0,0,0,0,0,0
11,Pacific,60000,4,4,4,50,11,1,1,1,0,0,0,0,0,0,0,0,1
12,North America,100000,2,0,2,41,2,0,1,0,0,0,0,0,0,1,0,0,1
13,North America,100000,2,0,3,40,1,0,1,1,0,0,0,0,0,1,0,0,1
14,North America,100000,3,0,3,46,2,0,0,0,0,0,0,0,0,1,0,0,0
15,North America,30000,0,0,1,35,7,1,0,0,0,0,1,0,0,0,0,1,0
16,North America,30000,0,0,1,35,7,1,1,1,0,0,1,0,0,0,0,1,1
17,Pacific,20000,4,0,2,70,7,1,0,0,0,1,0,0,0,0,0,1,1
18,Pacific,30000,2,0,2,64,7,1,0,1,0,0,1,0,1,0,0,0,1
19,North America,40000,0,0,2,36,7,0,0,1,0,1,0,0,0,0,0,1,0
20,North America,40000,0,0,2,35,2,1,0,1,0,1,0,0,0,0,0,1,0
21,North America,40000,0,0,1,35,2,1,0,0,0,0,1,0,0,0,0,1,0
22,North America,40000,0,0,1,35,7,1,1,1,0,0,1,0,0,0,0,1,1
23,North America,40000,0,0,1,35,2,0,1,1,0,0,1,0,0,0,0,1,1
24,North America,60000,0,0,2,35,7,0,1,1,0,0,1,0,0,0,0,1,1
25,Pacific,10000,2,1,2,68,2,1,1,1,0,0,0,1,1,0,0,0,1
26,Pacific,30000,2,0,2,68,2,1,0,1,0,0,1,0,1,0,0,0,0
27,Pacific,30000,2,0,2,67,7,1,1,1,0,0,1,0,1,0,0,0,1
28,Pacific,30000,2,0,2,68,2,1,1,0,0,0,1,0,1,0,0,0,1
29,Pacific,30000,2,0,2,67,2,1,1,1,0,0,1,0,1,0,0,0,1
30,Pacific,10000,2,1,2,62,2,1,1,0,0,0,0,1,1,0,0,0,1
31,Pacific,20000,4,0,2,67,2,1,1,0,0,1,0,0,0,0,0,1,1
32,Pacific,20000,4,0,2,67,2,1,1,0,0,1,0,0,0,0,0,1,1
33,Pacific,20000,4,0,2,61,7,1,1,1,0,1,0,0,0,0,0,1,1
34,Pacific,20000,4,0,2,67,7,1,1,0,0,1,0,0,0,0,0,1,1
35,Pacific,10000,2,1,2,66,2,1,1,0,0,0,0,1,1,0,0,0,1
36,North America,60000,0,0,2,35,2,1,1,0,0,0,1,0,0,0,0,1,1
37,North America,40000,0,0,2,36,7,1,0,0,0,0,0,1,1,0,0,0,0
38,Pacific,10000,2,1,2,66,7,1,1,0,0,0,0,1,1,0,0,0,1
39,Pacific,30000,3,0,2,65,7,1,1,1,0,0,1,0,1,0,0,0,1
40,North America,30000,0,0,2,37,2,1,1,1,0,0,1,0,0,0,0,1,1
41,North America,60000,0,0,2,36,2,1,1,0,0,0,1,0,0,0,0,1,1
42,North America,70000,0,0,2,37,1,1,1,0,0,0,1,0,0,0,0,1,1
43,North America,60000,0,0,2,38,7,0,1,1,0,0,1,0,0,0,0,1,1
44,Pacific,20000,2,1,2,65,2,1,1,1,0,0,0,1,1,0,0,0,1
45,Pacific,30000,3,0,2,64,2,0,0,1,0,1,0,0,0,0,0,1,0
46,Pacific,30000,3,0,2,64,7,1,1,0,0,1,0,0,0,0,0,1,1
47,Pacific,30000,3,0,2,64,2,1,1,0,0,1,0,0,0,0,0,1,0
48,Pacific,30000,3,0,2,63,7,1,1,1,0,1,0,0,0,0,0,1,1
49,North America,40000,0,0,2,34,7,0,0,0,0,0,0,1,1,0,0,0,1
50,Pacific,30000,3,0,2,62,7,1,1,1,0,1,0,0,0,0,0,1,1
51,Pacific,30000,3,0,2,63,2,0,0,1,0,1,0,0,0,0,0,1,0
52,Pacific,40000,2,0,2,63,7,1,0,0,0,0,1,0,1,0,0,0,0
53,North America,60000,0,0,2,34,2,1,1,0,0,0,1,0,0,0,0,1,0
54,Pacific,40000,2,0,2,62,7,1,1,0,0,0,1,0,0,0,0,1,1
55,Pacific,40000,2,0,2,62,7,1,1,1,0,0,1,0,0,0,0,1,1
56,Pacific,40000,3,0,2,61,7,1,1,0,0,0,1,0,0,0,0,1,1
57,Pacific,70000,2,0,2,49,2,1,1,1,1,0,0,0,0,1,0,0,1
58,Pacific,80000,2,0,2,54,2,1,1,1,0,0,1,0,0,0,0,1,1
59,Pacific,80000,2,0,2,60,7,0,0,0,0,0,1,0,0,0,0,1,1
60,Pacific,80000,2,0,2,60,7,1,1,1,0,0,1,0,0,0,0,1,1
61,Pacific,80000,2,0,2,44,7,1,1,1,0,0,1,0,0,0,0,1,1
62,North America,40000,0,0,2,39,7,1,1,1,0,1,0,0,0,0,0,1,1
63,North America,40000,0,0,2,39,7,1,0,0,0,1,0,0,0,0,0,1,1
64,North America,40000,0,0,2,38,7,1,1,1,0,1,0,0,0,0,0,1,1
65,North America,60000,0,0,2,40,2,0,1,0,0,0,1,0,0,0,0,1,0
66,North America,70000,0,0,2,40,7,0,1,0,0,0,1,0,0,0,0,0,1
67,North America,60000,0,0,2,37,7,0,0,1,0,0,1,0,0,0,0,0,1
68,Pacific,80000,2,0,2,53,7,0,0,0,0,1,0,0,0,0,0,1,1
69,Pacific,80000,2,0,2,53,2,1,0,0,0,1,0,0,0,0,0,1,0
70,Pacific,80000,2,0,2,59,7,1,1,1,0,1,0,0,0,0,0,1,1
71,Pacific,80000,2,0,2,59,7,0,0,0,0,1,0,0,0,0,0,1,1
72,Pacific,80000,2,0,2,59,2,1,0,0,0,1,0,0,0,0,0,1,0
73,Pacific,70000,2,0,2,58,7,0,0,0,0,1,0,0,0,0,0,1,1
74,Pacific,70000,2,0,2,58,7,0,0,1,0,1,0,0,0,0,0,1,1
75,Pacific,80000,2,0,2,56,7,1,0,0,0,1,0,0,0,0,0,0,1
76,Pacific,80000,2,0,2,57,7,1,0,1,0,1,0,0,0,0,0,0,1
77,Pacific,80000,2,0,2,56,2,1,0,0,0,1,0,0,0,0,0,0,0
78,North America,40000,0,0,2,35,2,0,0,0,0,1,0,0,0,0,0,0,0
79,Pacific,160000,0,0,2,49,1,0,0,1,1,0,0,0,0,1,0,0,1
80,Pacific,170000,0,0,2,55,1,1,1,1,1,0,0,0,0,1,0,0,1
81,North America,120000,2,2,3,48,4,0,1,0,0,0,0,0,0,1,0,0,1
82,North America,130000,0,1,3,48,2,1,0,0,1,0,0,0,0,1,0,0,0
83,North America,130000,0,1,3,42,2,1,1,0,1,0,0,0,0,1,0,0,1
84,North America,80000,2,0,2,56,2,1,0,1,0,0,0,1,0,0,0,1,0
85,North America,60000,2,0,2,57,7,0,0,0,0,1,0,0,0,0,0,0,0
86,North America,70000,2,1,0,56,1,0,1,1,0,0,1,0,0,0,0,0,1
87,North America,70000,3,2,0,56,1,0,1,0,0,0,1,0,0,0,0,0,0
88,North America,80000,2,1,0,56,4,1,1,1,0,0,0,0,0,1,0,0,1
89,North America,80000,2,1,1,57,4,1,0,0,0,0,0,0,0,1,0,0,1
90,North America,90000,2,0,1,51,4,1,0,1,0,0,1,0,0,0,0,0,1
91,North America,90000,2,0,1,57,7,0,1,1,0,0,1,0,0,0,0,0,1
92,Pacific,90000,2,2,0,47,2,1,1,0,0,0,0,0,0,0,0,0,1
93,Pacific,100000,0,0,0,41,1,1,1,0,1,0,0,0,0,1,0,0,1
94,Pacific,70000,1,0,1,52,1,0,0,1,0,0,1,0,0,0,0,1,0
95,Pacific,70000,1,0,1,52,7,1,0,1,0,0,1,0,0,0,0,1,1
96,Pacific,60000,1,0,1,52,7,1,1,1,0,0,0,0,0,0,0,0,1
97,Pacific,60000,1,0,1,47,7,1,1,1,0,0,1,0,0,0,0,1,1
98,Pacific,60000,1,0,1,53,1,0,0,0,0,0,1,0,0,0,0,1,0
99,Pacific,60000,1,0,1,53,1,1,1,1,0,0,0,0,0,0,0,0,1
100,Pacific,60000,1,0,1,53,7,1,0,0,0,0,1,0,0,0,0,1,1
101,Pacific,70000,0,0,1,49,1,1,0,0,0,0,0,0,0,0,0,0,0
102,Pacific,80000,5,5,4,49,2,0,0,0,0,0,0,0,0,0,0,0,1
103,Pacific,70000,0,0,1,38,7,1,0,0,0,0,0,0,0,0,0,0,1
104,Pacific,70000,0,0,1,44,1,1,1,1,0,0,0,0,0,0,0,0,0
105,Pacific,70000,0,0,1,49,7,1,0,0,0,0,0,0,0,0,0,0,0
106,Pacific,70000,0,0,1,49,7,1,0,1,0,0,0,0,0,0,0,0,0
107,Pacific,90000,1,0,1,43,7,1,1,0,0,0,0,0,0,0,0,0,1
108,Pacific,70000,0,0,2,51,1,1,0,0,0,0,0,0,0,0,0,0,0
109,Pacific,70000,0,0,2,39,1,1,0,1,0,0,0,0,0,0,0,0,0
110,Pacific,60000,1,0,1,52,7,1,1,1,0,0,1,0,0,0,0,1,1
111,Pacific,60000,1,0,1,52,1,1,1,0,0,0,1,0,0,0,0,1,1
112,Pacific,60000,1,0,1,51,1,1,1,0,0,0,1,0,0,0,0,1,1
113,Pacific,70000,5,4,2,47,7,0,1,1,0,0,0,0,0,0,0,0,1
114,Pacific,70000,5,4,2,52,7,0,0,0,0,0,1,0,0,0,0,1,1
115,Pacific,70000,5,4,2,52,1,0,1,1,0,0,1,0,0,0,0,1,1
116,Pacific,70000,5,4,2,40,7,0,1,1,0,0,1,0,0,0,0,1,1
117,Pacific,70000,5,4,3,53,11,1,1,0,0,0,1,0,0,0,0,1,1
118,Pacific,80000,1,0,1,57,1,0,0,1,0,0,1,0,0,0,0,1,0
119,Pacific,30000,2,0,2,79,1,0,0,1,0,0,1,0,1,0,0,0,0
120,Pacific,40000,2,0,1,78,7,1,0,0,0,0,0,0,0,1,0,0,1
121,Pacific,70000,5,4,3,53,11,0,1,1,0,0,1,0,0,0,0,1,1
122,Pacific,70000,5,4,3,54,7,0,1,1,0,0,1,0,0,0,0,1,1
123,Pacific,70000,5,4,3,54,11,0,1,1,0,0,1,0,0,0,0,1,1
124,Pacific,80000,1,0,1,51,7,1,0,1,0,0,1,0,0,0,0,1,1
125,Pacific,70000,1,0,1,58,7,0,0,0,0,0,1,0,0,0,0,1,1
126,Pacific,10000,2,1,2,65,1,1,1,1,0,1,0,0,0,0,0,1,0
127,North America,40000,0,0,1,38,7,0,1,0,0,1,0,0,0,0,0,1,1
128,North America,40000,0,0,1,38,7,0,1,0,0,1,0,0,0,0,0,1,1
129,North America,40000,0,0,1,39,7,1,0,0,0,1,0,0,0,0,0,1,1
130,North America,30000,0,0,2,34,7,0,1,0,0,1,0,0,0,0,0,1,1
131,North America,30000,0,0,2,34,1,0,1,0,0,1,0,0,0,0,0,1,0
132,North America,30000,0,0,2,33,7,1,0,0,0,1,0,0,0,0,0,1,0
133,North America,30000,0,0,2,33,1,0,0,0,0,0,0,1,1,0,0,0,0
134,Pacific,10000,5,0,2,63,7,1,0,1,0,1,0,0,0,0,0,1,1
135,North America,30000,0,0,2,34,7,1,0,1,0,0,0,1,1,0,0,0,0
136,North America,40000,0,0,2,35,1,1,0,0,0,1,0,0,0,0,0,1,0
137,North America,40000,0,0,2,36,7,0,1,0,0,1,0,0,0,0,0,1,1
138,North America,40000,0,0,2,35,1,0,1,0,0,1,0,0,0,0,0,1,0
139,Pacific,30000,2,0,2,70,7,0,0,0,0,0,1,0,1,0,0,0,0
140,North America,30000,0,0,2,37,7,0,0,1,0,0,0,1,1,0,0,0,0
141,North America,40000,0,0,2,37,1,0,1,0,0,1,0,0,0,0,0,1,0
142,North America,40000,0,0,2,37,1,0,0,1,0,1,0,0,0,0,0,1,0
143,North America,40000,0,0,2,37,7,0,1,1,0,1,0,0,0,0,0,1,1
144,North America,40000,0,0,2,34,1,1,0,1,0,1,0,0,0,0,0,1,0
145,North America,40000,0,0,2,34,1,1,0,0,0,1,0,0,0,0,0,1,0
146,Pacific,40000,2,0,2,75,7,0,0,0,0,0,0,0,0,1,0,0,1
147,Pacific,60000,2,0,1,75,1,1,1,1,1,0,0,0,0,1,0,0,1
148,Pacific,40000,2,0,2,73,7,0,1,1,0,0,0,0,0,1,0,0,1
149,Pacific,40000,2,0,2,73,1,0,1,1,0,0,0,0,0,1,0,0,1
150,Pacific,40000,2,0,2,73,7,0,0,1,0,0,0,0,0,1,0,0,1
151,Pacific,60000,2,0,1,72,1,1,0,0,1,0,0,0,0,1,0,0,0
152,North America,40000,0,0,2,38,7,1,0,1,0,1,0,0,0,0,0,1,1
153,North America,40000,0,0,2,38,7,0,1,0,0,1,0,0,0,0,0,1,1
154,North America,40000,0,0,1,38,7,1,0,0,0,0,1,0,0,0,0,1,1
155,North America,40000,0,0,1,38,2,1,0,1,0,0,1,0,0,0,0,1,0
156,North America,40000,0,0,1,38,2,1,0,0,0,0,1,0,0,0,0,1,0
157,North America,40000,0,0,2,39,7,0,1,0,0,1,0,0,0,0,0,1,1
158,North America,40000,0,0,2,38,7,1,0,1,0,1,0,0,0,0,0,1,1
159,North America,40000,0,0,2,38,2,0,0,0,0,1,0,0,0,0,0,1,0
160,North America,40000,0,0,1,40,7,1,0,1,0,0,1,0,0,0,0,1,0
161,North America,40000,0,0,1,40,2,0,0,0,0,0,1,0,0,0,0,1,0
162,North America,40000,0,0,1,40,7,1,0,1,0,0,1,0,0,0,0,1,1
163,North America,40000,0,0,1,39,7,0,1,1,0,0,1,0,0,0,0,1,1
164,North America,40000,0,0,1,40,2,0,0,1,0,0,1,0,0,0,0,1,0
165,North America,60000,0,0,1,41,2,0,1,0,0,0,1,0,0,0,0,1,0
166,North America,70000,0,0,2,42,1,0,0,0,0,0,1,0,0,0,0,1,0
167,North America,80000,0,0,1,42,1,1,0,0,0,0,0,0,0,1,0,0,0
168,North America,80000,0,0,1,46,1,1,0,1,0,0,0,0,0,1,0,0,0
169,North America,90000,4,4,1,46,1,0,1,1,0,0,0,0,0,1,0,0,1
170,North America,90000,4,4,1,46,1,0,1,0,0,0,0,0,0,1,0,0,1
171,North America,100000,1,0,2,41,2,1,0,1,0,0,0,0,0,1,0,0,1
172,North America,100000,1,0,2,46,2,0,1,0,0,0,0,0,0,1,0,0,1
173,North America,110000,0,0,4,47,1,0,0,0,1,0,0,0,0,1,0,0,0
174,North America,110000,0,1,0,47,4,0,1,1,1,0,0,0,0,1,0,0,1
175,North America,70000,0,0,2,51,7,1,0,1,0,0,1,0,0,0,0,1,1
176,North America,90000,4,4,1,41,2,0,1,1,0,0,0,0,0,1,0,0,1
177,North America,110000,2,4,2,72,7,0,1,1,1,0,0,0,0,1,0,0,1
178,North America,100000,2,3,3,65,2,0,1,1,1,0,0,0,0,1,0,0,1
179,North America,120000,2,4,3,60,7,0,1,0,1,0,0,0,0,1,0,0,1
180,North America,160000,1,3,4,71,1,0,1,0,0,0,0,0,0,1,0,0,1
181,North America,170000,2,3,2,60,1,0,1,1,1,0,0,0,0,1,0,0,1
182,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0,1
183,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0,1
184,North America,70000,4,0,2,64,11,0,0,0,0,0,0,0,0,1,0,0,1
185,North America,70000,4,0,2,69,11,0,0,0,0,0,0,0,0,1,0,0,1
186,North America,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0,1
187,North America,60000,4,0,2,70,11,0,1,0,1,0,0,0,0,1,0,0,1
188,North America,60000,4,0,2,69,2,0,1,0,1,0,0,0,0,1,0,0,0
189,North America,60000,4,0,2,70,11,1,0,1,1,0,0,0,0,1,0,0,1
190,North America,70000,5,0,2,70,11,0,1,1,0,0,0,0,0,1,0,0,1
191,North America,70000,5,0,3,68,11,1,0,0,0,0,0,0,0,1,0,0,1
192,North America,60000,4,0,2,68,4,0,1,1,0,0,0,0,0,1,0,0,1
193,North America,60000,4,0,2,69,4,0,1,1,0,0,0,0,0,1,0,0,1
194,North America,60000,4,0,2,69,4,0,1,0,0,0,0,0,0,1,0,0,1
195,North America,60000,5,0,3,68,11,0,1,0,0,0,0,0,0,1,0,0,1
196,North America,60000,5,0,3,68,11,0,1,1,0,0,0,0,0,1,0,0,1
197,North America,70000,3,1,1,68,2,0,1,0,0,0,0,0,0,1,0,0,0
198,North America,70000,4,1,1,67,11,0,0,0,0,0,0,0,0,1,0,0,1
199,North America,70000,4,1,1,62,11,0,1,0,0,0,0,0,0,1,0,0,1
200,North America,70000,4,1,1,66,2,0,1,1,0,0,0,0,0,1,0,0,1
201,North America,70000,4,1,1,67,11,0,1,0,0,0,0,0,0,1,0,0,1
202,North America,80000,5,0,2,61,2,0,1,0,0,0,0,0,0,1,0,0,0
203,North America,40000,2,1,2,60,11,0,1,1,0,1,0,0,0,0,0,0,1
204,North America,40000,2,1,2,66,4,0,1,0,0,1,0,0,0,0,0,0,1
205,North America,40000,2,1,2,66,11,0,1,0,0,1,0,0,0,0,0,0,1
206,North America,60000,2,1,1,65,11,0,1,1,0,0,1,0,0,0,0,0,1
207,North America,60000,2,1,1,66,11,0,0,0,0,0,1,0,0,0,0,0,1
208,North America,60000,2,1,0,66,11,0,1,0,0,0,0,0,0,1,0,0,1
209,North America,60000,2,1,0,66,11,0,1,0,0,0,0,0,0,1,0,0,1
210,North America,70000,4,1,2,66,11,0,1,1,0,0,1,0,0,0,0,0,1
211,North America,40000,2,1,2,59,4,0,1,0,0,1,0,0,0,0,0,0,1
212,North America,40000,2,1,2,64,4,0,1,0,0,1,0,0,0,0,0,0,1
213,North America,60000,2,1,2,65,11,0,0,0,0,0,1,0,0,0,0,0,1
214,North America,60000,2,1,2,64,11,0,0,1,0,0,1,0,0,0,0,0,1
215,North America,40000,2,1,2,58,11,0,1,0,0,0,0,1,0,0,0,1,1
216,North America,60000,2,1,2,64,11,1,0,0,0,0,1,0,0,0,0,0,1
217,North America,60000,2,1,2,64,11,1,0,0,0,0,1,0,0,0,0,0,1
218,North America,60000,2,1,2,58,4,0,0,0,0,0,1,0,0,0,0,0,0
219,North America,60000,2,1,2,63,11,0,1,1,0,1,0,0,0,0,0,0,1
220,North America,60000,2,1,1,59,11,0,1,0,0,0,1,0,0,0,0,0,1
221,North America,70000,4,2,1,64,2,0,1,1,0,0,1,0,0,0,0,0,1
222,North America,80000,3,1,1,64,2,0,1,0,0,0,0,0,0,1,0,0,1
223,North America,70000,2,1,2,62,4,0,0,0,0,1,0,0,0,0,0,0,1
224,North America,70000,2,1,2,62,11,1,0,0,0,1,0,0,0,0,0,0,1
225,North America,60000,2,1,1,58,11,0,1,0,0,0,1,0,0,0,0,0,1
226,North America,60000,2,1,1,57,4,0,1,0,0,0,1,0,0,0,0,0,1
227,North America,60000,2,1,2,57,11,1,0,1,0,0,1,0,0,0,0,0,1
228,North America,60000,2,1,2,63,11,0,1,0,0,0,1,0,0,0,0,0,1
229,North America,70000,4,2,1,62,11,0,0,1,0,0,1,0,0,0,0,0,1
230,North America,70000,4,2,2,63,4,0,1,0,0,0,1,0,0,0,0,0,0
231,North America,60000,2,1,2,56,11,0,1,1,0,1,0,0,0,0,0,0,1
232,North America,60000,3,1,2,61,4,0,1,0,0,1,0,0,0,0,0,0,0
233,North America,70000,4,2,2,56,11,0,1,1,0,0,1,0,0,0,0,0,1
234,North America,70000,4,2,2,61,11,0,0,0,0,0,1,0,0,0,0,0,1
235,North America,70000,4,2,2,62,11,0,1,1,0,0,1,0,0,0,0,0,1
236,North America,70000,5,2,2,62,11,0,0,1,0,0,1,0,0,0,0,0,1
237,Europe,130000,2,3,4,55,1,1,0,1,0,0,0,0,0,1,0,0,0
238,Europe,130000,2,3,4,56,1,1,0,0,0,0,0,0,0,1,0,0,0
239,Europe,130000,2,4,2,50,7,1,1,0,0,0,1,0,0,0,0,0,0
240,Europe,160000,2,3,4,55,7,1,1,0,0,0,1,0,0,0,0,0,1
241,Europe,100000,2,3,4,45,7,1,0,0,0,0,1,0,0,0,0,0,1
242,Europe,110000,2,4,3,56,7,1,1,1,0,0,1,0,0,0,0,0,1
243,Europe,150000,2,3,3,56,1,1,1,0,0,0,1,0,0,0,0,0,1
244,Europe,170000,2,3,3,51,1,1,0,0,0,0,0,0,0,1,0,0,0
245,Europe,120000,3,4,4,57,7,1,1,1,0,1,0,0,0,0,0,0,0
246,Europe,120000,3,4,4,57,7,1,1,0,0,1,0,0,0,0,0,0,0
247,Europe,130000,3,4,3,58,1,1,0,0,0,0,1,0,0,0,0,0,0
248,Europe,110000,3,4,4,53,11,0,1,1,0,0,1,0,0,0,0,0,1
249,Europe,130000,3,4,3,53,1,1,1,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,North America,110000,5,3,1,50,7,0,1,1,0,0,0,0,0,1,0,0,1
18235,North America,120000,4,3,2,50,2,0,0,1,0,0,1,0,0,0,0,0,0
18236,North America,120000,4,3,3,51,7,1,0,1,0,0,1,0,0,0,0,0,1
18237,North America,120000,4,3,3,51,7,1,0,0,0,0,1,0,0,0,0,0,1
18238,North America,150000,4,1,3,51,2,1,0,1,0,0,1,0,0,0,0,0,0
18239,North America,150000,4,1,4,51,2,1,0,0,0,0,1,0,0,0,0,0,0
18240,North America,80000,5,4,3,52,1,0,0,0,0,0,1,0,0,0,0,0,0
18241,North America,90000,5,4,4,46,2,0,0,0,0,0,1,0,0,0,0,0,0
18242,North America,100000,3,2,4,51,7,1,1,1,0,0,1,0,0,0,0,0,1
18243,North America,110000,1,3,1,51,7,0,0,1,0,0,0,0,0,1,0,0,1
18244,North America,110000,1,3,2,52,7,0,0,1,0,0,0,0,0,1,0,0,1
18245,North America,130000,1,2,4,51,1,0,1,1,0,0,0,0,0,1,0,0,1
18246,North America,130000,1,2,4,52,4,0,0,1,0,0,0,0,0,1,0,0,0
18247,North America,70000,5,4,3,42,7,1,0,0,0,0,1,0,0,0,0,0,1
18248,North America,90000,4,3,2,53,7,0,0,1,0,1,0,0,0,0,0,0,1
18249,North America,90000,4,3,2,53,7,0,1,1,0,1,0,0,0,0,0,0,1
18250,North America,100000,3,2,4,47,2,0,0,1,0,0,1,0,0,0,0,0,0
18251,North America,110000,1,3,3,53,7,0,1,0,0,0,0,0,0,1,0,0,1
18252,North America,130000,1,3,3,52,1,1,1,1,0,0,0,0,0,1,0,0,1
18253,North America,130000,3,3,3,53,4,0,0,0,0,0,0,0,0,1,0,0,0
18254,North America,60000,2,0,2,58,7,1,1,0,0,1,0,0,0,0,0,0,1
18255,North America,80000,3,2,1,59,2,1,0,1,0,0,1,0,0,0,0,0,0
18256,North America,90000,2,1,1,58,11,1,1,1,0,1,0,0,0,0,0,0,0
18257,North America,90000,2,1,1,58,11,0,0,1,0,1,0,0,0,0,0,0,1
18258,North America,90000,2,1,1,58,11,1,1,0,0,1,0,0,0,0,0,0,1
18259,North America,70000,2,0,2,59,7,0,0,1,0,0,0,1,0,0,0,1,1
18260,North America,70000,4,0,2,79,2,0,0,1,1,0,0,0,0,1,0,0,0
18261,North America,130000,2,3,3,79,1,1,0,1,1,0,0,0,0,1,0,0,0
18262,North America,50000,2,0,2,78,2,0,0,0,1,0,0,0,0,1,0,0,0
18263,North America,70000,4,0,2,78,2,0,1,1,1,0,0,0,0,1,0,0,0
18264,North America,90000,4,0,2,78,2,1,1,0,0,0,0,0,0,1,0,0,0
18265,North America,90000,4,0,2,77,2,1,0,0,0,0,0,0,0,1,0,0,0
18266,North America,80000,5,4,3,54,2,0,0,1,0,0,1,0,0,0,0,0,0
18267,North America,80000,5,4,3,48,7,0,1,0,0,0,1,0,0,0,0,0,1
18268,North America,90000,4,3,3,54,7,0,1,1,0,1,0,0,0,0,0,0,1
18269,North America,90000,4,3,3,54,7,0,1,0,0,1,0,0,0,0,0,0,1
18270,North America,100000,0,3,1,54,7,0,1,1,0,0,1,0,0,0,0,0,1
18271,North America,100000,0,3,1,48,2,0,0,1,0,0,1,0,0,0,0,0,0
18272,North America,100000,0,3,2,54,7,0,1,1,0,0,1,0,0,0,0,0,1
18273,North America,100000,0,3,2,49,7,0,1,1,0,0,1,0,0,0,0,0,1
18274,North America,120000,5,4,3,54,7,1,0,1,0,1,0,0,0,0,0,0,1
18275,North America,70000,3,0,2,61,2,1,0,0,1,0,0,0,0,1,0,0,0
18276,North America,70000,3,0,2,61,7,1,1,0,1,0,0,0,0,1,0,0,1
18277,North America,70000,3,0,2,61,2,1,0,0,1,0,0,0,0,1,0,0,0
18278,North America,70000,3,0,2,55,7,1,0,0,1,0,0,0,0,1,0,0,1
18279,North America,70000,3,0,2,61,7,1,0,0,1,0,0,0,0,1,0,0,1
18280,North America,40000,3,0,2,52,2,1,0,0,0,0,1,0,0,0,0,0,0
18281,North America,40000,4,0,2,59,2,1,0,1,0,0,1,0,0,0,0,0,0
18282,North America,30000,4,0,2,64,7,0,1,0,0,1,0,0,0,0,0,0,1
18283,North America,30000,4,0,2,65,2,0,1,1,0,1,0,0,0,0,0,0,0
18284,North America,30000,4,0,2,64,2,0,0,0,0,1,0,0,0,0,0,0,0
18285,North America,40000,4,0,2,65,2,1,0,1,0,1,0,0,0,0,0,0,0
18286,Pacific,60000,3,3,2,44,1,0,0,1,0,0,0,0,0,0,0,0,0
18287,Pacific,60000,4,4,1,50,7,0,1,0,0,0,0,0,0,0,0,0,1
18288,Pacific,60000,4,4,2,38,1,0,1,1,0,0,0,0,0,0,0,0,0
18289,Pacific,70000,0,0,1,44,7,1,0,1,0,0,0,0,0,0,0,0,1
18290,Pacific,60000,5,5,2,50,1,0,0,1,0,0,0,0,0,0,0,0,0
18291,Pacific,60000,3,2,2,50,1,1,1,0,0,0,0,0,0,0,0,0,0
18292,Pacific,90000,2,2,0,42,1,1,0,0,0,0,0,0,0,0,0,0,0
18293,Pacific,90000,3,3,0,47,2,1,0,1,0,0,0,0,0,0,0,0,1
18294,Pacific,60000,1,0,1,53,1,1,0,0,0,0,1,0,0,0,0,1,0
18295,Pacific,110000,0,0,2,48,2,1,0,1,1,0,0,0,0,1,0,0,1
18296,Pacific,110000,0,0,3,47,2,0,0,0,1,0,0,0,0,1,0,0,0
18297,Pacific,60000,1,0,1,48,1,1,0,0,0,0,1,0,0,0,0,1,0
18298,Pacific,60000,1,0,1,54,7,1,0,0,0,0,1,0,0,0,0,1,1
18299,Pacific,60000,1,0,1,53,7,1,1,0,0,0,1,0,0,0,0,1,1
18300,Pacific,70000,0,0,1,48,7,1,0,1,0,0,0,0,0,0,0,0,0
18301,Pacific,80000,5,5,4,43,2,0,1,1,0,0,0,0,0,0,0,0,1
18302,Pacific,70000,0,0,1,50,7,0,0,0,0,0,0,0,0,0,0,0,0
18303,Pacific,70000,0,0,1,50,7,1,0,1,0,0,0,0,0,0,0,0,1
18304,Pacific,100000,5,0,1,55,11,0,1,1,0,0,0,0,0,0,0,0,1
18305,Pacific,100000,5,0,1,55,11,0,0,0,0,0,0,0,0,0,0,0,0
18306,Pacific,70000,0,0,1,45,1,1,0,1,0,0,0,0,0,0,0,0,0
18307,Pacific,70000,0,0,1,51,7,0,0,1,0,0,0,0,0,0,0,0,0
18308,Pacific,70000,0,0,2,40,1,1,0,1,0,0,0,0,0,0,0,0,0
18309,Pacific,70000,0,0,2,51,7,1,0,1,0,0,0,0,0,0,0,0,1
18310,Pacific,70000,0,0,2,50,7,1,0,1,0,0,0,0,0,0,0,0,0
18311,Pacific,60000,1,0,1,52,7,1,0,0,0,0,1,0,0,0,0,1,1
18312,Pacific,70000,5,4,2,46,7,0,0,0,0,0,1,0,0,0,0,1,1
18313,Pacific,60000,1,0,1,52,7,1,1,1,0,0,1,0,0,0,0,1,1
18314,Pacific,60000,1,0,1,47,7,1,1,0,0,0,1,0,0,0,0,1,1
18315,Pacific,90000,2,0,1,44,7,0,1,0,0,0,0,0,0,0,0,0,1
18316,Pacific,90000,2,0,1,55,4,1,0,1,0,0,0,0,0,0,0,0,0
18317,Pacific,90000,2,0,1,56,4,1,0,1,0,0,0,0,0,0,0,0,0
18318,Pacific,100000,4,0,2,55,2,1,1,1,0,0,0,0,0,1,0,0,1
18319,Pacific,70000,1,0,1,57,1,1,0,1,0,0,1,0,0,0,0,1,0
18320,Pacific,70000,5,4,3,49,7,0,1,1,0,0,1,0,0,0,0,1,0
18321,Pacific,70000,5,4,3,53,7,0,0,1,0,0,1,0,0,0,0,1,1
18322,North America,30000,0,0,2,38,7,0,0,1,0,1,0,0,0,0,0,1,1
18323,North America,40000,0,0,2,38,7,0,0,0,0,1,0,0,0,0,0,1,1
18324,North America,40000,0,0,2,38,7,0,1,0,0,1,0,0,0,0,0,1,1
18325,North America,40000,0,0,2,38,1,0,1,1,0,1,0,0,0,0,0,1,0
18326,North America,30000,0,0,2,34,1,1,0,0,0,1,0,0,0,0,0,1,0
18327,North America,30000,0,0,2,34,1,0,1,1,0,1,0,0,0,0,0,1,0
18328,North America,30000,0,0,2,34,7,0,1,1,0,1,0,0,0,0,0,1,1

In [21]:
region_dummies=pd.get_dummies(main_df.Region)
merged6=pd.concat([mergedfinal5,region_dummies],axis='columns')
mergedfinal6=merged6.drop(['Region','Pacific'],axis='columns')
mergedfinal6
#İlk M marital Status ikincisi Male

,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer,M,M,Graduate Degree,High School,Partial College,Partial High School,Clerical,Management,Manual,Skilled Manual,Yes,Europe,North America
0,90000,2,0,0,48,2,1,1,1,0,0,0,0,0,0,0,0,1,0,0
1,60000,3,3,1,43,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0
2,60000,3,3,1,49,4,1,1,1,0,0,0,0,0,0,0,0,1,0,0
3,70000,0,0,1,46,7,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,80000,5,5,4,40,2,1,0,0,0,0,0,0,0,0,0,0,1,0,0
5,70000,0,0,1,43,7,1,0,1,0,0,0,0,0,0,0,0,1,0,0
6,70000,0,0,1,43,7,1,0,0,0,0,0,0,0,0,0,0,1,0,0
7,60000,3,3,2,50,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0
8,60000,4,4,3,44,11,1,0,0,0,0,0,0,0,0,0,0,1,0,0
9,70000,0,0,1,50,7,1,0,1,0,0,0,0,0,0,0,0,0,0,0
10,70000,0,0,1,50,7,1,0,0,0,0,0,0,0,0,0,0,0,0,0
11,60000,4,4,4,50,11,1,1,1,0,0,0,0,0,0,0,0,1,0,0
12,100000,2,0,2,41,2,0,1,0,0,0,0,0,0,1,0,0,1,0,1
13,100000,2,0,3,40,1,0,1,1,0,0,0,0,0,1,0,0,1,0,1
14,100000,3,0,3,46,2,0,0,0,0,0,0,0,0,1,0,0,0,0,1
15,30000,0,0,1,35,7,1,0,0,0,0,1,0,0,0,0,1,0,0,1
16,30000,0,0,1,35,7,1,1,1,0,0,1,0,0,0,0,1,1,0,1
17,20000,4,0,2,70,7,1,0,0,0,1,0,0,0,0,0,1,1,0,0
18,30000,2,0,2,64,7,1,0,1,0,0,1,0,1,0,0,0,1,0,0
19,40000,0,0,2,36,7,0,0,1,0,1,0,0,0,0,0,1,0,0,1
20,40000,0,0,2,35,2,1,0,1,0,1,0,0,0,0,0,1,0,0,1
21,40000,0,0,1,35,2,1,0,0,0,0,1,0,0,0,0,1,0,0,1
22,40000,0,0,1,35,7,1,1,1,0,0,1,0,0,0,0,1,1,0,1
23,40000,0,0,1,35,2,0,1,1,0,0,1,0,0,0,0,1,1,0,1
24,60000,0,0,2,35,7,0,1,1,0,0,1,0,0,0,0,1,1,0,1
25,10000,2,1,2,68,2,1,1,1,0,0,0,1,1,0,0,0,1,0,0
26,30000,2,0,2,68,2,1,0,1,0,0,1,0,1,0,0,0,0,0,0
27,30000,2,0,2,67,7,1,1,1,0,0,1,0,1,0,0,0,1,0,0
28,30000,2,0,2,68,2,1,1,0,0,0,1,0,1,0,0,0,1,0,0
29,30000,2,0,2,67,2,1,1,1,0,0,1,0,1,0,0,0,1,0,0
30,10000,2,1,2,62,2,1,1,0,0,0,0,1,1,0,0,0,1,0,0
31,20000,4,0,2,67,2,1,1,0,0,1,0,0,0,0,0,1,1,0,0
32,20000,4,0,2,67,2,1,1,0,0,1,0,0,0,0,0,1,1,0,0
33,20000,4,0,2,61,7,1,1,1,0,1,0,0,0,0,0,1,1,0,0
34,20000,4,0,2,67,7,1,1,0,0,1,0,0,0,0,0,1,1,0,0
35,10000,2,1,2,66,2,1,1,0,0,0,0,1,1,0,0,0,1,0,0
36,60000,0,0,2,35,2,1,1,0,0,0,1,0,0,0,0,1,1,0,1
37,40000,0,0,2,36,7,1,0,0,0,0,0,1,1,0,0,0,0,0,1
38,10000,2,1,2,66,7,1,1,0,0,0,0,1,1,0,0,0,1,0,0
39,30000,3,0,2,65,7,1,1,1,0,0,1,0,1,0,0,0,1,0,0
40,30000,0,0,2,37,2,1,1,1,0,0,1,0,0,0,0,1,1,0,1
41,60000,0,0,2,36,2,1,1,0,0,0,1,0,0,0,0,1,1,0,1
42,70000,0,0,2,37,1,1,1,0,0,0,1,0,0,0,0,1,1,0,1
43,60000,0,0,2,38,7,0,1,1,0,0,1,0,0,0,0,1,1,0,1
44,20000,2,1,2,65,2,1,1,1,0,0,0,1,1,0,0,0,1,0,0
45,30000,3,0,2,64,2,0,0,1,0,1,0,0,0,0,0,1,0,0,0
46,30000,3,0,2,64,7,1,1,0,0,1,0,0,0,0,0,1,1,0,0
47,30000,3,0,2,64,2,1,1,0,0,1,0,0,0,0,0,1,0,0,0
48,30000,3,0,2,63,7,1,1,1,0,1,0,0,0,0,0,1,1,0,0
49,40000,0,0,2,34,7,0,0,0,0,0,0,1,1,0,0,0,1,0,1
50,30000,3,0,2,62,7,1,1,1,0,1,0,0,0,0,0,1,1,0,0
51,30000,3,0,2,63,2,0,0,1,0,1,0,0,0,0,0,1,0,0,0
52,40000,2,0,2,63,7,1,0,0,0,0,1,0,1,0,0,0,0,0,0
53,60000,0,0,2,34,2,1,1,0,0,0,1,0,0,0,0,1,0,0,1
54,40000,2,0,2,62,7,1,1,0,0,0,1,0,0,0,0,1,1,0,0
55,40000,2,0,2,62,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
56,40000,3,0,2,61,7,1,1,0,0,0,1,0,0,0,0,1,1,0,0
57,70000,2,0,2,49,2,1,1,1,1,0,0,0,0,1,0,0,1,0,0
58,80000,2,0,2,54,2,1,1,1,0,0,1,0,0,0,0,1,1,0,0
59,80000,2,0,2,60,7,0,0,0,0,0,1,0,0,0,0,1,1,0,0
60,80000,2,0,2,60,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
61,80000,2,0,2,44,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
62,40000,0,0,2,39,7,1,1,1,0,1,0,0,0,0,0,1,1,0,1
63,40000,0,0,2,39,7,1,0,0,0,1,0,0,0,0,0,1,1,0,1
64,40000,0,0,2,38,7,1,1,1,0,1,0,0,0,0,0,1,1,0,1
65,60000,0,0,2,40,2,0,1,0,0,0,1,0,0,0,0,1,0,0,1
66,70000,0,0,2,40,7,0,1,0,0,0,1,0,0,0,0,0,1,0,1
67,60000,0,0,2,37,7,0,0,1,0,0,1,0,0,0,0,0,1,0,1
68,80000,2,0,2,53,7,0,0,0,0,1,0,0,0,0,0,1,1,0,0
69,80000,2,0,2,53,2,1,0,0,0,1,0,0,0,0,0,1,0,0,0
70,80000,2,0,2,59,7,1,1,1,0,1,0,0,0,0,0,1,1,0,0
71,80000,2,0,2,59,7,0,0,0,0,1,0,0,0,0,0,1,1,0,0
72,80000,2,0,2,59,2,1,0,0,0,1,0,0,0,0,0,1,0,0,0
73,70000,2,0,2,58,7,0,0,0,0,1,0,0,0,0,0,1,1,0,0
74,70000,2,0,2,58,7,0,0,1,0,1,0,0,0,0,0,1,1,0,0
75,80000,2,0,2,56,7,1,0,0,0,1,0,0,0,0,0,0,1,0,0
76,80000,2,0,2,57,7,1,0,1,0,1,0,0,0,0,0,0,1,0,0
77,80000,2,0,2,56,2,1,0,0,0,1,0,0,0,0,0,0,0,0,0
78,40000,0,0,2,35,2,0,0,0,0,1,0,0,0,0,0,0,0,0,1
79,160000,0,0,2,49,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0
80,170000,0,0,2,55,1,1,1,1,1,0,0,0,0,1,0,0,1,0,0
81,120000,2,2,3,48,4,0,1,0,0,0,0,0,0,1,0,0,1,0,1
82,130000,0,1,3,48,2,1,0,0,1,0,0,0,0,1,0,0,0,0,1
83,130000,0,1,3,42,2,1,1,0,1,0,0,0,0,1,0,0,1,0,1
84,80000,2,0,2,56,2,1,0,1,0,0,0,1,0,0,0,1,0,0,1
85,60000,2,0,2,57,7,0,0,0,0,1,0,0,0,0,0,0,0,0,1
86,70000,2,1,0,56,1,0,1,1,0,0,1,0,0,0,0,0,1,0,1
87,70000,3,2,0,56,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1
88,80000,2,1,0,56,4,1,1,1,0,0,0,0,0,1,0,0,1,0,1
89,80000,2,1,1,57,4,1,0,0,0,0,0,0,0,1,0,0,1,0,1
90,90000,2,0,1,51,4,1,0,1,0,0,1,0,0,0,0,0,1,0,1
91,90000,2,0,1,57,7,0,1,1,0,0,1,0,0,0,0,0,1,0,1
92,90000,2,2,0,47,2,1,1,0,0,0,0,0,0,0,0,0,1,0,0
93,100000,0,0,0,41,1,1,1,0,1,0,0,0,0,1,0,0,1,0,0
94,70000,1,0,1,52,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0
95,70000,1,0,1,52,7,1,0,1,0,0,1,0,0,0,0,1,1,0,0
96,60000,1,0,1,52,7,1,1,1,0,0,0,0,0,0,0,0,1,0,0
97,60000,1,0,1,47,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
98,60000,1,0,1,53,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0
99,60000,1,0,1,53,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0
100,60000,1,0,1,53,7,1,0,0,0,0,1,0,0,0,0,1,1,0,0
101,70000,0,0,1,49,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
102,80000,5,5,4,49,2,0,0,0,0,0,0,0,0,0,0,0,1,0,0
103,70000,0,0,1,38,7,1,0,0,0,0,0,0,0,0,0,0,1,0,0
104,70000,0,0,1,44,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0
105,70000,0,0,1,49,7,1,0,0,0,0,0,0,0,0,0,0,0,0,0
106,70000,0,0,1,49,7,1,0,1,0,0,0,0,0,0,0,0,0,0,0
107,90000,1,0,1,43,7,1,1,0,0,0,0,0,0,0,0,0,1,0,0
108,70000,0,0,2,51,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
109,70000,0,0,2,39,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0
110,60000,1,0,1,52,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
111,60000,1,0,1,52,1,1,1,0,0,0,1,0,0,0,0,1,1,0,0
112,60000,1,0,1,51,1,1,1,0,0,0,1,0,0,0,0,1,1,0,0
113,70000,5,4,2,47,7,0,1,1,0,0,0,0,0,0,0,0,1,0,0
114,70000,5,4,2,52,7,0,0,0,0,0,1,0,0,0,0,1,1,0,0
115,70000,5,4,2,52,1,0,1,1,0,0,1,0,0,0,0,1,1,0,0
116,70000,5,4,2,40,7,0,1,1,0,0,1,0,0,0,0,1,1,0,0
117,70000,5,4,3,53,11,1,1,0,0,0,1,0,0,0,0,1,1,0,0
118,80000,1,0,1,57,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0
119,30000,2,0,2,79,1,0,0,1,0,0,1,0,1,0,0,0,0,0,0
120,40000,2,0,1,78,7,1,0,0,0,0,0,0,0,1,0,0,1,0,0
121,70000,5,4,3,53,11,0,1,1,0,0,1,0,0,0,0,1,1,0,0
122,70000,5,4,3,54,7,0,1,1,0,0,1,0,0,0,0,1,1,0,0
123,70000,5,4,3,54,11,0,1,1,0,0,1,0,0,0,0,1,1,0,0
124,80000,1,0,1,51,7,1,0,1,0,0,1,0,0,0,0,1,1,0,0
125,70000,1,0,1,58,7,0,0,0,0,0,1,0,0,0,0,1,1,0,0
126,10000,2,1,2,65,1,1,1,1,0,1,0,0,0,0,0,1,0,0,0
127,40000,0,0,1,38,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
128,40000,0,0,1,38,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
129,40000,0,0,1,39,7,1,0,0,0,1,0,0,0,0,0,1,1,0,1
130,30000,0,0,2,34,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
131,30000,0,0,2,34,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1
132,30000,0,0,2,33,7,1,0,0,0,1,0,0,0,0,0,1,0,0,1
133,30000,0,0,2,33,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1
134,10000,5,0,2,63,7,1,0,1,0,1,0,0,0,0,0,1,1,0,0
135,30000,0,0,2,34,7,1,0,1,0,0,0,1,1,0,0,0,0,0,1
136,40000,0,0,2,35,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1
137,40000,0,0,2,36,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
138,40000,0,0,2,35,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1
139,30000,2,0,2,70,7,0,0,0,0,0,1,0,1,0,0,0,0,0,0
140,30000,0,0,2,37,7,0,0,1,0,0,0,1,1,0,0,0,0,0,1
141,40000,0,0,2,37,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1
142,40000,0,0,2,37,1,0,0,1,0,1,0,0,0,0,0,1,0,0,1
143,40000,0,0,2,37,7,0,1,1,0,1,0,0,0,0,0,1,1,0,1
144,40000,0,0,2,34,1,1,0,1,0,1,0,0,0,0,0,1,0,0,1
145,40000,0,0,2,34,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1
146,40000,2,0,2,75,7,0,0,0,0,0,0,0,0,1,0,0,1,0,0
147,60000,2,0,1,75,1,1,1,1,1,0,0,0,0,1,0,0,1,0,0
148,40000,2,0,2,73,7,0,1,1,0,0,0,0,0,1,0,0,1,0,0
149,40000,2,0,2,73,1,0,1,1,0,0,0,0,0,1,0,0,1,0,0
150,40000,2,0,2,73,7,0,0,1,0,0,0,0,0,1,0,0,1,0,0
151,60000,2,0,1,72,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0
152,40000,0,0,2,38,7,1,0,1,0,1,0,0,0,0,0,1,1,0,1
153,40000,0,0,2,38,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
154,40000,0,0,1,38,7,1,0,0,0,0,1,0,0,0,0,1,1,0,1
155,40000,0,0,1,38,2,1,0,1,0,0,1,0,0,0,0,1,0,0,1
156,40000,0,0,1,38,2,1,0,0,0,0,1,0,0,0,0,1,0,0,1
157,40000,0,0,2,39,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
158,40000,0,0,2,38,7,1,0,1,0,1,0,0,0,0,0,1,1,0,1
159,40000,0,0,2,38,2,0,0,0,0,1,0,0,0,0,0,1,0,0,1
160,40000,0,0,1,40,7,1,0,1,0,0,1,0,0,0,0,1,0,0,1
161,40000,0,0,1,40,2,0,0,0,0,0,1,0,0,0,0,1,0,0,1
162,40000,0,0,1,40,7,1,0,1,0,0,1,0,0,0,0,1,1,0,1
163,40000,0,0,1,39,7,0,1,1,0,0,1,0,0,0,0,1,1,0,1
164,40000,0,0,1,40,2,0,0,1,0,0,1,0,0,0,0,1,0,0,1
165,60000,0,0,1,41,2,0,1,0,0,0,1,0,0,0,0,1,0,0,1
166,70000,0,0,2,42,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1
167,80000,0,0,1,42,1,1,0,0,0,0,0,0,0,1,0,0,0,0,1
168,80000,0,0,1,46,1,1,0,1,0,0,0,0,0,1,0,0,0,0,1
169,90000,4,4,1,46,1,0,1,1,0,0,0,0,0,1,0,0,1,0,1
170,90000,4,4,1,46,1,0,1,0,0,0,0,0,0,1,0,0,1,0,1
171,100000,1,0,2,41,2,1,0,1,0,0,0,0,0,1,0,0,1,0,1
172,100000,1,0,2,46,2,0,1,0,0,0,0,0,0,1,0,0,1,0,1
173,110000,0,0,4,47,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1
174,110000,0,1,0,47,4,0,1,1,1,0,0,0,0,1,0,0,1,0,1
175,70000,0,0,2,51,7,1,0,1,0,0,1,0,0,0,0,1,1,0,1
176,90000,4,4,1,41,2,0,1,1,0,0,0,0,0,1,0,0,1,0,1
177,110000,2,4,2,72,7,0,1,1,1,0,0,0,0,1,0,0,1,0,1
178,100000,2,3,3,65,2,0,1,1,1,0,0,0,0,1,0,0,1,0,1
179,120000,2,4,3,60,7,0,1,0,1,0,0,0,0,1,0,0,1,0,1
180,160000,1,3,4,71,1,0,1,0,0,0,0,0,0,1,0,0,1,0,1
181,170000,2,3,2,60,1,0,1,1,1,0,0,0,0,1,0,0,1,0,1
182,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
183,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
184,70000,4,0,2,64,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
185,70000,4,0,2,69,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
186,70000,4,0,2,70,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
187,60000,4,0,2,70,11,0,1,0,1,0,0,0,0,1,0,0,1,0,1
188,60000,4,0,2,69,2,0,1,0,1,0,0,0,0,1,0,0,0,0,1
189,60000,4,0,2,70,11,1,0,1,1,0,0,0,0,1,0,0,1,0,1
190,70000,5,0,2,70,11,0,1,1,0,0,0,0,0,1,0,0,1,0,1
191,70000,5,0,3,68,11,1,0,0,0,0,0,0,0,1,0,0,1,0,1
192,60000,4,0,2,68,4,0,1,1,0,0,0,0,0,1,0,0,1,0,1
193,60000,4,0,2,69,4,0,1,1,0,0,0,0,0,1,0,0,1,0,1
194,60000,4,0,2,69,4,0,1,0,0,0,0,0,0,1,0,0,1,0,1
195,60000,5,0,3,68,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
196,60000,5,0,3,68,11,0,1,1,0,0,0,0,0,1,0,0,1,0,1
197,70000,3,1,1,68,2,0,1,0,0,0,0,0,0,1,0,0,0,0,1
198,70000,4,1,1,67,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
199,70000,4,1,1,62,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
200,70000,4,1,1,66,2,0,1,1,0,0,0,0,0,1,0,0,1,0,1
201,70000,4,1,1,67,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
202,80000,5,0,2,61,2,0,1,0,0,0,0,0,0,1,0,0,0,0,1
203,40000,2,1,2,60,11,0,1,1,0,1,0,0,0,0,0,0,1,0,1
204,40000,2,1,2,66,4,0,1,0,0,1,0,0,0,0,0,0,1,0,1
205,40000,2,1,2,66,11,0,1,0,0,1,0,0,0,0,0,0,1,0,1
206,60000,2,1,1,65,11,0,1,1,0,0,1,0,0,0,0,0,1,0,1
207,60000,2,1,1,66,11,0,0,0,0,0,1,0,0,0,0,0,1,0,1
208,60000,2,1,0,66,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
209,60000,2,1,0,66,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
210,70000,4,1,2,66,11,0,1,1,0,0,1,0,0,0,0,0,1,0,1
211,40000,2,1,2,59,4,0,1,0,0,1,0,0,0,0,0,0,1,0,1
212,40000,2,1,2,64,4,0,1,0,0,1,0,0,0,0,0,0,1,0,1
213,60000,2,1,2,65,11,0,0,0,0,0,1,0,0,0,0,0,1,0,1
214,60000,2,1,2,64,11,0,0,1,0,0,1,0,0,0,0,0,1,0,1
215,40000,2,1,2,58,11,0,1,0,0,0,0,1,0,0,0,1,1,0,1
216,60000,2,1,2,64,11,1,0,0,0,0,1,0,0,0,0,0,1,0,1
217,60000,2,1,2,64,11,1,0,0,0,0,1,0,0,0,0,0,1,0,1
218,60000,2,1,2,58,4,0,0,0,0,0,1,0,0,0,0,0,0,0,1
219,60000,2,1,2,63,11,0,1,1,0,1,0,0,0,0,0,0,1,0,1
220,60000,2,1,1,59,11,0,1,0,0,0,1,0,0,0,0,0,1,0,1
221,70000,4,2,1,64,2,0,1,1,0,0,1,0,0,0,0,0,1,0,1
222,80000,3,1,1,64,2,0,1,0,0,0,0,0,0,1,0,0,1,0,1
223,70000,2,1,2,62,4,0,0,0,0,1,0,0,0,0,0,0,1,0,1
224,70000,2,1,2,62,11,1,0,0,0,1,0,0,0,0,0,0,1,0,1
225,60000,2,1,1,58,11,0,1,0,0,0,1,0,0,0,0,0,1,0,1
226,60000,2,1,1,57,4,0,1,0,0,0,1,0,0,0,0,0,1,0,1
227,60000,2,1,2,57,11,1,0,1,0,0,1,0,0,0,0,0,1,0,1
228,60000,2,1,2,63,11,0,1,0,0,0,1,0,0,0,0,0,1,0,1
229,70000,4,2,1,62,11,0,0,1,0,0,1,0,0,0,0,0,1,0,1
230,70000,4,2,2,63,4,0,1,0,0,0,1,0,0,0,0,0,0,0,1
231,60000,2,1,2,56,11,0,1,1,0,1,0,0,0,0,0,0,1,0,1
232,60000,3,1,2,61,4,0,1,0,0,1,0,0,0,0,0,0,0,0,1
233,70000,4,2,2,56,11,0,1,1,0,0,1,0,0,0,0,0,1,0,1
234,70000,4,2,2,61,11,0,0,0,0,0,1,0,0,0,0,0,1,0,1
235,70000,4,2,2,62,11,0,1,1,0,0,1,0,0,0,0,0,1,0,1
236,70000,5,2,2,62,11,0,0,1,0,0,1,0,0,0,0,0,1,0,1
237,130000,2,3,4,55,1,1,0,1,0,0,0,0,0,1,0,0,0,1,0
238,130000,2,3,4,56,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0
239,130000,2,4,2,50,7,1,1,0,0,0,1,0,0,0,0,0,0,1,0
240,160000,2,3,4,55,7,1,1,0,0,0,1,0,0,0,0,0,1,1,0
241,100000,2,3,4,45,7,1,0,0,0,0,1,0,0,0,0,0,1,1,0
242,110000,2,4,3,56,7,1,1,1,0,0,1,0,0,0,0,0,1,1,0
243,150000,2,3,3,56,1,1,1,0,0,0,1,0,0,0,0,0,1,1,0
244,170000,2,3,3,51,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0
245,120000,3,4,4,57,7,1,1,1,0,1,0,0,0,0,0,0,0,1,0
246,120000,3,4,4,57,7,1,1,0,0,1,0,0,0,0,0,0,0,1,0
247,130000,3,4,3,58,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0
248,110000,3,4,4,53,11,0,1,1,0,0,1,0,0,0,0,0,1,1,0
249,130000,3,4,3,53,1,1,1,0,0,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,110000,5,3,1,50,7,0,1,1,0,0,0,0,0,1,0,0,1,0,1
18235,120000,4,3,2,50,2,0,0,1,0,0,1,0,0,0,0,0,0,0,1
18236,120000,4,3,3,51,7,1,0,1,0,0,1,0,0,0,0,0,1,0,1
18237,120000,4,3,3,51,7,1,0,0,0,0,1,0,0,0,0,0,1,0,1
18238,150000,4,1,3,51,2,1,0,1,0,0,1,0,0,0,0,0,0,0,1
18239,150000,4,1,4,51,2,1,0,0,0,0,1,0,0,0,0,0,0,0,1
18240,80000,5,4,3,52,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
18241,90000,5,4,4,46,2,0,0,0,0,0,1,0,0,0,0,0,0,0,1
18242,100000,3,2,4,51,7,1,1,1,0,0,1,0,0,0,0,0,1,0,1
18243,110000,1,3,1,51,7,0,0,1,0,0,0,0,0,1,0,0,1,0,1
18244,110000,1,3,2,52,7,0,0,1,0,0,0,0,0,1,0,0,1,0,1
18245,130000,1,2,4,51,1,0,1,1,0,0,0,0,0,1,0,0,1,0,1
18246,130000,1,2,4,52,4,0,0,1,0,0,0,0,0,1,0,0,0,0,1
18247,70000,5,4,3,42,7,1,0,0,0,0,1,0,0,0,0,0,1,0,1
18248,90000,4,3,2,53,7,0,0,1,0,1,0,0,0,0,0,0,1,0,1
18249,90000,4,3,2,53,7,0,1,1,0,1,0,0,0,0,0,0,1,0,1
18250,100000,3,2,4,47,2,0,0,1,0,0,1,0,0,0,0,0,0,0,1
18251,110000,1,3,3,53,7,0,1,0,0,0,0,0,0,1,0,0,1,0,1
18252,130000,1,3,3,52,1,1,1,1,0,0,0,0,0,1,0,0,1,0,1
18253,130000,3,3,3,53,4,0,0,0,0,0,0,0,0,1,0,0,0,0,1
18254,60000,2,0,2,58,7,1,1,0,0,1,0,0,0,0,0,0,1,0,1
18255,80000,3,2,1,59,2,1,0,1,0,0,1,0,0,0,0,0,0,0,1
18256,90000,2,1,1,58,11,1,1,1,0,1,0,0,0,0,0,0,0,0,1
18257,90000,2,1,1,58,11,0,0,1,0,1,0,0,0,0,0,0,1,0,1
18258,90000,2,1,1,58,11,1,1,0,0,1,0,0,0,0,0,0,1,0,1
18259,70000,2,0,2,59,7,0,0,1,0,0,0,1,0,0,0,1,1,0,1
18260,70000,4,0,2,79,2,0,0,1,1,0,0,0,0,1,0,0,0,0,1
18261,130000,2,3,3,79,1,1,0,1,1,0,0,0,0,1,0,0,0,0,1
18262,50000,2,0,2,78,2,0,0,0,1,0,0,0,0,1,0,0,0,0,1
18263,70000,4,0,2,78,2,0,1,1,1,0,0,0,0,1,0,0,0,0,1
18264,90000,4,0,2,78,2,1,1,0,0,0,0,0,0,1,0,0,0,0,1
18265,90000,4,0,2,77,2,1,0,0,0,0,0,0,0,1,0,0,0,0,1
18266,80000,5,4,3,54,2,0,0,1,0,0,1,0,0,0,0,0,0,0,1
18267,80000,5,4,3,48,7,0,1,0,0,0,1,0,0,0,0,0,1,0,1
18268,90000,4,3,3,54,7,0,1,1,0,1,0,0,0,0,0,0,1,0,1
18269,90000,4,3,3,54,7,0,1,0,0,1,0,0,0,0,0,0,1,0,1
18270,100000,0,3,1,54,7,0,1,1,0,0,1,0,0,0,0,0,1,0,1
18271,100000,0,3,1,48,2,0,0,1,0,0,1,0,0,0,0,0,0,0,1
18272,100000,0,3,2,54,7,0,1,1,0,0,1,0,0,0,0,0,1,0,1
18273,100000,0,3,2,49,7,0,1,1,0,0,1,0,0,0,0,0,1,0,1
18274,120000,5,4,3,54,7,1,0,1,0,1,0,0,0,0,0,0,1,0,1
18275,70000,3,0,2,61,2,1,0,0,1,0,0,0,0,1,0,0,0,0,1
18276,70000,3,0,2,61,7,1,1,0,1,0,0,0,0,1,0,0,1,0,1
18277,70000,3,0,2,61,2,1,0,0,1,0,0,0,0,1,0,0,0,0,1
18278,70000,3,0,2,55,7,1,0,0,1,0,0,0,0,1,0,0,1,0,1
18279,70000,3,0,2,61,7,1,0,0,1,0,0,0,0,1,0,0,1,0,1
18280,40000,3,0,2,52,2,1,0,0,0,0,1,0,0,0,0,0,0,0,1
18281,40000,4,0,2,59,2,1,0,1,0,0,1,0,0,0,0,0,0,0,1
18282,30000,4,0,2,64,7,0,1,0,0,1,0,0,0,0,0,0,1,0,1
18283,30000,4,0,2,65,2,0,1,1,0,1,0,0,0,0,0,0,0,0,1
18284,30000,4,0,2,64,2,0,0,0,0,1,0,0,0,0,0,0,0,0,1
18285,40000,4,0,2,65,2,1,0,1,0,1,0,0,0,0,0,0,0,0,1
18286,60000,3,3,2,44,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
18287,60000,4,4,1,50,7,0,1,0,0,0,0,0,0,0,0,0,1,0,0
18288,60000,4,4,2,38,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0
18289,70000,0,0,1,44,7,1,0,1,0,0,0,0,0,0,0,0,1,0,0
18290,60000,5,5,2,50,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
18291,60000,3,2,2,50,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0
18292,90000,2,2,0,42,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
18293,90000,3,3,0,47,2,1,0,1,0,0,0,0,0,0,0,0,1,0,0
18294,60000,1,0,1,53,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0
18295,110000,0,0,2,48,2,1,0,1,1,0,0,0,0,1,0,0,1,0,0
18296,110000,0,0,3,47,2,0,0,0,1,0,0,0,0,1,0,0,0,0,0
18297,60000,1,0,1,48,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0
18298,60000,1,0,1,54,7,1,0,0,0,0,1,0,0,0,0,1,1,0,0
18299,60000,1,0,1,53,7,1,1,0,0,0,1,0,0,0,0,1,1,0,0
18300,70000,0,0,1,48,7,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18301,80000,5,5,4,43,2,0,1,1,0,0,0,0,0,0,0,0,1,0,0
18302,70000,0,0,1,50,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18303,70000,0,0,1,50,7,1,0,1,0,0,0,0,0,0,0,0,1,0,0
18304,100000,5,0,1,55,11,0,1,1,0,0,0,0,0,0,0,0,1,0,0
18305,100000,5,0,1,55,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18306,70000,0,0,1,45,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18307,70000,0,0,1,51,7,0,0,1,0,0,0,0,0,0,0,0,0,0,0
18308,70000,0,0,2,40,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18309,70000,0,0,2,51,7,1,0,1,0,0,0,0,0,0,0,0,1,0,0
18310,70000,0,0,2,50,7,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18311,60000,1,0,1,52,7,1,0,0,0,0,1,0,0,0,0,1,1,0,0
18312,70000,5,4,2,46,7,0,0,0,0,0,1,0,0,0,0,1,1,0,0
18313,60000,1,0,1,52,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
18314,60000,1,0,1,47,7,1,1,0,0,0,1,0,0,0,0,1,1,0,0
18315,90000,2,0,1,44,7,0,1,0,0,0,0,0,0,0,0,0,1,0,0
18316,90000,2,0,1,55,4,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18317,90000,2,0,1,56,4,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18318,100000,4,0,2,55,2,1,1,1,0,0,0,0,0,1,0,0,1,0,0
18319,70000,1,0,1,57,1,1,0,1,0,0,1,0,0,0,0,1,0,0,0
18320,70000,5,4,3,49,7,0,1,1,0,0,1,0,0,0,0,1,0,0,0
18321,70000,5,4,3,53,7,0,0,1,0,0,1,0,0,0,0,1,1,0,0
18322,30000,0,0,2,38,7,0,0,1,0,1,0,0,0,0,0,1,1,0,1
18323,40000,0,0,2,38,7,0,0,0,0,1,0,0,0,0,0,1,1,0,1
18324,40000,0,0,2,38,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
18325,40000,0,0,2,38,1,0,1,1,0,1,0,0,0,0,0,1,0,0,1
18326,30000,0,0,2,34,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1
18327,30000,0,0,2,34,1,0,1,1,0,1,0,0,0,0,0,1,0,0,1
18328,30000,0,0,2,34,7,0,1,1,0,1,0,0,0,0,0,1,1,0,1
18329,30000,0,0,2,35,7,0,0,1,0,1,0,0,0,0,0,1,1,0,1
18330,40000,0,0,2,34,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
18331,30000,2,0,2,71,1,0,1,1,0,0,1,0,1,0,0,0,0,0,0
18332,30000,2,0,2,77,7,0,0,0,0,0,1,0,1,0,0,0,0,0,0
18333,40000,2,0,2,76,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
18334,30000,0,0,2,35,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1
18335,30000,0,0,2,36,1,1,0,1,0,0,0,1,1,0,0,0,0,0,1
18336,40000,0,0,2,36,1,1,0,1,0,1,0,0,0,0,0,1,0,0,1
18337,30000,2,0,2,76,7,0,0,1,0,0,1,0,1,0,0,0,1,0,0
18338,40000,2,0,2,76,7,0,1,0,0,0,0,0,0,1,0,0,1,0,0
18339,30000,0,0,2,34,7,0,0,1,0,0,0,1,1,0,0,0,0,0,1
18340,30000,0,0,2,34,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1
18341,30000,0,0,2,35,7,0,0,1,0,0,0,1,1,0,0,0,0,0,1
18342,30000,2,0,2,74,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0
18343,40000,2,0,2,74,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0
18344,40000,2,0,2,71,7,1,0,1,0,0,0,0,0,1,0,0,1,0,0
18345,40000,2,0,2,61,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0
18346,50000,2,0,1,72,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0
18347,40000,0,0,1,43,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1
18348,50000,3,3,1,49,4,0,1,1,0,0,0,0,0,0,0,1,1,0,1
18349,50000,3,3,2,43,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1
18350,50000,3,3,2,48,4,1,0,0,0,0,0,0,0,0,0,1,1,0,1
18351,50000,3,3,2,49,1,0,0,1,0,0,0,0,0,0,0,1,0,0,1
18352,50000,3,3,3,49,11,1,0,0,0,0,0,0,0,0,0,1,0,0,1
18353,50000,3,3,3,38,11,0,1,1,0,0,0,0,0,0,0,1,1,0,1
18354,60000,0,0,0,48,4,1,0,1,1,0,0,0,0,0,0,0,1,0,1
18355,40000,0,0,0,45,1,1,1,0,1,0,0,0,1,0,0,0,1,1,0
18356,40000,0,0,0,46,1,1,1,1,1,0,0,0,1,0,0,0,1,1,0
18357,40000,0,0,0,40,1,1,0,1,1,0,0,0,1,0,0,0,0,1,0
18358,40000,0,0,0,46,1,1,1,0,1,0,0,0,1,0,0,0,0,1,0
18359,40000,0,0,0,45,1,1,1,1,1,0,0,0,1,0,0,0,0,1,0
18360,40000,0,0,0,40,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18361,20000,1,1,1,47,4,1,0,0,0,0,1,0,0,0,1,0,0,1,0
18362,20000,1,1,1,46,4,1,0,1,0,0,1,0,0,0,1,0,1,1,0
18363,20000,1,1,1,46,4,1,0,0,0,0,1,0,0,0,1,0,1,1,0
18364,10000,4,4,1,48,1,1,1,1,0,0,0,1,0,0,1,0,1,1,0
18365,20000,1,1,1,48,4,1,0,0,0,1,0,0,0,0,1,0,1,1,0
18366,40000,0,0,0,47,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18367,40000,0,0,0,36,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18368,40000,0,0,0,47,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18369,40000,0,0,0,35,1,1,0,1,0,0,0,0,0,0,0,0,1,1,0
18370,30000,1,0,1,86,4,0,0,1,0,0,0,0,1,0,0,0,0,1,0
18371,20000,2,2,0,47,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0
18372,30000,1,1,2,47,1,0,1,0,0,0,0,0,0,0,0,1,1,1,0
18373,30000,1,1,2,48,1,0,1,1,0,0,0,0,0,0,0,1,1,1,0
18374,20000,2,2,1,49,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0
18375,20000,2,2,1,48,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0
18376,20000,2,2,2,48,1,0,0,1,0,1,0,0,0,0,1,0,1,1,0
18377,30000,1,1,2,49,1,0,1,0,0,0,0,0,0,0,0,1,1,1,0
18378,30000,1,1,2,49,1,0,1,1,0,0,0,0,0,0,0,1,0,1,0

-------

### TRAIN/TEST SPLIT YÖNTEMİ

In [25]:
X=mergedfinal6.drop('BikeBuyer',axis=1)
y=mergedfinal6['BikeBuyer']

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [32]:
from sklearn.linear_model import LogisticRegression

In [59]:
logmodel=LogisticRegression(solver='newton-cg')
logmodel.fit(X_train,y_train)

C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:422: LineSearchWarning: Rounding errors prevent the line search from converging
  warn(msg, LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [60]:
predictions=logmodel.predict(X_test)

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.644969347277317

----

### StandardScale ile standardizasyon yapıp regresyon yapma testi

In [67]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [74]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\samay\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype uint8, int32, int64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.

In [75]:
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [76]:
y_pred=classifier.predict(X_test)

In [77]:
accuracy_score(y_test,y_pred)

0.641002524341868

0.003 azaldı

-----

### Train/Test yapmadan accuracy sonucunu görme

In [82]:
model=LogisticRegression(solver='newton-cg')

In [83]:
model.fit(X,y)

C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:422: LineSearchWarning: Rounding errors prevent the line search from converging
  warn(msg, LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [84]:
model.score(X,y)

0.6426098247132656

0.002 azaldı

----

### Yaptığımız feature importance ve Univariate Selection yönteminden çıkardığımız sonuca göre Gender,marital status,houseownerflag sütunlarını çıkarırsak modelimizde accuracy artışı görebilirdik bunu train/test modelinde de göreceğiz

In [87]:
mergedfinal8=mergedfinal6.drop(['M','Yes'],axis='columns')

In [88]:
mergedfinal8

,YearlyIncome,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,Age,CommuteDistanceNumeric,BikeBuyer,Graduate Degree,High School,Partial College,Partial High School,Clerical,Management,Manual,Skilled Manual,Europe,North America
0,90000,2,0,0,48,2,1,0,0,0,0,0,0,0,0,0,0
1,60000,3,3,1,43,1,1,0,0,0,0,0,0,0,0,0,0
2,60000,3,3,1,49,4,1,0,0,0,0,0,0,0,0,0,0
3,70000,0,0,1,46,7,1,0,0,0,0,0,0,0,0,0,0
4,80000,5,5,4,40,2,1,0,0,0,0,0,0,0,0,0,0
5,70000,0,0,1,43,7,1,0,0,0,0,0,0,0,0,0,0
6,70000,0,0,1,43,7,1,0,0,0,0,0,0,0,0,0,0
7,60000,3,3,2,50,1,1,0,0,0,0,0,0,0,0,0,0
8,60000,4,4,3,44,11,1,0,0,0,0,0,0,0,0,0,0
9,70000,0,0,1,50,7,1,0,0,0,0,0,0,0,0,0,0
10,70000,0,0,1,50,7,1,0,0,0,0,0,0,0,0,0,0
11,60000,4,4,4,50,11,1,0,0,0,0,0,0,0,0,0,0
12,100000,2,0,2,41,2,0,0,0,0,0,0,1,0,0,0,1
13,100000,2,0,3,40,1,0,0,0,0,0,0,1,0,0,0,1
14,100000,3,0,3,46,2,0,0,0,0,0,0,1,0,0,0,1
15,30000,0,0,1,35,7,1,0,0,1,0,0,0,0,1,0,1
16,30000,0,0,1,35,7,1,0,0,1,0,0,0,0,1,0,1
17,20000,4,0,2,70,7,1,0,1,0,0,0,0,0,1,0,0
18,30000,2,0,2,64,7,1,0,0,1,0,1,0,0,0,0,0
19,40000,0,0,2,36,7,0,0,1,0,0,0,0,0,1,0,1
20,40000,0,0,2,35,2,1,0,1,0,0,0,0,0,1,0,1
21,40000,0,0,1,35,2,1,0,0,1,0,0,0,0,1,0,1
22,40000,0,0,1,35,7,1,0,0,1,0,0,0,0,1,0,1
23,40000,0,0,1,35,2,0,0,0,1,0,0,0,0,1,0,1
24,60000,0,0,2,35,7,0,0,0,1,0,0,0,0,1,0,1
25,10000,2,1,2,68,2,1,0,0,0,1,1,0,0,0,0,0
26,30000,2,0,2,68,2,1,0,0,1,0,1,0,0,0,0,0
27,30000,2,0,2,67,7,1,0,0,1,0,1,0,0,0,0,0
28,30000,2,0,2,68,2,1,0,0,1,0,1,0,0,0,0,0
29,30000,2,0,2,67,2,1,0,0,1,0,1,0,0,0,0,0
30,10000,2,1,2,62,2,1,0,0,0,1,1,0,0,0,0,0
31,20000,4,0,2,67,2,1,0,1,0,0,0,0,0,1,0,0
32,20000,4,0,2,67,2,1,0,1,0,0,0,0,0,1,0,0
33,20000,4,0,2,61,7,1,0,1,0,0,0,0,0,1,0,0
34,20000,4,0,2,67,7,1,0,1,0,0,0,0,0,1,0,0
35,10000,2,1,2,66,2,1,0,0,0,1,1,0,0,0,0,0
36,60000,0,0,2,35,2,1,0,0,1,0,0,0,0,1,0,1
37,40000,0,0,2,36,7,1,0,0,0,1,1,0,0,0,0,1
38,10000,2,1,2,66,7,1,0,0,0,1,1,0,0,0,0,0
39,30000,3,0,2,65,7,1,0,0,1,0,1,0,0,0,0,0
40,30000,0,0,2,37,2,1,0,0,1,0,0,0,0,1,0,1
41,60000,0,0,2,36,2,1,0,0,1,0,0,0,0,1,0,1
42,70000,0,0,2,37,1,1,0,0,1,0,0,0,0,1,0,1
43,60000,0,0,2,38,7,0,0,0,1,0,0,0,0,1,0,1
44,20000,2,1,2,65,2,1,0,0,0,1,1,0,0,0,0,0
45,30000,3,0,2,64,2,0,0,1,0,0,0,0,0,1,0,0
46,30000,3,0,2,64,7,1,0,1,0,0,0,0,0,1,0,0
47,30000,3,0,2,64,2,1,0,1,0,0,0,0,0,1,0,0
48,30000,3,0,2,63,7,1,0,1,0,0,0,0,0,1,0,0
49,40000,0,0,2,34,7,0,0,0,0,1,1,0,0,0,0,1
50,30000,3,0,2,62,7,1,0,1,0,0,0,0,0,1,0,0
51,30000,3,0,2,63,2,0,0,1,0,0,0,0,0,1,0,0
52,40000,2,0,2,63,7,1,0,0,1,0,1,0,0,0,0,0
53,60000,0,0,2,34,2,1,0,0,1,0,0,0,0,1,0,1
54,40000,2,0,2,62,7,1,0,0,1,0,0,0,0,1,0,0
55,40000,2,0,2,62,7,1,0,0,1,0,0,0,0,1,0,0
56,40000,3,0,2,61,7,1,0,0,1,0,0,0,0,1,0,0
57,70000,2,0,2,49,2,1,1,0,0,0,0,1,0,0,0,0
58,80000,2,0,2,54,2,1,0,0,1,0,0,0,0,1,0,0
59,80000,2,0,2,60,7,0,0,0,1,0,0,0,0,1,0,0
60,80000,2,0,2,60,7,1,0,0,1,0,0,0,0,1,0,0
61,80000,2,0,2,44,7,1,0,0,1,0,0,0,0,1,0,0
62,40000,0,0,2,39,7,1,0,1,0,0,0,0,0,1,0,1
63,40000,0,0,2,39,7,1,0,1,0,0,0,0,0,1,0,1
64,40000,0,0,2,38,7,1,0,1,0,0,0,0,0,1,0,1
65,60000,0,0,2,40,2,0,0,0,1,0,0,0,0,1,0,1
66,70000,0,0,2,40,7,0,0,0,1,0,0,0,0,0,0,1
67,60000,0,0,2,37,7,0,0,0,1,0,0,0,0,0,0,1
68,80000,2,0,2,53,7,0,0,1,0,0,0,0,0,1,0,0
69,80000,2,0,2,53,2,1,0,1,0,0,0,0,0,1,0,0
70,80000,2,0,2,59,7,1,0,1,0,0,0,0,0,1,0,0
71,80000,2,0,2,59,7,0,0,1,0,0,0,0,0,1,0,0
72,80000,2,0,2,59,2,1,0,1,0,0,0,0,0,1,0,0
73,70000,2,0,2,58,7,0,0,1,0,0,0,0,0,1,0,0
74,70000,2,0,2,58,7,0,0,1,0,0,0,0,0,1,0,0
75,80000,2,0,2,56,7,1,0,1,0,0,0,0,0,0,0,0
76,80000,2,0,2,57,7,1,0,1,0,0,0,0,0,0,0,0
77,80000,2,0,2,56,2,1,0,1,0,0,0,0,0,0,0,0
78,40000,0,0,2,35,2,0,0,1,0,0,0,0,0,0,0,1
79,160000,0,0,2,49,1,0,1,0,0,0,0,1,0,0,0,0
80,170000,0,0,2,55,1,1,1,0,0,0,0,1,0,0,0,0
81,120000,2,2,3,48,4,0,0,0,0,0,0,1,0,0,0,1
82,130000,0,1,3,48,2,1,1,0,0,0,0,1,0,0,0,1
83,130000,0,1,3,42,2,1,1,0,0,0,0,1,0,0,0,1
84,80000,2,0,2,56,2,1,0,0,0,1,0,0,0,1,0,1
85,60000,2,0,2,57,7,0,0,1,0,0,0,0,0,0,0,1
86,70000,2,1,0,56,1,0,0,0,1,0,0,0,0,0,0,1
87,70000,3,2,0,56,1,0,0,0,1,0,0,0,0,0,0,1
88,80000,2,1,0,56,4,1,0,0,0,0,0,1,0,0,0,1
89,80000,2,1,1,57,4,1,0,0,0,0,0,1,0,0,0,1
90,90000,2,0,1,51,4,1,0,0,1,0,0,0,0,0,0,1
91,90000,2,0,1,57,7,0,0,0,1,0,0,0,0,0,0,1
92,90000,2,2,0,47,2,1,0,0,0,0,0,0,0,0,0,0
93,100000,0,0,0,41,1,1,1,0,0,0,0,1,0,0,0,0
94,70000,1,0,1,52,1,0,0,0,1,0,0,0,0,1,0,0
95,70000,1,0,1,52,7,1,0,0,1,0,0,0,0,1,0,0
96,60000,1,0,1,52,7,1,0,0,0,0,0,0,0,0,0,0
97,60000,1,0,1,47,7,1,0,0,1,0,0,0,0,1,0,0
98,60000,1,0,1,53,1,0,0,0,1,0,0,0,0,1,0,0
99,60000,1,0,1,53,1,1,0,0,0,0,0,0,0,0,0,0
100,60000,1,0,1,53,7,1,0,0,1,0,0,0,0,1,0,0
101,70000,0,0,1,49,1,1,0,0,0,0,0,0,0,0,0,0
102,80000,5,5,4,49,2,0,0,0,0,0,0,0,0,0,0,0
103,70000,0,0,1,38,7,1,0,0,0,0,0,0,0,0,0,0
104,70000,0,0,1,44,1,1,0,0,0,0,0,0,0,0,0,0
105,70000,0,0,1,49,7,1,0,0,0,0,0,0,0,0,0,0
106,70000,0,0,1,49,7,1,0,0,0,0,0,0,0,0,0,0
107,90000,1,0,1,43,7,1,0,0,0,0,0,0,0,0,0,0
108,70000,0,0,2,51,1,1,0,0,0,0,0,0,0,0,0,0
109,70000,0,0,2,39,1,1,0,0,0,0,0,0,0,0,0,0
110,60000,1,0,1,52,7,1,0,0,1,0,0,0,0,1,0,0
111,60000,1,0,1,52,1,1,0,0,1,0,0,0,0,1,0,0
112,60000,1,0,1,51,1,1,0,0,1,0,0,0,0,1,0,0
113,70000,5,4,2,47,7,0,0,0,0,0,0,0,0,0,0,0
114,70000,5,4,2,52,7,0,0,0,1,0,0,0,0,1,0,0
115,70000,5,4,2,52,1,0,0,0,1,0,0,0,0,1,0,0
116,70000,5,4,2,40,7,0,0,0,1,0,0,0,0,1,0,0
117,70000,5,4,3,53,11,1,0,0,1,0,0,0,0,1,0,0
118,80000,1,0,1,57,1,0,0,0,1,0,0,0,0,1,0,0
119,30000,2,0,2,79,1,0,0,0,1,0,1,0,0,0,0,0
120,40000,2,0,1,78,7,1,0,0,0,0,0,1,0,0,0,0
121,70000,5,4,3,53,11,0,0,0,1,0,0,0,0,1,0,0
122,70000,5,4,3,54,7,0,0,0,1,0,0,0,0,1,0,0
123,70000,5,4,3,54,11,0,0,0,1,0,0,0,0,1,0,0
124,80000,1,0,1,51,7,1,0,0,1,0,0,0,0,1,0,0
125,70000,1,0,1,58,7,0,0,0,1,0,0,0,0,1,0,0
126,10000,2,1,2,65,1,1,0,1,0,0,0,0,0,1,0,0
127,40000,0,0,1,38,7,0,0,1,0,0,0,0,0,1,0,1
128,40000,0,0,1,38,7,0,0,1,0,0,0,0,0,1,0,1
129,40000,0,0,1,39,7,1,0,1,0,0,0,0,0,1,0,1
130,30000,0,0,2,34,7,0,0,1,0,0,0,0,0,1,0,1
131,30000,0,0,2,34,1,0,0,1,0,0,0,0,0,1,0,1
132,30000,0,0,2,33,7,1,0,1,0,0,0,0,0,1,0,1
133,30000,0,0,2,33,1,0,0,0,0,1,1,0,0,0,0,1
134,10000,5,0,2,63,7,1,0,1,0,0,0,0,0,1,0,0
135,30000,0,0,2,34,7,1,0,0,0,1,1,0,0,0,0,1
136,40000,0,0,2,35,1,1,0,1,0,0,0,0,0,1,0,1
137,40000,0,0,2,36,7,0,0,1,0,0,0,0,0,1,0,1
138,40000,0,0,2,35,1,0,0,1,0,0,0,0,0,1,0,1
139,30000,2,0,2,70,7,0,0,0,1,0,1,0,0,0,0,0
140,30000,0,0,2,37,7,0,0,0,0,1,1,0,0,0,0,1
141,40000,0,0,2,37,1,0,0,1,0,0,0,0,0,1,0,1
142,40000,0,0,2,37,1,0,0,1,0,0,0,0,0,1,0,1
143,40000,0,0,2,37,7,0,0,1,0,0,0,0,0,1,0,1
144,40000,0,0,2,34,1,1,0,1,0,0,0,0,0,1,0,1
145,40000,0,0,2,34,1,1,0,1,0,0,0,0,0,1,0,1
146,40000,2,0,2,75,7,0,0,0,0,0,0,1,0,0,0,0
147,60000,2,0,1,75,1,1,1,0,0,0,0,1,0,0,0,0
148,40000,2,0,2,73,7,0,0,0,0,0,0,1,0,0,0,0
149,40000,2,0,2,73,1,0,0,0,0,0,0,1,0,0,0,0
150,40000,2,0,2,73,7,0,0,0,0,0,0,1,0,0,0,0
151,60000,2,0,1,72,1,1,1,0,0,0,0,1,0,0,0,0
152,40000,0,0,2,38,7,1,0,1,0,0,0,0,0,1,0,1
153,40000,0,0,2,38,7,0,0,1,0,0,0,0,0,1,0,1
154,40000,0,0,1,38,7,1,0,0,1,0,0,0,0,1,0,1
155,40000,0,0,1,38,2,1,0,0,1,0,0,0,0,1,0,1
156,40000,0,0,1,38,2,1,0,0,1,0,0,0,0,1,0,1
157,40000,0,0,2,39,7,0,0,1,0,0,0,0,0,1,0,1
158,40000,0,0,2,38,7,1,0,1,0,0,0,0,0,1,0,1
159,40000,0,0,2,38,2,0,0,1,0,0,0,0,0,1,0,1
160,40000,0,0,1,40,7,1,0,0,1,0,0,0,0,1,0,1
161,40000,0,0,1,40,2,0,0,0,1,0,0,0,0,1,0,1
162,40000,0,0,1,40,7,1,0,0,1,0,0,0,0,1,0,1
163,40000,0,0,1,39,7,0,0,0,1,0,0,0,0,1,0,1
164,40000,0,0,1,40,2,0,0,0,1,0,0,0,0,1,0,1
165,60000,0,0,1,41,2,0,0,0,1,0,0,0,0,1,0,1
166,70000,0,0,2,42,1,0,0,0,1,0,0,0,0,1,0,1
167,80000,0,0,1,42,1,1,0,0,0,0,0,1,0,0,0,1
168,80000,0,0,1,46,1,1,0,0,0,0,0,1,0,0,0,1
169,90000,4,4,1,46,1,0,0,0,0,0,0,1,0,0,0,1
170,90000,4,4,1,46,1,0,0,0,0,0,0,1,0,0,0,1
171,100000,1,0,2,41,2,1,0,0,0,0,0,1,0,0,0,1
172,100000,1,0,2,46,2,0,0,0,0,0,0,1,0,0,0,1
173,110000,0,0,4,47,1,0,1,0,0,0,0,1,0,0,0,1
174,110000,0,1,0,47,4,0,1,0,0,0,0,1,0,0,0,1
175,70000,0,0,2,51,7,1,0,0,1,0,0,0,0,1,0,1
176,90000,4,4,1,41,2,0,0,0,0,0,0,1,0,0,0,1
177,110000,2,4,2,72,7,0,1,0,0,0,0,1,0,0,0,1
178,100000,2,3,3,65,2,0,1,0,0,0,0,1,0,0,0,1
179,120000,2,4,3,60,7,0,1,0,0,0,0,1,0,0,0,1
180,160000,1,3,4,71,1,0,0,0,0,0,0,1,0,0,0,1
181,170000,2,3,2,60,1,0,1,0,0,0,0,1,0,0,0,1
182,70000,4,0,2,70,11,0,0,0,0,0,0,1,0,0,0,1
183,70000,4,0,2,70,11,0,0,0,0,0,0,1,0,0,0,1
184,70000,4,0,2,64,11,0,0,0,0,0,0,1,0,0,0,1
185,70000,4,0,2,69,11,0,0,0,0,0,0,1,0,0,0,1
186,70000,4,0,2,70,11,0,0,0,0,0,0,1,0,0,0,1
187,60000,4,0,2,70,11,0,1,0,0,0,0,1,0,0,0,1
188,60000,4,0,2,69,2,0,1,0,0,0,0,1,0,0,0,1
189,60000,4,0,2,70,11,1,1,0,0,0,0,1,0,0,0,1
190,70000,5,0,2,70,11,0,0,0,0,0,0,1,0,0,0,1
191,70000,5,0,3,68,11,1,0,0,0,0,0,1,0,0,0,1
192,60000,4,0,2,68,4,0,0,0,0,0,0,1,0,0,0,1
193,60000,4,0,2,69,4,0,0,0,0,0,0,1,0,0,0,1
194,60000,4,0,2,69,4,0,0,0,0,0,0,1,0,0,0,1
195,60000,5,0,3,68,11,0,0,0,0,0,0,1,0,0,0,1
196,60000,5,0,3,68,11,0,0,0,0,0,0,1,0,0,0,1
197,70000,3,1,1,68,2,0,0,0,0,0,0,1,0,0,0,1
198,70000,4,1,1,67,11,0,0,0,0,0,0,1,0,0,0,1
199,70000,4,1,1,62,11,0,0,0,0,0,0,1,0,0,0,1
200,70000,4,1,1,66,2,0,0,0,0,0,0,1,0,0,0,1
201,70000,4,1,1,67,11,0,0,0,0,0,0,1,0,0,0,1
202,80000,5,0,2,61,2,0,0,0,0,0,0,1,0,0,0,1
203,40000,2,1,2,60,11,0,0,1,0,0,0,0,0,0,0,1
204,40000,2,1,2,66,4,0,0,1,0,0,0,0,0,0,0,1
205,40000,2,1,2,66,11,0,0,1,0,0,0,0,0,0,0,1
206,60000,2,1,1,65,11,0,0,0,1,0,0,0,0,0,0,1
207,60000,2,1,1,66,11,0,0,0,1,0,0,0,0,0,0,1
208,60000,2,1,0,66,11,0,0,0,0,0,0,1,0,0,0,1
209,60000,2,1,0,66,11,0,0,0,0,0,0,1,0,0,0,1
210,70000,4,1,2,66,11,0,0,0,1,0,0,0,0,0,0,1
211,40000,2,1,2,59,4,0,0,1,0,0,0,0,0,0,0,1
212,40000,2,1,2,64,4,0,0,1,0,0,0,0,0,0,0,1
213,60000,2,1,2,65,11,0,0,0,1,0,0,0,0,0,0,1
214,60000,2,1,2,64,11,0,0,0,1,0,0,0,0,0,0,1
215,40000,2,1,2,58,11,0,0,0,0,1,0,0,0,1,0,1
216,60000,2,1,2,64,11,1,0,0,1,0,0,0,0,0,0,1
217,60000,2,1,2,64,11,1,0,0,1,0,0,0,0,0,0,1
218,60000,2,1,2,58,4,0,0,0,1,0,0,0,0,0,0,1
219,60000,2,1,2,63,11,0,0,1,0,0,0,0,0,0,0,1
220,60000,2,1,1,59,11,0,0,0,1,0,0,0,0,0,0,1
221,70000,4,2,1,64,2,0,0,0,1,0,0,0,0,0,0,1
222,80000,3,1,1,64,2,0,0,0,0,0,0,1,0,0,0,1
223,70000,2,1,2,62,4,0,0,1,0,0,0,0,0,0,0,1
224,70000,2,1,2,62,11,1,0,1,0,0,0,0,0,0,0,1
225,60000,2,1,1,58,11,0,0,0,1,0,0,0,0,0,0,1
226,60000,2,1,1,57,4,0,0,0,1,0,0,0,0,0,0,1
227,60000,2,1,2,57,11,1,0,0,1,0,0,0,0,0,0,1
228,60000,2,1,2,63,11,0,0,0,1,0,0,0,0,0,0,1
229,70000,4,2,1,62,11,0,0,0,1,0,0,0,0,0,0,1
230,70000,4,2,2,63,4,0,0,0,1,0,0,0,0,0,0,1
231,60000,2,1,2,56,11,0,0,1,0,0,0,0,0,0,0,1
232,60000,3,1,2,61,4,0,0,1,0,0,0,0,0,0,0,1
233,70000,4,2,2,56,11,0,0,0,1,0,0,0,0,0,0,1
234,70000,4,2,2,61,11,0,0,0,1,0,0,0,0,0,0,1
235,70000,4,2,2,62,11,0,0,0,1,0,0,0,0,0,0,1
236,70000,5,2,2,62,11,0,0,0,1,0,0,0,0,0,0,1
237,130000,2,3,4,55,1,1,0,0,0,0,0,1,0,0,1,0
238,130000,2,3,4,56,1,1,0,0,0,0,0,1,0,0,1,0
239,130000,2,4,2,50,7,1,0,0,1,0,0,0,0,0,1,0
240,160000,2,3,4,55,7,1,0,0,1,0,0,0,0,0,1,0
241,100000,2,3,4,45,7,1,0,0,1,0,0,0,0,0,1,0
242,110000,2,4,3,56,7,1,0,0,1,0,0,0,0,0,1,0
243,150000,2,3,3,56,1,1,0,0,1,0,0,0,0,0,1,0
244,170000,2,3,3,51,1,1,0,0,0,0,0,1,0,0,1,0
245,120000,3,4,4,57,7,1,0,1,0,0,0,0,0,0,1,0
246,120000,3,4,4,57,7,1,0,1,0,0,0,0,0,0,1,0
247,130000,3,4,3,58,1,1,0,0,1,0,0,0,0,0,1,0
248,110000,3,4,4,53,11,0,0,0,1,0,0,0,0,0,1,0
249,130000,3,4,3,53,1,1,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,110000,5,3,1,50,7,0,0,0,0,0,0,1,0,0,0,1
18235,120000,4,3,2,50,2,0,0,0,1,0,0,0,0,0,0,1
18236,120000,4,3,3,51,7,1,0,0,1,0,0,0,0,0,0,1
18237,120000,4,3,3,51,7,1,0,0,1,0,0,0,0,0,0,1
18238,150000,4,1,3,51,2,1,0,0,1,0,0,0,0,0,0,1
18239,150000,4,1,4,51,2,1,0,0,1,0,0,0,0,0,0,1
18240,80000,5,4,3,52,1,0,0,0,1,0,0,0,0,0,0,1
18241,90000,5,4,4,46,2,0,0,0,1,0,0,0,0,0,0,1
18242,100000,3,2,4,51,7,1,0,0,1,0,0,0,0,0,0,1
18243,110000,1,3,1,51,7,0,0,0,0,0,0,1,0,0,0,1
18244,110000,1,3,2,52,7,0,0,0,0,0,0,1,0,0,0,1
18245,130000,1,2,4,51,1,0,0,0,0,0,0,1,0,0,0,1
18246,130000,1,2,4,52,4,0,0,0,0,0,0,1,0,0,0,1
18247,70000,5,4,3,42,7,1,0,0,1,0,0,0,0,0,0,1
18248,90000,4,3,2,53,7,0,0,1,0,0,0,0,0,0,0,1
18249,90000,4,3,2,53,7,0,0,1,0,0,0,0,0,0,0,1
18250,100000,3,2,4,47,2,0,0,0,1,0,0,0,0,0,0,1
18251,110000,1,3,3,53,7,0,0,0,0,0,0,1,0,0,0,1
18252,130000,1,3,3,52,1,1,0,0,0,0,0,1,0,0,0,1
18253,130000,3,3,3,53,4,0,0,0,0,0,0,1,0,0,0,1
18254,60000,2,0,2,58,7,1,0,1,0,0,0,0,0,0,0,1
18255,80000,3,2,1,59,2,1,0,0,1,0,0,0,0,0,0,1
18256,90000,2,1,1,58,11,1,0,1,0,0,0,0,0,0,0,1
18257,90000,2,1,1,58,11,0,0,1,0,0,0,0,0,0,0,1
18258,90000,2,1,1,58,11,1,0,1,0,0,0,0,0,0,0,1
18259,70000,2,0,2,59,7,0,0,0,0,1,0,0,0,1,0,1
18260,70000,4,0,2,79,2,0,1,0,0,0,0,1,0,0,0,1
18261,130000,2,3,3,79,1,1,1,0,0,0,0,1,0,0,0,1
18262,50000,2,0,2,78,2,0,1,0,0,0,0,1,0,0,0,1
18263,70000,4,0,2,78,2,0,1,0,0,0,0,1,0,0,0,1
18264,90000,4,0,2,78,2,1,0,0,0,0,0,1,0,0,0,1
18265,90000,4,0,2,77,2,1,0,0,0,0,0,1,0,0,0,1
18266,80000,5,4,3,54,2,0,0,0,1,0,0,0,0,0,0,1
18267,80000,5,4,3,48,7,0,0,0,1,0,0,0,0,0,0,1
18268,90000,4,3,3,54,7,0,0,1,0,0,0,0,0,0,0,1
18269,90000,4,3,3,54,7,0,0,1,0,0,0,0,0,0,0,1
18270,100000,0,3,1,54,7,0,0,0,1,0,0,0,0,0,0,1
18271,100000,0,3,1,48,2,0,0,0,1,0,0,0,0,0,0,1
18272,100000,0,3,2,54,7,0,0,0,1,0,0,0,0,0,0,1
18273,100000,0,3,2,49,7,0,0,0,1,0,0,0,0,0,0,1
18274,120000,5,4,3,54,7,1,0,1,0,0,0,0,0,0,0,1
18275,70000,3,0,2,61,2,1,1,0,0,0,0,1,0,0,0,1
18276,70000,3,0,2,61,7,1,1,0,0,0,0,1,0,0,0,1
18277,70000,3,0,2,61,2,1,1,0,0,0,0,1,0,0,0,1
18278,70000,3,0,2,55,7,1,1,0,0,0,0,1,0,0,0,1
18279,70000,3,0,2,61,7,1,1,0,0,0,0,1,0,0,0,1
18280,40000,3,0,2,52,2,1,0,0,1,0,0,0,0,0,0,1
18281,40000,4,0,2,59,2,1,0,0,1,0,0,0,0,0,0,1
18282,30000,4,0,2,64,7,0,0,1,0,0,0,0,0,0,0,1
18283,30000,4,0,2,65,2,0,0,1,0,0,0,0,0,0,0,1
18284,30000,4,0,2,64,2,0,0,1,0,0,0,0,0,0,0,1
18285,40000,4,0,2,65,2,1,0,1,0,0,0,0,0,0,0,1
18286,60000,3,3,2,44,1,0,0,0,0,0,0,0,0,0,0,0
18287,60000,4,4,1,50,7,0,0,0,0,0,0,0,0,0,0,0
18288,60000,4,4,2,38,1,0,0,0,0,0,0,0,0,0,0,0
18289,70000,0,0,1,44,7,1,0,0,0,0,0,0,0,0,0,0
18290,60000,5,5,2,50,1,0,0,0,0,0,0,0,0,0,0,0
18291,60000,3,2,2,50,1,1,0,0,0,0,0,0,0,0,0,0
18292,90000,2,2,0,42,1,1,0,0,0,0,0,0,0,0,0,0
18293,90000,3,3,0,47,2,1,0,0,0,0,0,0,0,0,0,0
18294,60000,1,0,1,53,1,1,0,0,1,0,0,0,0,1,0,0
18295,110000,0,0,2,48,2,1,1,0,0,0,0,1,0,0,0,0
18296,110000,0,0,3,47,2,0,1,0,0,0,0,1,0,0,0,0
18297,60000,1,0,1,48,1,1,0,0,1,0,0,0,0,1,0,0
18298,60000,1,0,1,54,7,1,0,0,1,0,0,0,0,1,0,0
18299,60000,1,0,1,53,7,1,0,0,1,0,0,0,0,1,0,0
18300,70000,0,0,1,48,7,1,0,0,0,0,0,0,0,0,0,0
18301,80000,5,5,4,43,2,0,0,0,0,0,0,0,0,0,0,0
18302,70000,0,0,1,50,7,0,0,0,0,0,0,0,0,0,0,0
18303,70000,0,0,1,50,7,1,0,0,0,0,0,0,0,0,0,0
18304,100000,5,0,1,55,11,0,0,0,0,0,0,0,0,0,0,0
18305,100000,5,0,1,55,11,0,0,0,0,0,0,0,0,0,0,0
18306,70000,0,0,1,45,1,1,0,0,0,0,0,0,0,0,0,0
18307,70000,0,0,1,51,7,0,0,0,0,0,0,0,0,0,0,0
18308,70000,0,0,2,40,1,1,0,0,0,0,0,0,0,0,0,0
18309,70000,0,0,2,51,7,1,0,0,0,0,0,0,0,0,0,0
18310,70000,0,0,2,50,7,1,0,0,0,0,0,0,0,0,0,0
18311,60000,1,0,1,52,7,1,0,0,1,0,0,0,0,1,0,0
18312,70000,5,4,2,46,7,0,0,0,1,0,0,0,0,1,0,0
18313,60000,1,0,1,52,7,1,0,0,1,0,0,0,0,1,0,0
18314,60000,1,0,1,47,7,1,0,0,1,0,0,0,0,1,0,0
18315,90000,2,0,1,44,7,0,0,0,0,0,0,0,0,0,0,0
18316,90000,2,0,1,55,4,1,0,0,0,0,0,0,0,0,0,0
18317,90000,2,0,1,56,4,1,0,0,0,0,0,0,0,0,0,0
18318,100000,4,0,2,55,2,1,0,0,0,0,0,1,0,0,0,0
18319,70000,1,0,1,57,1,1,0,0,1,0,0,0,0,1,0,0
18320,70000,5,4,3,49,7,0,0,0,1,0,0,0,0,1,0,0
18321,70000,5,4,3,53,7,0,0,0,1,0,0,0,0,1,0,0
18322,30000,0,0,2,38,7,0,0,1,0,0,0,0,0,1,0,1
18323,40000,0,0,2,38,7,0,0,1,0,0,0,0,0,1,0,1
18324,40000,0,0,2,38,7,0,0,1,0,0,0,0,0,1,0,1
18325,40000,0,0,2,38,1,0,0,1,0,0,0,0,0,1,0,1
18326,30000,0,0,2,34,1,1,0,1,0,0,0,0,0,1,0,1
18327,30000,0,0,2,34,1,0,0,1,0,0,0,0,0,1,0,1
18328,30000,0,0,2,34,7,0,0,1,0,0,0,0,0,1,0,1
18329,30000,0,0,2,35,7,0,0,1,0,0,0,0,0,1,0,1
18330,40000,0,0,2,34,7,0,0,1,0,0,0,0,0,1,0,1
18331,30000,2,0,2,71,1,0,0,0,1,0,1,0,0,0,0,0
18332,30000,2,0,2,77,7,0,0,0,1,0,1,0,0,0,0,0
18333,40000,2,0,2,76,1,0,0,0,0,0,0,1,0,0,0,0
18334,30000,0,0,2,35,1,1,0,0,0,1,1,0,0,0,0,1
18335,30000,0,0,2,36,1,1,0,0,0,1,1,0,0,0,0,1
18336,40000,0,0,2,36,1,1,0,1,0,0,0,0,0,1,0,1
18337,30000,2,0,2,76,7,0,0,0,1,0,1,0,0,0,0,0
18338,40000,2,0,2,76,7,0,0,0,0,0,0,1,0,0,0,0
18339,30000,0,0,2,34,7,0,0,0,0,1,1,0,0,0,0,1
18340,30000,0,0,2,34,1,1,0,0,0,1,1,0,0,0,0,1
18341,30000,0,0,2,35,7,0,0,0,0,1,1,0,0,0,0,1
18342,30000,2,0,2,74,1,1,0,0,1,0,1,0,0,0,0,0
18343,40000,2,0,2,74,1,1,0,0,0,0,0,1,0,0,0,0
18344,40000,2,0,2,71,7,1,0,0,0,0,0,1,0,0,0,0
18345,40000,2,0,2,61,1,1,0,0,0,0,0,1,0,0,0,0
18346,50000,2,0,1,72,1,1,1,0,0,0,0,1,0,0,0,0
18347,40000,0,0,1,43,1,0,0,0,0,0,0,0,0,0,0,1
18348,50000,3,3,1,49,4,0,0,0,0,0,0,0,0,1,0,1
18349,50000,3,3,2,43,1,0,0,0,0,0,0,0,0,1,0,1
18350,50000,3,3,2,48,4,1,0,0,0,0,0,0,0,1,0,1
18351,50000,3,3,2,49,1,0,0,0,0,0,0,0,0,1,0,1
18352,50000,3,3,3,49,11,1,0,0,0,0,0,0,0,1,0,1
18353,50000,3,3,3,38,11,0,0,0,0,0,0,0,0,1,0,1
18354,60000,0,0,0,48,4,1,1,0,0,0,0,0,0,0,0,1
18355,40000,0,0,0,45,1,1,1,0,0,0,1,0,0,0,1,0
18356,40000,0,0,0,46,1,1,1,0,0,0,1,0,0,0,1,0
18357,40000,0,0,0,40,1,1,1,0,0,0,1,0,0,0,1,0
18358,40000,0,0,0,46,1,1,1,0,0,0,1,0,0,0,1,0
18359,40000,0,0,0,45,1,1,1,0,0,0,1,0,0,0,1,0
18360,40000,0,0,0,40,1,1,0,0,0,0,0,0,0,0,1,0
18361,20000,1,1,1,47,4,1,0,0,1,0,0,0,1,0,1,0
18362,20000,1,1,1,46,4,1,0,0,1,0,0,0,1,0,1,0
18363,20000,1,1,1,46,4,1,0,0,1,0,0,0,1,0,1,0
18364,10000,4,4,1,48,1,1,0,0,0,1,0,0,1,0,1,0
18365,20000,1,1,1,48,4,1,0,1,0,0,0,0,1,0,1,0
18366,40000,0,0,0,47,1,1,0,0,0,0,0,0,0,0,1,0
18367,40000,0,0,0,36,1,1,0,0,0,0,0,0,0,0,1,0
18368,40000,0,0,0,47,1,1,0,0,0,0,0,0,0,0,1,0
18369,40000,0,0,0,35,1,1,0,0,0,0,0,0,0,0,1,0
18370,30000,1,0,1,86,4,0,0,0,0,0,1,0,0,0,1,0
18371,20000,2,2,0,47,1,1,0,1,0,0,0,0,1,0,1,0
18372,30000,1,1,2,47,1,0,0,0,0,0,0,0,0,1,1,0
18373,30000,1,1,2,48,1,0,0,0,0,0,0,0,0,1,1,0
18374,20000,2,2,1,49,1,1,0,1,0,0,0,0,1,0,1,0
18375,20000,2,2,1,48,1,1,0,1,0,0,0,0,1,0,1,0
18376,20000,2,2,2,48,1,0,0,1,0,0,0,0,1,0,1,0
18377,30000,1,1,2,49,1,0,0,0,0,0,0,0,0,1,1,0
18378,30000,1,1,2,49,1,0,0,0,0,0,0,0,0,1,1,0
18379,30000,1,1,2,43,1,0,0,0,0,0,0,0,0,1,1,0
18380,20000,3,3,0,49,1,1,0,1,0,0,0,0,1,0,1,0
18381,20000,3,3,0,50,1,1,0,1,0,0,0,0,1,0,1,0
18382,20000,3,3,0,49,1,1,0,1,0,0,0,0,1,0,1,0
18383,10000,3,2,2,51,1,0,0,0,0,1,0,0,1,0,1,0
18384,10000,4,2,2,51,1,0,0,0,0,1,0,0,1,0,1,0
18385,20000,4,4,1,51,1,1,0,1,0,0,0,0,1,0,1,0
18386,20000,2,0,1,71,4,0,0,0,1,0,0,0,1,0,1,0
18387,10000,4,0,2,75,1,0,0,1,0,0,0,0,1,0,1,0
18388,40000,0,0,0,42,1,1,0,0,0,0,0,0,0,0,1,0
18389,40000,0,0,0,48,1,1,0,0,0,0,0,0,0,0,1,0
18390,40000,0,0,0,48,1,1,0,0,0,0,0,0,0,0,1,0
18391,40000,0,0,0,47,1,1,0,0,0,0,0,0,0,0,1,0
18392,40000,0,0,0,48,1,1,0,0,0,0,0,0,0,0,1,0
18393,30000,2,2,0,50,1,0,0,0,1,0,1,0,0,0,1,0
18394,30000,1,0,1,46,4,0,0,0,1,0,1,0,0,0,1,0
18395,20000,2,0,1,80,2,0,0,0,1,0,1,0,0,0,1,0
18396,30000,1,0,1,80,1,0,0,0,0,0,0,0,0,1,1,0
18397,30000,2,2,1,43,1,1,0,0,1,0,1,0,0,0,1,0
18398,40000,0,0,0,49,1,1,0,0,0,0,0,0,0,0,1,0
18399,40000,0,0,0,44,1,1,0,0,0,0,0,0,0,0,1,0
18400,40000,1,0,0,43,1,1,0,0,0,0,0,0,0,1,1,0
18401,40000,1,0,0,43,1,1,0,0,0,0,0,0,0,1,1,0
18402,30000,2,2,2,50,1,0,0,0,1,0,1,0,0,0,1,0
18403,40000,1,0,0,50,1,1,0,0,0,0,0,0,0,1,1,0
18404,30000,3,3,0,45,1,1,0,0,1,0,1,0,0,0,1,0
18405,20000,0,0,1,36,4,0,0,1,0,0,0,0,1,0,1,0
18406,10000,0,0,2,37,1,0,0,0,0,1,0,0,1,0,1,0
18407,20000,4,4,1,38,1,1,0,1,0,0,0,0,1,0,1,0
18408,20000,4,4,2,35,1,0,0,1,0,0,0,0,1,0,1,0
18409,30000,3,3,1,34,1,0,0,0,1,0,1,0,0,0,1,0
18410,30000,3,3,1,35,1,1,0,0,1,0,1,0,0,0,1,0
18411,40000,1,0,0,45,1,1,0,0,0,0,0,0,0,1,1,0
18412,40000,1,0,1,46,1,1,0,0,0,0,0,0,0,1,1,0
18413,30000,3,3,2,35,1,0,0,0,1,0,1,0,0,0,1,0
18414,30000,3,3,2,36,1,1,0,0,1,0,1,0,0,0,1,0
18415,30000,0,0,1,36,4,1,0,0,1,0,1,0,0,0,1,0
18416,10000,0,0,2,39,1,0,0,0,0,1,0,0,1,0,1,0
18417,10000,0,0,2,39,1,0,0,0,0,1,0,0,1,0,1,0
18418,20000,0,0,1,38,7,0,0,1,0,0,0,0,1,0,1,0
18419,20000,0,0,1,37,4,0,0,1,0,0,0,0,1,0,1,0
18420,20000,0,0,1,38,4,0,0,1,0,0,0,0,1,0,1,0
18421,20000,0,0,1,38,4,0,0,1,0,0,0,0,1,0,1,0
18422,20000,0,0,1,38,4,0,0,1,0,0,0,0,1,0,1,0
18423,20000,0,0,1,38,4,0,0,1,0,0,0,0,1,0,1,0
18424,10000,0,0,2,40,1,0,0,0,0,1,0,0,1,0,1,0
18425,20000,0,0,2,40,1,0,0,0,0,1,0,0,1,0,1,0
18426,20000,0,0,2,39,1,0,0,0,0,1,0,0,1,0,1,0
18427,20000,0,0,2,40,1,0,0,0,0,1,0,0,1,0,1,0
18428,20000,0,0,2,40,2,0,0,0,0,1,0,0,1,0,1,0
18429,30000,0,0,1,39,1,0,0,0,1,0,1,0,0,0,1,0
18430,30000,0,0,1,38,1,0,0,0,1,0,1,0,0,0,1,0
18431,40000,1,1,0,38,1,1,0,0,0,0,0,0,0,1,1,0

In [89]:
X=mergedfinal8.drop('BikeBuyer',axis=1)
y=mergedfinal8['BikeBuyer']

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [92]:
from sklearn.linear_model import LogisticRegression

In [93]:
logmodel=LogisticRegression(solver='newton-cg')
logmodel.fit(X_train,y_train)

C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:422: LineSearchWarning: Rounding errors prevent the line search from converging
  warn(msg, LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [94]:
predictions=logmodel.predict(X_test)

In [95]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.6458708979444645

3 sütunu çıkardığımızda accuracy oranında 0.001'lik artış oldu

### Şimdi de sonucu en fazla etkileyen iki sütun olan 'Age' ve 'YearlyIncome' sütunların veri setine dahil edilmediğindeki sonucu görelim

In [96]:
mergedfinal9=mergedfinal6.drop(['Age','YearlyIncome'],axis='columns')

In [97]:
mergedfinal9

,TotalChildren,NumberChildrenAtHome,NumberCarsOwned,CommuteDistanceNumeric,BikeBuyer,M,M,Graduate Degree,High School,Partial College,Partial High School,Clerical,Management,Manual,Skilled Manual,Yes,Europe,North America
0,2,0,0,2,1,1,1,0,0,0,0,0,0,0,0,1,0,0
1,3,3,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0
2,3,3,1,4,1,1,1,0,0,0,0,0,0,0,0,1,0,0
3,0,0,1,7,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,5,4,2,1,0,0,0,0,0,0,0,0,0,0,1,0,0
5,0,0,1,7,1,0,1,0,0,0,0,0,0,0,0,1,0,0
6,0,0,1,7,1,0,0,0,0,0,0,0,0,0,0,1,0,0
7,3,3,2,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0
8,4,4,3,11,1,0,0,0,0,0,0,0,0,0,0,1,0,0
9,0,0,1,7,1,0,1,0,0,0,0,0,0,0,0,0,0,0
10,0,0,1,7,1,0,0,0,0,0,0,0,0,0,0,0,0,0
11,4,4,4,11,1,1,1,0,0,0,0,0,0,0,0,1,0,0
12,2,0,2,2,0,1,0,0,0,0,0,0,1,0,0,1,0,1
13,2,0,3,1,0,1,1,0,0,0,0,0,1,0,0,1,0,1
14,3,0,3,2,0,0,0,0,0,0,0,0,1,0,0,0,0,1
15,0,0,1,7,1,0,0,0,0,1,0,0,0,0,1,0,0,1
16,0,0,1,7,1,1,1,0,0,1,0,0,0,0,1,1,0,1
17,4,0,2,7,1,0,0,0,1,0,0,0,0,0,1,1,0,0
18,2,0,2,7,1,0,1,0,0,1,0,1,0,0,0,1,0,0
19,0,0,2,7,0,0,1,0,1,0,0,0,0,0,1,0,0,1
20,0,0,2,2,1,0,1,0,1,0,0,0,0,0,1,0,0,1
21,0,0,1,2,1,0,0,0,0,1,0,0,0,0,1,0,0,1
22,0,0,1,7,1,1,1,0,0,1,0,0,0,0,1,1,0,1
23,0,0,1,2,0,1,1,0,0,1,0,0,0,0,1,1,0,1
24,0,0,2,7,0,1,1,0,0,1,0,0,0,0,1,1,0,1
25,2,1,2,2,1,1,1,0,0,0,1,1,0,0,0,1,0,0
26,2,0,2,2,1,0,1,0,0,1,0,1,0,0,0,0,0,0
27,2,0,2,7,1,1,1,0,0,1,0,1,0,0,0,1,0,0
28,2,0,2,2,1,1,0,0,0,1,0,1,0,0,0,1,0,0
29,2,0,2,2,1,1,1,0,0,1,0,1,0,0,0,1,0,0
30,2,1,2,2,1,1,0,0,0,0,1,1,0,0,0,1,0,0
31,4,0,2,2,1,1,0,0,1,0,0,0,0,0,1,1,0,0
32,4,0,2,2,1,1,0,0,1,0,0,0,0,0,1,1,0,0
33,4,0,2,7,1,1,1,0,1,0,0,0,0,0,1,1,0,0
34,4,0,2,7,1,1,0,0,1,0,0,0,0,0,1,1,0,0
35,2,1,2,2,1,1,0,0,0,0,1,1,0,0,0,1,0,0
36,0,0,2,2,1,1,0,0,0,1,0,0,0,0,1,1,0,1
37,0,0,2,7,1,0,0,0,0,0,1,1,0,0,0,0,0,1
38,2,1,2,7,1,1,0,0,0,0,1,1,0,0,0,1,0,0
39,3,0,2,7,1,1,1,0,0,1,0,1,0,0,0,1,0,0
40,0,0,2,2,1,1,1,0,0,1,0,0,0,0,1,1,0,1
41,0,0,2,2,1,1,0,0,0,1,0,0,0,0,1,1,0,1
42,0,0,2,1,1,1,0,0,0,1,0,0,0,0,1,1,0,1
43,0,0,2,7,0,1,1,0,0,1,0,0,0,0,1,1,0,1
44,2,1,2,2,1,1,1,0,0,0,1,1,0,0,0,1,0,0
45,3,0,2,2,0,0,1,0,1,0,0,0,0,0,1,0,0,0
46,3,0,2,7,1,1,0,0,1,0,0,0,0,0,1,1,0,0
47,3,0,2,2,1,1,0,0,1,0,0,0,0,0,1,0,0,0
48,3,0,2,7,1,1,1,0,1,0,0,0,0,0,1,1,0,0
49,0,0,2,7,0,0,0,0,0,0,1,1,0,0,0,1,0,1
50,3,0,2,7,1,1,1,0,1,0,0,0,0,0,1,1,0,0
51,3,0,2,2,0,0,1,0,1,0,0,0,0,0,1,0,0,0
52,2,0,2,7,1,0,0,0,0,1,0,1,0,0,0,0,0,0
53,0,0,2,2,1,1,0,0,0,1,0,0,0,0,1,0,0,1
54,2,0,2,7,1,1,0,0,0,1,0,0,0,0,1,1,0,0
55,2,0,2,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
56,3,0,2,7,1,1,0,0,0,1,0,0,0,0,1,1,0,0
57,2,0,2,2,1,1,1,1,0,0,0,0,1,0,0,1,0,0
58,2,0,2,2,1,1,1,0,0,1,0,0,0,0,1,1,0,0
59,2,0,2,7,0,0,0,0,0,1,0,0,0,0,1,1,0,0
60,2,0,2,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
61,2,0,2,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
62,0,0,2,7,1,1,1,0,1,0,0,0,0,0,1,1,0,1
63,0,0,2,7,1,0,0,0,1,0,0,0,0,0,1,1,0,1
64,0,0,2,7,1,1,1,0,1,0,0,0,0,0,1,1,0,1
65,0,0,2,2,0,1,0,0,0,1,0,0,0,0,1,0,0,1
66,0,0,2,7,0,1,0,0,0,1,0,0,0,0,0,1,0,1
67,0,0,2,7,0,0,1,0,0,1,0,0,0,0,0,1,0,1
68,2,0,2,7,0,0,0,0,1,0,0,0,0,0,1,1,0,0
69,2,0,2,2,1,0,0,0,1,0,0,0,0,0,1,0,0,0
70,2,0,2,7,1,1,1,0,1,0,0,0,0,0,1,1,0,0
71,2,0,2,7,0,0,0,0,1,0,0,0,0,0,1,1,0,0
72,2,0,2,2,1,0,0,0,1,0,0,0,0,0,1,0,0,0
73,2,0,2,7,0,0,0,0,1,0,0,0,0,0,1,1,0,0
74,2,0,2,7,0,0,1,0,1,0,0,0,0,0,1,1,0,0
75,2,0,2,7,1,0,0,0,1,0,0,0,0,0,0,1,0,0
76,2,0,2,7,1,0,1,0,1,0,0,0,0,0,0,1,0,0
77,2,0,2,2,1,0,0,0,1,0,0,0,0,0,0,0,0,0
78,0,0,2,2,0,0,0,0,1,0,0,0,0,0,0,0,0,1
79,0,0,2,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0
80,0,0,2,1,1,1,1,1,0,0,0,0,1,0,0,1,0,0
81,2,2,3,4,0,1,0,0,0,0,0,0,1,0,0,1,0,1
82,0,1,3,2,1,0,0,1,0,0,0,0,1,0,0,0,0,1
83,0,1,3,2,1,1,0,1,0,0,0,0,1,0,0,1,0,1
84,2,0,2,2,1,0,1,0,0,0,1,0,0,0,1,0,0,1
85,2,0,2,7,0,0,0,0,1,0,0,0,0,0,0,0,0,1
86,2,1,0,1,0,1,1,0,0,1,0,0,0,0,0,1,0,1
87,3,2,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1
88,2,1,0,4,1,1,1,0,0,0,0,0,1,0,0,1,0,1
89,2,1,1,4,1,0,0,0,0,0,0,0,1,0,0,1,0,1
90,2,0,1,4,1,0,1,0,0,1,0,0,0,0,0,1,0,1
91,2,0,1,7,0,1,1,0,0,1,0,0,0,0,0,1,0,1
92,2,2,0,2,1,1,0,0,0,0,0,0,0,0,0,1,0,0
93,0,0,0,1,1,1,0,1,0,0,0,0,1,0,0,1,0,0
94,1,0,1,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0
95,1,0,1,7,1,0,1,0,0,1,0,0,0,0,1,1,0,0
96,1,0,1,7,1,1,1,0,0,0,0,0,0,0,0,1,0,0
97,1,0,1,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
98,1,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0
99,1,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0
100,1,0,1,7,1,0,0,0,0,1,0,0,0,0,1,1,0,0
101,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
102,5,5,4,2,0,0,0,0,0,0,0,0,0,0,0,1,0,0
103,0,0,1,7,1,0,0,0,0,0,0,0,0,0,0,1,0,0
104,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0
105,0,0,1,7,1,0,0,0,0,0,0,0,0,0,0,0,0,0
106,0,0,1,7,1,0,1,0,0,0,0,0,0,0,0,0,0,0
107,1,0,1,7,1,1,0,0,0,0,0,0,0,0,0,1,0,0
108,0,0,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
109,0,0,2,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0
110,1,0,1,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
111,1,0,1,1,1,1,0,0,0,1,0,0,0,0,1,1,0,0
112,1,0,1,1,1,1,0,0,0,1,0,0,0,0,1,1,0,0
113,5,4,2,7,0,1,1,0,0,0,0,0,0,0,0,1,0,0
114,5,4,2,7,0,0,0,0,0,1,0,0,0,0,1,1,0,0
115,5,4,2,1,0,1,1,0,0,1,0,0,0,0,1,1,0,0
116,5,4,2,7,0,1,1,0,0,1,0,0,0,0,1,1,0,0
117,5,4,3,11,1,1,0,0,0,1,0,0,0,0,1,1,0,0
118,1,0,1,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0
119,2,0,2,1,0,0,1,0,0,1,0,1,0,0,0,0,0,0
120,2,0,1,7,1,0,0,0,0,0,0,0,1,0,0,1,0,0
121,5,4,3,11,0,1,1,0,0,1,0,0,0,0,1,1,0,0
122,5,4,3,7,0,1,1,0,0,1,0,0,0,0,1,1,0,0
123,5,4,3,11,0,1,1,0,0,1,0,0,0,0,1,1,0,0
124,1,0,1,7,1,0,1,0,0,1,0,0,0,0,1,1,0,0
125,1,0,1,7,0,0,0,0,0,1,0,0,0,0,1,1,0,0
126,2,1,2,1,1,1,1,0,1,0,0,0,0,0,1,0,0,0
127,0,0,1,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
128,0,0,1,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
129,0,0,1,7,1,0,0,0,1,0,0,0,0,0,1,1,0,1
130,0,0,2,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
131,0,0,2,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1
132,0,0,2,7,1,0,0,0,1,0,0,0,0,0,1,0,0,1
133,0,0,2,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1
134,5,0,2,7,1,0,1,0,1,0,0,0,0,0,1,1,0,0
135,0,0,2,7,1,0,1,0,0,0,1,1,0,0,0,0,0,1
136,0,0,2,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1
137,0,0,2,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
138,0,0,2,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1
139,2,0,2,7,0,0,0,0,0,1,0,1,0,0,0,0,0,0
140,0,0,2,7,0,0,1,0,0,0,1,1,0,0,0,0,0,1
141,0,0,2,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1
142,0,0,2,1,0,0,1,0,1,0,0,0,0,0,1,0,0,1
143,0,0,2,7,0,1,1,0,1,0,0,0,0,0,1,1,0,1
144,0,0,2,1,1,0,1,0,1,0,0,0,0,0,1,0,0,1
145,0,0,2,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1
146,2,0,2,7,0,0,0,0,0,0,0,0,1,0,0,1,0,0
147,2,0,1,1,1,1,1,1,0,0,0,0,1,0,0,1,0,0
148,2,0,2,7,0,1,1,0,0,0,0,0,1,0,0,1,0,0
149,2,0,2,1,0,1,1,0,0,0,0,0,1,0,0,1,0,0
150,2,0,2,7,0,0,1,0,0,0,0,0,1,0,0,1,0,0
151,2,0,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0
152,0,0,2,7,1,0,1,0,1,0,0,0,0,0,1,1,0,1
153,0,0,2,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
154,0,0,1,7,1,0,0,0,0,1,0,0,0,0,1,1,0,1
155,0,0,1,2,1,0,1,0,0,1,0,0,0,0,1,0,0,1
156,0,0,1,2,1,0,0,0,0,1,0,0,0,0,1,0,0,1
157,0,0,2,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
158,0,0,2,7,1,0,1,0,1,0,0,0,0,0,1,1,0,1
159,0,0,2,2,0,0,0,0,1,0,0,0,0,0,1,0,0,1
160,0,0,1,7,1,0,1,0,0,1,0,0,0,0,1,0,0,1
161,0,0,1,2,0,0,0,0,0,1,0,0,0,0,1,0,0,1
162,0,0,1,7,1,0,1,0,0,1,0,0,0,0,1,1,0,1
163,0,0,1,7,0,1,1,0,0,1,0,0,0,0,1,1,0,1
164,0,0,1,2,0,0,1,0,0,1,0,0,0,0,1,0,0,1
165,0,0,1,2,0,1,0,0,0,1,0,0,0,0,1,0,0,1
166,0,0,2,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1
167,0,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,1
168,0,0,1,1,1,0,1,0,0,0,0,0,1,0,0,0,0,1
169,4,4,1,1,0,1,1,0,0,0,0,0,1,0,0,1,0,1
170,4,4,1,1,0,1,0,0,0,0,0,0,1,0,0,1,0,1
171,1,0,2,2,1,0,1,0,0,0,0,0,1,0,0,1,0,1
172,1,0,2,2,0,1,0,0,0,0,0,0,1,0,0,1,0,1
173,0,0,4,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1
174,0,1,0,4,0,1,1,1,0,0,0,0,1,0,0,1,0,1
175,0,0,2,7,1,0,1,0,0,1,0,0,0,0,1,1,0,1
176,4,4,1,2,0,1,1,0,0,0,0,0,1,0,0,1,0,1
177,2,4,2,7,0,1,1,1,0,0,0,0,1,0,0,1,0,1
178,2,3,3,2,0,1,1,1,0,0,0,0,1,0,0,1,0,1
179,2,4,3,7,0,1,0,1,0,0,0,0,1,0,0,1,0,1
180,1,3,4,1,0,1,0,0,0,0,0,0,1,0,0,1,0,1
181,2,3,2,1,0,1,1,1,0,0,0,0,1,0,0,1,0,1
182,4,0,2,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
183,4,0,2,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
184,4,0,2,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
185,4,0,2,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
186,4,0,2,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
187,4,0,2,11,0,1,0,1,0,0,0,0,1,0,0,1,0,1
188,4,0,2,2,0,1,0,1,0,0,0,0,1,0,0,0,0,1
189,4,0,2,11,1,0,1,1,0,0,0,0,1,0,0,1,0,1
190,5,0,2,11,0,1,1,0,0,0,0,0,1,0,0,1,0,1
191,5,0,3,11,1,0,0,0,0,0,0,0,1,0,0,1,0,1
192,4,0,2,4,0,1,1,0,0,0,0,0,1,0,0,1,0,1
193,4,0,2,4,0,1,1,0,0,0,0,0,1,0,0,1,0,1
194,4,0,2,4,0,1,0,0,0,0,0,0,1,0,0,1,0,1
195,5,0,3,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
196,5,0,3,11,0,1,1,0,0,0,0,0,1,0,0,1,0,1
197,3,1,1,2,0,1,0,0,0,0,0,0,1,0,0,0,0,1
198,4,1,1,11,0,0,0,0,0,0,0,0,1,0,0,1,0,1
199,4,1,1,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
200,4,1,1,2,0,1,1,0,0,0,0,0,1,0,0,1,0,1
201,4,1,1,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
202,5,0,2,2,0,1,0,0,0,0,0,0,1,0,0,0,0,1
203,2,1,2,11,0,1,1,0,1,0,0,0,0,0,0,1,0,1
204,2,1,2,4,0,1,0,0,1,0,0,0,0,0,0,1,0,1
205,2,1,2,11,0,1,0,0,1,0,0,0,0,0,0,1,0,1
206,2,1,1,11,0,1,1,0,0,1,0,0,0,0,0,1,0,1
207,2,1,1,11,0,0,0,0,0,1,0,0,0,0,0,1,0,1
208,2,1,0,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
209,2,1,0,11,0,1,0,0,0,0,0,0,1,0,0,1,0,1
210,4,1,2,11,0,1,1,0,0,1,0,0,0,0,0,1,0,1
211,2,1,2,4,0,1,0,0,1,0,0,0,0,0,0,1,0,1
212,2,1,2,4,0,1,0,0,1,0,0,0,0,0,0,1,0,1
213,2,1,2,11,0,0,0,0,0,1,0,0,0,0,0,1,0,1
214,2,1,2,11,0,0,1,0,0,1,0,0,0,0,0,1,0,1
215,2,1,2,11,0,1,0,0,0,0,1,0,0,0,1,1,0,1
216,2,1,2,11,1,0,0,0,0,1,0,0,0,0,0,1,0,1
217,2,1,2,11,1,0,0,0,0,1,0,0,0,0,0,1,0,1
218,2,1,2,4,0,0,0,0,0,1,0,0,0,0,0,0,0,1
219,2,1,2,11,0,1,1,0,1,0,0,0,0,0,0,1,0,1
220,2,1,1,11,0,1,0,0,0,1,0,0,0,0,0,1,0,1
221,4,2,1,2,0,1,1,0,0,1,0,0,0,0,0,1,0,1
222,3,1,1,2,0,1,0,0,0,0,0,0,1,0,0,1,0,1
223,2,1,2,4,0,0,0,0,1,0,0,0,0,0,0,1,0,1
224,2,1,2,11,1,0,0,0,1,0,0,0,0,0,0,1,0,1
225,2,1,1,11,0,1,0,0,0,1,0,0,0,0,0,1,0,1
226,2,1,1,4,0,1,0,0,0,1,0,0,0,0,0,1,0,1
227,2,1,2,11,1,0,1,0,0,1,0,0,0,0,0,1,0,1
228,2,1,2,11,0,1,0,0,0,1,0,0,0,0,0,1,0,1
229,4,2,1,11,0,0,1,0,0,1,0,0,0,0,0,1,0,1
230,4,2,2,4,0,1,0,0,0,1,0,0,0,0,0,0,0,1
231,2,1,2,11,0,1,1,0,1,0,0,0,0,0,0,1,0,1
232,3,1,2,4,0,1,0,0,1,0,0,0,0,0,0,0,0,1
233,4,2,2,11,0,1,1,0,0,1,0,0,0,0,0,1,0,1
234,4,2,2,11,0,0,0,0,0,1,0,0,0,0,0,1,0,1
235,4,2,2,11,0,1,1,0,0,1,0,0,0,0,0,1,0,1
236,5,2,2,11,0,0,1,0,0,1,0,0,0,0,0,1,0,1
237,2,3,4,1,1,0,1,0,0,0,0,0,1,0,0,0,1,0
238,2,3,4,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0
239,2,4,2,7,1,1,0,0,0,1,0,0,0,0,0,0,1,0
240,2,3,4,7,1,1,0,0,0,1,0,0,0,0,0,1,1,0
241,2,3,4,7,1,0,0,0,0,1,0,0,0,0,0,1,1,0
242,2,4,3,7,1,1,1,0,0,1,0,0,0,0,0,1,1,0
243,2,3,3,1,1,1,0,0,0,1,0,0,0,0,0,1,1,0
244,2,3,3,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0
245,3,4,4,7,1,1,1,0,1,0,0,0,0,0,0,0,1,0
246,3,4,4,7,1,1,0,0,1,0,0,0,0,0,0,0,1,0
247,3,4,3,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0
248,3,4,4,11,0,1,1,0,0,1,0,0,0,0,0,1,1,0
249,3,4,3,1,1,1,0,0,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18234,5,3,1,7,0,1,1,0,0,0,0,0,1,0,0,1,0,1
18235,4,3,2,2,0,0,1,0,0,1,0,0,0,0,0,0,0,1
18236,4,3,3,7,1,0,1,0,0,1,0,0,0,0,0,1,0,1
18237,4,3,3,7,1,0,0,0,0,1,0,0,0,0,0,1,0,1
18238,4,1,3,2,1,0,1,0,0,1,0,0,0,0,0,0,0,1
18239,4,1,4,2,1,0,0,0,0,1,0,0,0,0,0,0,0,1
18240,5,4,3,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
18241,5,4,4,2,0,0,0,0,0,1,0,0,0,0,0,0,0,1
18242,3,2,4,7,1,1,1,0,0,1,0,0,0,0,0,1,0,1
18243,1,3,1,7,0,0,1,0,0,0,0,0,1,0,0,1,0,1
18244,1,3,2,7,0,0,1,0,0,0,0,0,1,0,0,1,0,1
18245,1,2,4,1,0,1,1,0,0,0,0,0,1,0,0,1,0,1
18246,1,2,4,4,0,0,1,0,0,0,0,0,1,0,0,0,0,1
18247,5,4,3,7,1,0,0,0,0,1,0,0,0,0,0,1,0,1
18248,4,3,2,7,0,0,1,0,1,0,0,0,0,0,0,1,0,1
18249,4,3,2,7,0,1,1,0,1,0,0,0,0,0,0,1,0,1
18250,3,2,4,2,0,0,1,0,0,1,0,0,0,0,0,0,0,1
18251,1,3,3,7,0,1,0,0,0,0,0,0,1,0,0,1,0,1
18252,1,3,3,1,1,1,1,0,0,0,0,0,1,0,0,1,0,1
18253,3,3,3,4,0,0,0,0,0,0,0,0,1,0,0,0,0,1
18254,2,0,2,7,1,1,0,0,1,0,0,0,0,0,0,1,0,1
18255,3,2,1,2,1,0,1,0,0,1,0,0,0,0,0,0,0,1
18256,2,1,1,11,1,1,1,0,1,0,0,0,0,0,0,0,0,1
18257,2,1,1,11,0,0,1,0,1,0,0,0,0,0,0,1,0,1
18258,2,1,1,11,1,1,0,0,1,0,0,0,0,0,0,1,0,1
18259,2,0,2,7,0,0,1,0,0,0,1,0,0,0,1,1,0,1
18260,4,0,2,2,0,0,1,1,0,0,0,0,1,0,0,0,0,1
18261,2,3,3,1,1,0,1,1,0,0,0,0,1,0,0,0,0,1
18262,2,0,2,2,0,0,0,1,0,0,0,0,1,0,0,0,0,1
18263,4,0,2,2,0,1,1,1,0,0,0,0,1,0,0,0,0,1
18264,4,0,2,2,1,1,0,0,0,0,0,0,1,0,0,0,0,1
18265,4,0,2,2,1,0,0,0,0,0,0,0,1,0,0,0,0,1
18266,5,4,3,2,0,0,1,0,0,1,0,0,0,0,0,0,0,1
18267,5,4,3,7,0,1,0,0,0,1,0,0,0,0,0,1,0,1
18268,4,3,3,7,0,1,1,0,1,0,0,0,0,0,0,1,0,1
18269,4,3,3,7,0,1,0,0,1,0,0,0,0,0,0,1,0,1
18270,0,3,1,7,0,1,1,0,0,1,0,0,0,0,0,1,0,1
18271,0,3,1,2,0,0,1,0,0,1,0,0,0,0,0,0,0,1
18272,0,3,2,7,0,1,1,0,0,1,0,0,0,0,0,1,0,1
18273,0,3,2,7,0,1,1,0,0,1,0,0,0,0,0,1,0,1
18274,5,4,3,7,1,0,1,0,1,0,0,0,0,0,0,1,0,1
18275,3,0,2,2,1,0,0,1,0,0,0,0,1,0,0,0,0,1
18276,3,0,2,7,1,1,0,1,0,0,0,0,1,0,0,1,0,1
18277,3,0,2,2,1,0,0,1,0,0,0,0,1,0,0,0,0,1
18278,3,0,2,7,1,0,0,1,0,0,0,0,1,0,0,1,0,1
18279,3,0,2,7,1,0,0,1,0,0,0,0,1,0,0,1,0,1
18280,3,0,2,2,1,0,0,0,0,1,0,0,0,0,0,0,0,1
18281,4,0,2,2,1,0,1,0,0,1,0,0,0,0,0,0,0,1
18282,4,0,2,7,0,1,0,0,1,0,0,0,0,0,0,1,0,1
18283,4,0,2,2,0,1,1,0,1,0,0,0,0,0,0,0,0,1
18284,4,0,2,2,0,0,0,0,1,0,0,0,0,0,0,0,0,1
18285,4,0,2,2,1,0,1,0,1,0,0,0,0,0,0,0,0,1
18286,3,3,2,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
18287,4,4,1,7,0,1,0,0,0,0,0,0,0,0,0,1,0,0
18288,4,4,2,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0
18289,0,0,1,7,1,0,1,0,0,0,0,0,0,0,0,1,0,0
18290,5,5,2,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
18291,3,2,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0
18292,2,2,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
18293,3,3,0,2,1,0,1,0,0,0,0,0,0,0,0,1,0,0
18294,1,0,1,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0
18295,0,0,2,2,1,0,1,1,0,0,0,0,1,0,0,1,0,0
18296,0,0,3,2,0,0,0,1,0,0,0,0,1,0,0,0,0,0
18297,1,0,1,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0
18298,1,0,1,7,1,0,0,0,0,1,0,0,0,0,1,1,0,0
18299,1,0,1,7,1,1,0,0,0,1,0,0,0,0,1,1,0,0
18300,0,0,1,7,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18301,5,5,4,2,0,1,1,0,0,0,0,0,0,0,0,1,0,0
18302,0,0,1,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18303,0,0,1,7,1,0,1,0,0,0,0,0,0,0,0,1,0,0
18304,5,0,1,11,0,1,1,0,0,0,0,0,0,0,0,1,0,0
18305,5,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18306,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18307,0,0,1,7,0,0,1,0,0,0,0,0,0,0,0,0,0,0
18308,0,0,2,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18309,0,0,2,7,1,0,1,0,0,0,0,0,0,0,0,1,0,0
18310,0,0,2,7,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18311,1,0,1,7,1,0,0,0,0,1,0,0,0,0,1,1,0,0
18312,5,4,2,7,0,0,0,0,0,1,0,0,0,0,1,1,0,0
18313,1,0,1,7,1,1,1,0,0,1,0,0,0,0,1,1,0,0
18314,1,0,1,7,1,1,0,0,0,1,0,0,0,0,1,1,0,0
18315,2,0,1,7,0,1,0,0,0,0,0,0,0,0,0,1,0,0
18316,2,0,1,4,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18317,2,0,1,4,1,0,1,0,0,0,0,0,0,0,0,0,0,0
18318,4,0,2,2,1,1,1,0,0,0,0,0,1,0,0,1,0,0
18319,1,0,1,1,1,0,1,0,0,1,0,0,0,0,1,0,0,0
18320,5,4,3,7,0,1,1,0,0,1,0,0,0,0,1,0,0,0
18321,5,4,3,7,0,0,1,0,0,1,0,0,0,0,1,1,0,0
18322,0,0,2,7,0,0,1,0,1,0,0,0,0,0,1,1,0,1
18323,0,0,2,7,0,0,0,0,1,0,0,0,0,0,1,1,0,1
18324,0,0,2,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
18325,0,0,2,1,0,1,1,0,1,0,0,0,0,0,1,0,0,1
18326,0,0,2,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1
18327,0,0,2,1,0,1,1,0,1,0,0,0,0,0,1,0,0,1
18328,0,0,2,7,0,1,1,0,1,0,0,0,0,0,1,1,0,1
18329,0,0,2,7,0,0,1,0,1,0,0,0,0,0,1,1,0,1
18330,0,0,2,7,0,1,0,0,1,0,0,0,0,0,1,1,0,1
18331,2,0,2,1,0,1,1,0,0,1,0,1,0,0,0,0,0,0
18332,2,0,2,7,0,0,0,0,0,1,0,1,0,0,0,0,0,0
18333,2,0,2,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
18334,0,0,2,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1
18335,0,0,2,1,1,0,1,0,0,0,1,1,0,0,0,0,0,1
18336,0,0,2,1,1,0,1,0,1,0,0,0,0,0,1,0,0,1
18337,2,0,2,7,0,0,1,0,0,1,0,1,0,0,0,1,0,0
18338,2,0,2,7,0,1,0,0,0,0,0,0,1,0,0,1,0,0
18339,0,0,2,7,0,0,1,0,0,0,1,1,0,0,0,0,0,1
18340,0,0,2,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1
18341,0,0,2,7,0,0,1,0,0,0,1,1,0,0,0,0,0,1
18342,2,0,2,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0
18343,2,0,2,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0
18344,2,0,2,7,1,0,1,0,0,0,0,0,1,0,0,1,0,0
18345,2,0,2,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0
18346,2,0,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0
18347,0,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1
18348,3,3,1,4,0,1,1,0,0,0,0,0,0,0,1,1,0,1
18349,3,3,2,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1
18350,3,3,2,4,1,0,0,0,0,0,0,0,0,0,1,1,0,1
18351,3,3,2,1,0,0,1,0,0,0,0,0,0,0,1,0,0,1
18352,3,3,3,11,1,0,0,0,0,0,0,0,0,0,1,0,0,1
18353,3,3,3,11,0,1,1,0,0,0,0,0,0,0,1,1,0,1
18354,0,0,0,4,1,0,1,1,0,0,0,0,0,0,0,1,0,1
18355,0,0,0,1,1,1,0,1,0,0,0,1,0,0,0,1,1,0
18356,0,0,0,1,1,1,1,1,0,0,0,1,0,0,0,1,1,0
18357,0,0,0,1,1,0,1,1,0,0,0,1,0,0,0,0,1,0
18358,0,0,0,1,1,1,0,1,0,0,0,1,0,0,0,0,1,0
18359,0,0,0,1,1,1,1,1,0,0,0,1,0,0,0,0,1,0
18360,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18361,1,1,1,4,1,0,0,0,0,1,0,0,0,1,0,0,1,0
18362,1,1,1,4,1,0,1,0,0,1,0,0,0,1,0,1,1,0
18363,1,1,1,4,1,0,0,0,0,1,0,0,0,1,0,1,1,0
18364,4,4,1,1,1,1,1,0,0,0,1,0,0,1,0,1,1,0
18365,1,1,1,4,1,0,0,0,1,0,0,0,0,1,0,1,1,0
18366,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18367,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18368,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18369,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,1,1,0
18370,1,0,1,4,0,0,1,0,0,0,0,1,0,0,0,0,1,0
18371,2,2,0,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0
18372,1,1,2,1,0,1,0,0,0,0,0,0,0,0,1,1,1,0
18373,1,1,2,1,0,1,1,0,0,0,0,0,0,0,1,1,1,0
18374,2,2,1,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0
18375,2,2,1,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0
18376,2,2,2,1,0,0,1,0,1,0,0,0,0,1,0,1,1,0
18377,1,1,2,1,0,1,0,0,0,0,0,0,0,0,1,1,1,0
18378,1,1,2,1,0,1,1,0,0,0,0,0,0,0,1,0,1,0
18379,1,1,2,1,0,1,1,0,0,0,0,0,0,0,1,1,1,0
18380,3,3,0,1,1,1,0,0,1,0,0,0,0,1,0,1,1,0
18381,3,3,0,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0
18382,3,3,0,1,1,1,0,0,1,0,0,0,0,1,0,1,1,0
18383,3,2,2,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0
18384,4,2,2,1,0,1,0,0,0,0,1,0,0,1,0,1,1,0
18385,4,4,1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,0
18386,2,0,1,4,0,0,1,0,0,1,0,0,0,1,0,1,1,0
18387,4,0,2,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0
18388,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0
18389,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0
18390,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0
18391,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0
18392,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,1,0
18393,2,2,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0
18394,1,0,1,4,0,0,0,0,0,1,0,1,0,0,0,1,1,0
18395,2,0,1,2,0,0,0,0,0,1,0,1,0,0,0,0,1,0
18396,1,0,1,1,0,1,1,0,0,0,0,0,0,0,1,0,1,0
18397,2,2,1,1,1,1,1,0,0,1,0,1,0,0,0,1,1,0
18398,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0
18399,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0
18400,1,0,0,1,1,1,1,0,0,0,0,0,0,0,1,1,1,0
18401,1,0,0,1,1,1,1,0,0,0,0,0,0,0,1,1,1,0
18402,2,2,2,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0
18403,1,0,0,1,1,1,1,0,0,0,0,0,0,0,1,1,1,0
18404,3,3,0,1,1,0,0,0,0,1,0,1,0,0,0,0,1,0
18405,0,0,1,4,0,0,0,0,1,0,0,0,0,1,0,0,1,0
18406,0,0,2,1,0,1,0,0,0,0,1,0,0,1,0,0,1,0
18407,4,4,1,1,1,1,0,0,1,0,0,0,0,1,0,1,1,0
18408,4,4,2,1,0,1,0,0,1,0,0,0,0,1,0,1,1,0
18409,3,3,1,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0
18410,3,3,1,1,1,0,1,0,0,1,0,1,0,0,0,1,1,0
18411,1,0,0,1,1,1,0,0,0,0,0,0,0,0,1,1,1,0
18412,1,0,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,0
18413,3,3,2,1,0,1,1,0,0,1,0,1,0,0,0,1,1,0
18414,3,3,2,1,1,0,0,0,0,1,0,1,0,0,0,0,1,0
18415,0,0,1,4,1,0,1,0,0,1,0,1,0,0,0,1,1,0
18416,0,0,2,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0
18417,0,0,2,1,0,1,0,0,0,0,1,0,0,1,0,1,1,0
18418,0,0,1,7,0,0,0,0,1,0,0,0,0,1,0,0,1,0
18419,0,0,1,4,0,0,0,0,1,0,0,0,0,1,0,1,1,0
18420,0,0,1,4,0,1,0,0,1,0,0,0,0,1,0,0,1,0
18421,0,0,1,4,0,0,1,0,1,0,0,0,0,1,0,0,1,0
18422,0,0,1,4,0,0,1,0,1,0,0,0,0,1,0,1,1,0
18423,0,0,1,4,0,0,1,0,1,0,0,0,0,1,0,0,1,0
18424,0,0,2,1,0,1,1,0,0,0,1,0,0,1,0,1,1,0
18425,0,0,2,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0
18426,0,0,2,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0
18427,0,0,2,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0
18428,0,0,2,2,0,1,1,0,0,0,1,0,0,1,0,1,1,0
18429,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0
18430,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0
18431,1,1,0,1,1,1,0,0,0,0,0,0,0,0,1,0,1,0
18432,1,1,0,1,1,1,0,0,0,0,0,0,0,0,1,1,1,0
18433,1,1,0,2,1,1,1,0,0,0,0,0,0,0,1,1,1,0
18434,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,1,0
18435,1,0,0,1,0,1,1,0,0,0,0,0,0,1,0,1,1,0
18436,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0
18437,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0
18438,1,0,0,1,0,1,1,1,0,0,0,1,0,0,0,1,1,0
18439,1,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,1,0
18440,1,0,0,1,0,0,1,1,0,0,0,1,0,0,0,1,1,0
18441,1,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,1,0
18442,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
18443,2,0,0,1,0,0,1,0,0,1,0,0,0,1,0,1,1,0
18444,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,1,0
18445,2,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0
18446,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0
18447,2,0,1,4,0,0,0,0,0,0,0,1,0,0,0,0,1,0
18448,1,0,0,1,1,0,0,0,0,1,0,0,0,1,0,1,1,0
18449,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0
18450,2,0,1,2,1,0,1,0,0,1,0,0,0,1,0,1,1,0
18451,3,0,1,4,0,0,1,0,0,1,0,0,0,1,0,0,1,0
18452,0,0,1,4,1,0,0,0,0,1,0,0,0,1,0,1,0,0
18453,0,0,0,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0
18454,0,0,1,4,1,1,0,0,0,1,0,0,0,1,0,1,0,0
18455,0,0,1,4,1,1,0,0,0,1,0,0,0,1,0,1,0,0
18456,0,0,1,4,1,0,0,0,0,1,0,0,0,1,0,1,0,0
18457,0,0,1,4,1,0,0,0,0,1,0,0,0,1,0,0,0,0
18458,0,0,1,4,1,0,1,0,1,0,0,0,0,1,0,1,0,0
18459,0,0,1,4,1,0,1,0,1,0,0,0,0,1,0,0,0,0
18460,0,0,2,1,1,1,1,0,1,0,0,0,0,1,0,0,0,0
18461,0,0,2,1,1,1,1,0,1,0,0,0,0,1,0,1,0,0
18462,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,1,0,0
18463,1,1,0,4,1,0,1,0,1,0,0,0,0,1,0,1,0,0
18464,1,1,0,2,1,0,1,0,1,0,0,0,0,1,0,0,0,0
18465,0,0,0,1,1,0,1,0,0,1,0,0,0,1,0,1,0,0

In [98]:
X=mergedfinal9.drop('BikeBuyer',axis=1)
y=mergedfinal9['BikeBuyer']

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [101]:
from sklearn.linear_model import LogisticRegression

In [102]:
logmodel=LogisticRegression(solver='newton-cg')
logmodel.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [103]:
predictions=logmodel.predict(X_test)

In [104]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.6345113595384061

Burada sonuç normalden 0.01 azaldı

-----

### Sadece regresyon katsayısı 0'dan büyük olan sütunları eğittiğimizdeki sonuç

In [140]:
X=mergedfinal6.drop('BikeBuyer',axis=1)
y=mergedfinal6['BikeBuyer']

In [141]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [142]:
logreg=LogisticRegression(fit_intercept=False)
logreg.fit(X_train,y_train)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=False,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [144]:
np.round(logreg.coef_,decimals=2)>0

array([[False, False, False, False,  True, False, False, False, False,
         True,  True, False,  True, False,  True,  True,  True, False,
        False]])

In [114]:
X.columns

Index(['YearlyIncome', 'TotalChildren', 'NumberChildrenAtHome', 'NumberCarsOwned', 'Age', 'CommuteDistanceNumeric', 'M', 'M', 'Graduate Degree',
       'High School', 'Partial College', 'Partial High School', 'Clerical', 'Management', 'Manual', 'Skilled Manual', 'Yes', 'Europe',
       'North America'],
      dtype='object')

In [116]:
logreg='Age','High School','Partial College','Clerical','Manual','Skilled Manual','Yes'

In [128]:
X=mergedfinal6[['Age','High School','Partial College','Clerical','Manual','Skilled Manual','Yes']]
y=mergedfinal6['BikeBuyer']

In [129]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [130]:
from sklearn.linear_model import LogisticRegression

In [134]:
logmodel=LogisticRegression()
logmodel.fit(X_train,y_train)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [135]:
predictions=logmodel.predict(X_test)

In [136]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.5580598629642985

0.1 azaldı

----

### GridSearch yöntemi kullanarak Lojistik Regresyon modelimizdeki en optimal C katsayısını bulma

In [198]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range = (0,1))

scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

In [197]:
X=mergedfinal6.drop('BikeBuyer',axis=1).values
y=mergedfinal6['BikeBuyer'].values

In [199]:
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.3,random_state=3)

In [200]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
grid={"C":np.logspace(-3,6,7), "penalty":["l1","l2"]}# l1 lasso l2 ridge
logreg=LogisticRegression()
logreg_cv=GridSearchCV(logreg,grid,cv=10)
logreg_cv.fit(X_train,y_train)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': array([1.00000e-03, 3.16228e-02, 1.00000e+00, 3.16228e+01, 1.00000e+03,
       3.16228e+04, 1.00000e+06]), 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [201]:
print("tuned hpyerparameters :(best parameters) ",logreg_cv.best_params_)
print("accuracy :",logreg_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'C': 1.0, 'penalty': 'l2'}
accuracy : 0.6441490183954244

In [202]:
logreg2=LogisticRegression(C=9,penalty="l2")
logreg2.fit(X_train,y_train)
print("score",logreg2.score(X_test,y_test))

C:\Users\samay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

score 0.6393797331410025

### RandomForestClassifier modeli kullanarak accuracy score'u arttırma

RandomForestClassifier modelinin en iyi parametrelerini bulmak için tek tek deneme yanılma yoluyla işlem yapamayız.
Bu yüzden GridSearch modelini kullandık bulduğumuz parametreyi modele uyguladık.

In [203]:
from sklearn.pipeline import *

In [204]:
from sklearn.ensemble import RandomForestClassifier

In [205]:
# Create first pipeline for base without reducing features.

pipe = Pipeline([('classifier' , RandomForestClassifier())])
# pipe = Pipeline([('classifier', RandomForestClassifier())])

In [214]:
# Create param grid.

param_grid = [
    {'classifier' : [LogisticRegression()],
     'classifier__penalty' : ['l1', 'l2'],
    'classifier__C' : np.logspace(-4, 4, 20),
    'classifier__solver' : ['liblinear']},
    {'classifier' : [RandomForestClassifier()],
    'classifier__n_estimators' : list(range(10,101,10))}
]

In [215]:
clf = GridSearchCV(pipe, param_grid = param_grid, cv = 5, verbose=True, n_jobs=-1)

# Fit on data

best_clf = clf.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    4.4s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   14.4s
[Parallel(n_jobs=-1)]: Done 250 out of 250 | elapsed:   30.8s finished

In [221]:
best_clf.best_params_

{'classifier': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
             oob_score=False, random_state=None, verbose=0,
             warm_start=False), 'classifier__n_estimators': 100}

In [222]:
rfc=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
             oob_score=False, random_state=None, verbose=0,
             warm_start=False)

In [223]:
rfc.fit(X_train,y_train)
print("score",rfc.score(X_test,y_test))

score 0.7908402452217814

**Accuracy score'u yüzde 64ten yüzde 79'a çıkarmayı başardık**

In [226]:
Xdf = pd.DataFrame(X)

In [227]:
X_new=Xdf.sample(5,random_state=99)
X_new

          0   1   2   3    4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
5471   10000   4   0   2  101   1   1   0   0   1   0   0   0   0   1   0   0   1   0
12364  40000   0   0   1   50   4   0   0   0   0   0   0   0   0   0   0   0   0   1
7989   70000   5   0   2   63   4   1   0   0   0   0   0   0   1   0   0   1   0   1
10396  40000   0   0   2   38   2   0   0   0   0   1   0   0   0   0   1   0   0   1
758    70000   5   5   3   40  11   1   1   0   0   0   0   0   0   0   0   1   0   0

In [233]:
mergedfinal6.columns

Index(['YearlyIncome', 'TotalChildren', 'NumberChildrenAtHome', 'NumberCarsOwned', 'Age', 'CommuteDistanceNumeric', 'BikeBuyer', 'M', 'M',
       'Graduate Degree', 'High School', 'Partial College', 'Partial High School', 'Clerical', 'Management', 'Manual', 'Skilled Manual', 'Yes',
       'Europe', 'North America'],
      dtype='object')

In [228]:
rfc.predict(X_new)

array([0, 0, 0, 1, 0], dtype=int64)

Burada da yeni gelen müşterilerin bilgilerini X_new vasıtasıyla modele soktuk.Daha sonra predict edip alıp almayacaklarını gördük.